//! The action table and the help dialog's editing keys.

use super::*;

pub const ACTIONS: &[ActionDef] = &[
    ActionDef {
        action: Action::Sessions,
        name: "sessions",
        aliases: &["resume", "continue"],
        label: "switch sessions",
        keys: "",
        group: "sessions",
        args: "",
    },
    ActionDef {
        action: Action::Skills,
        name: "skills",
        aliases: &[],
        label: "insert a skill reference",
        keys: "",
        group: "settings",
        args: "",
    },
    ActionDef {
        action: Action::Palette,
        name: "palette",
        aliases: &["commands"],
        label: "command palette",
        keys: "/  Ctrl-Shift-p  Cmd-k",
        group: "general",
        args: "",
    },
    ActionDef {
        action: Action::Help,
        name: "help",
        aliases: &["keys"],
        label: "all keys",
        keys: "?",
        group: "general",
        args: "",
    },
    ActionDef {
        action: Action::Web,
        name: "web",
        aliases: &[],
        label: "open the web dashboard",
        keys: "",
        group: "general",
        args: "",
    },
    ActionDef {
        action: Action::Quit,
        name: "quit",
        aliases: &["q", "detach", "exit"],
        label: "leave; every agent keeps running",
        keys: "Ctrl-q",
        group: "general",
        args: "",
    },
    ActionDef {
        action: Action::NewDraft,
        name: "new",
        aliases: &["draft", "clear"],
        label: "new session tab",
        keys: "Ctrl-t  Alt-n  Ctrl-x then n",
        group: "sessions",
        args: "",
    },
    ActionDef {
        action: Action::NewForm,
        name: "form",
        aliases: &[],
        label: "new session form (agent, name, directory, permissions)",
        keys: "",
        group: "sessions",
        args: "",
    },
    ActionDef {
        action: Action::NextSession,
        name: "next",
        aliases: &[],
        label: "next session",
        keys: "Ctrl-n (sidebar)  Alt-]",
        group: "sessions",
        args: "",
    },
    ActionDef {
        action: Action::PrevSession,
        name: "prev",
        aliases: &["previous"],
        label: "previous session",
        keys: "Ctrl-p (sidebar)  Alt-[",
        group: "sessions",
        args: "",
    },
    ActionDef {
        action: Action::Goto,
        name: "go",
        aliases: &["goto", "switch", "open"],
        label: "switch to a session by name or title",
        keys: "",
        group: "sessions",
        args: "NAME",
    },
    ActionDef {
        action: Action::Rename,
        name: "rename",
        aliases: &[],
        label: "rename the session",
        keys: "r (sidebar)",
        group: "sessions",
        args: "NAME",
    },
    ActionDef {
        action: Action::Fork,
        name: "fork",
        aliases: &[],
        label: "fork the session with its history",
        keys: "f (sidebar)",
        group: "sessions",
        args: "",
    },
    ActionDef {
        action: Action::Stop,
        name: "stop",
        aliases: &["kill"],
        label: "stop the agent process (session stays resumable)",
        keys: "x (sidebar)",
        group: "sessions",
        args: "",
    },
    ActionDef {
        action: Action::Delete,
        name: "delete",
        aliases: &["purge"],
        label: "delete the session and its history",
        keys: "X (sidebar)",
        group: "sessions",
        args: "",
    },
    ActionDef {
        action: Action::Export,
        name: "export",
        aliases: &[],
        label: "export a session bundle",
        keys: "",
        group: "sessions",
        args: "[DEST]",
    },
    ActionDef {
        action: Action::Import,
        name: "import",
        aliases: &[],
        label: "import a session bundle",
        keys: "",
        group: "sessions",
        args: "PATH",
    },
    ActionDef {
        action: Action::Send,
        name: "send",
        aliases: &[],
        label: "send the message",
        keys: "Enter",
        group: "talking",
        args: "",
    },
    ActionDef {
        action: Action::Steer,
        name: "steer",
        aliases: &[],
        label: "steer the running turn, or queue when the agent cannot steer",
        keys: "Ctrl-s",
        group: "talking",
        args: "",
    },
    ActionDef {
        action: Action::Cancel,
        name: "cancel",
        aliases: &["interrupt", "pause"],
        label: "interrupt the running turn",
        keys: "Esc  Ctrl-g",
        group: "talking",
        args: "",
    },
    ActionDef {
        action: Action::Allow,
        name: "allow",
        aliases: &["yes"],
        label: "allow the pending permission",
        keys: "y",
        group: "talking",
        args: "",
    },
    ActionDef {
        action: Action::Deny,
        name: "deny",
        aliases: &["no"],
        label: "reject the pending permission",
        keys: "n",
        group: "talking",
        args: "",
    },
    ActionDef {
        action: Action::ReloadCatalog,
        name: "reload",
        aliases: &["refresh"],
        label: "reload harness catalog without stopping sessions",
        keys: "",
        group: "settings",
        args: "",
    },
    ActionDef {
        action: Action::Model,
        name: "model",
        aliases: &["models"],
        label: "pick harness and model",
        keys: "Ctrl-l  Alt-m",
        group: "settings",
        args: "[MODEL]",
    },
    ActionDef {
        action: Action::Mode,
        name: "mode",
        aliases: &[],
        label: "pick the agent mode",
        keys: "Ctrl-o",
        group: "settings",
        args: "[MODE]",
    },
    ActionDef {
        action: Action::Effort,
        name: "effort",
        aliases: &["reasoning"],
        label: "pick the thinking effort",
        keys: "Alt-e",
        group: "settings",
        args: "[LEVEL]",
    },
    ActionDef {
        action: Action::Policy,
        name: "policy",
        aliases: &["perms", "permissions"],
        label: "permission policy: ask · approve-reads · approve-edits · approve-all · deny-all",
        keys: "Alt-p",
        group: "settings",
        args: "[POLICY]",
    },
    ActionDef {
        action: Action::Directory,
        name: "cwd",
        aliases: &["dir", "directory", "cd"],
        label: "working directory (a live session forks into a new tab)",
        keys: "Alt-Shift-d",
        group: "settings",
        args: "[PATH]",
    },
    ActionDef {
        action: Action::Agent,
        name: "harness",
        aliases: &[],
        label: "harness for the current draft",
        keys: "",
        group: "settings",
        args: "NAME",
    },
    ActionDef {
        action: Action::Set,
        name: "set",
        aliases: &["config", "option"],
        label: "any agent option: /set KEY or /set KEY=VALUE",
        keys: "",
        group: "settings",
        args: "KEY[=VALUE]",
    },
    ActionDef {
        action: Action::ToggleSystem,
        name: "system",
        aliases: &["events", "lifecycle"],
        label: "show or hide lifecycle events (stopped, resumed, renamed, model set)",
        keys: "",
        group: "reading",
        args: "",
    },
    ActionDef {
        action: Action::ToggleThoughts,
        name: "thoughts",
        aliases: &["thinking-text", "thinking"],
        label: "show or hide the agent's thinking text",
        keys: "",
        group: "reading",
        args: "",
    },
    ActionDef {
        action: Action::ScrollTop,
        name: "top",
        aliases: &[],
        label: "scroll to the top",
        keys: "Home  g (transcript)",
        group: "reading",
        args: "",
    },
    ActionDef {
        action: Action::ScrollBottom,
        name: "bottom",
        aliases: &["follow"],
        label: "scroll to the bottom and follow",
        keys: "End  G (transcript)",
        group: "reading",
        args: "",
    },
    ActionDef {
        action: Action::PageUp,
        name: "pageup",
        aliases: &[],
        label: "scroll up one page",
        keys: "PgUp",
        group: "reading",
        args: "",
    },
    ActionDef {
        action: Action::PageDown,
        name: "pagedown",
        aliases: &[],
        label: "scroll down one page",
        keys: "PgDn",
        group: "reading",
        args: "",
    },
    ActionDef {
        action: Action::FocusSidebar,
        name: "sidebar",
        aliases: &["focus-sidebar"],
        label: "focus the sidebar (Option-j/k step)",
        keys: "Cmd-Ctrl-h  Alt-h  Tab",
        group: "focus",
        args: "",
    },
    ActionDef {
        action: Action::FocusContent,
        name: "content",
        aliases: &["focus-content"],
        label: "focus the content area",
        keys: "Cmd-Ctrl-l  Alt-l",
        group: "focus",
        args: "",
    },
    ActionDef {
        action: Action::FocusTranscript,
        name: "transcript",
        aliases: &["focus-transcript"],
        label: "focus the transcript (j/k scroll)",
        keys: "Cmd-Ctrl-k  Alt-k",
        group: "focus",
        args: "",
    },
    ActionDef {
        action: Action::FocusComposer,
        name: "composer",
        aliases: &["focus-composer", "input"],
        label: "focus the composer",
        keys: "Cmd-Ctrl-j  Alt-j",
        group: "focus",
        args: "",
    },
    ActionDef {
        action: Action::ToggleSidebar,
        name: "toggle-sidebar",
        aliases: &["hide-sidebar", "show-sidebar"],
        label: "hide or show the sidebar",
        keys: "Alt-s",
        group: "focus",
        args: "",
    },
    ActionDef {
        action: Action::SidebarNarrow,
        name: "narrow",
        aliases: &[],
        label: "narrow the sidebar",
        keys: "Alt-Left",
        group: "focus",
        args: "",
    },
    ActionDef {
        action: Action::SidebarWiden,
        name: "widen",
        aliases: &[],
        label: "widen the sidebar",
        keys: "Alt-Right",
        group: "focus",
        args: "",
    },
    ActionDef {
        action: Action::AddHost,
        name: "host",
        aliases: &["peer", "add-host"],
        label: "mirror another machine over ssh",
        keys: "",
        group: "hosts",
        args: "add NAME URL | rm NAME",
    },
    ActionDef {
        action: Action::RemoveHost,
        name: "remove-host",
        aliases: &["peer-rm"],
        label: "remove a host",
        keys: "",
        group: "hosts",
        args: "NAME",
    },
    ActionDef {
        action: Action::Undo,
        name: "undo",
        aliases: &[],
        label: "undo in the composer",
        keys: "Ctrl-z",
        group: "editing",
        args: "",
    },
];

/// Keys that are not actions but belong in the help dialog.
pub const EDITING_KEYS: &[(&str, &str)] = &[
    ("Ctrl-j", "newline (also Shift-Enter, or a trailing \\ then Enter)"),
    ("Ctrl-n / Ctrl-p", "next / previous line in the composer; history at the ends"),
    ("Ctrl-a / Ctrl-e", "start / end of line"),
    ("Alt-b / Alt-f", "word left / right"),
    ("Ctrl-w  Alt-d", "delete word back / forward"),
    ("Ctrl-k / Ctrl-u", "kill to end / start of line"),
    ("Alt-1…9", "jump to a visible session in the sidebar"),
    ("y / n / 1-9", "answer the permission card above the composer"),
    (
        "click",
        "a chip in the composer changes permissions, model or effort; a handle, thought or tool line opens or closes it",
    ),
    (
        "wheel",
        "scroll the transcript; drag selects and copies; double / triple click selects a word / line",
    ),
    ("drag the sidebar edge", "resize the sidebar; hover a session for its details"),
];
