/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as AppsInstalledRouteImport } from './routes/apps/installed'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations/index'
import { Route as IntegrationsCallbackRouteImport } from './routes/integrations/callback'
import { Route as AppsPublisherNameRouteImport } from './routes/apps/$publisher.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsInstalledRoute = AppsInstalledRouteImport.update({
  id: '/apps/installed',
  path: '/apps/installed',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsCallbackRoute = IntegrationsCallbackRouteImport.update({
  id: '/integrations/callback',
  path: '/integrations/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsPublisherNameRoute = AppsPublisherNameRouteImport.update({
  id: '/apps/$publisher/$name',
  path: '/apps/$publisher/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/devices': typeof DevicesRoute
  '/team': typeof TeamRoute
  '/apps/installed': typeof AppsInstalledRoute
  '/integrations/callback': typeof IntegrationsCallbackRoute
  '/apps/': typeof AppsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/apps/$publisher/$name': typeof AppsPublisherNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/devices': typeof DevicesRoute
  '/team': typeof TeamRoute
  '/apps/installed': typeof AppsInstalledRoute
  '/integrations/callback': typeof IntegrationsCallbackRoute
  '/apps': typeof AppsIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/apps/$publisher/$name': typeof AppsPublisherNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/devices': typeof DevicesRoute
  '/team': typeof TeamRoute
  '/apps/installed': typeof AppsInstalledRoute
  '/integrations/callback': typeof IntegrationsCallbackRoute
  '/apps/': typeof AppsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/apps/$publisher/$name': typeof AppsPublisherNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/devices'
    | '/team'
    | '/apps/installed'
    | '/integrations/callback'
    | '/apps/'
    | '/integrations/'
    | '/apps/$publisher/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/devices'
    | '/team'
    | '/apps/installed'
    | '/integrations/callback'
    | '/apps'
    | '/integrations'
    | '/apps/$publisher/$name'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/devices'
    | '/team'
    | '/apps/installed'
    | '/integrations/callback'
    | '/apps/'
    | '/integrations/'
    | '/apps/$publisher/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRoute
  DevicesRoute: typeof DevicesRoute
  TeamRoute: typeof TeamRoute
  AppsInstalledRoute: typeof AppsInstalledRoute
  IntegrationsCallbackRoute: typeof IntegrationsCallbackRoute
  AppsIndexRoute: typeof AppsIndexRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  AppsPublisherNameRoute: typeof AppsPublisherNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/installed': {
      id: '/apps/installed'
      path: '/apps/installed'
      fullPath: '/apps/installed'
      preLoaderRoute: typeof AppsInstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/callback': {
      id: '/integrations/callback'
      path: '/integrations/callback'
      fullPath: '/integrations/callback'
      preLoaderRoute: typeof IntegrationsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$publisher/$name': {
      id: '/apps/$publisher/$name'
      path: '/apps/$publisher/$name'
      fullPath: '/apps/$publisher/$name'
      preLoaderRoute: typeof AppsPublisherNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRoute,
  DevicesRoute: DevicesRoute,
  TeamRoute: TeamRoute,
  AppsInstalledRoute: AppsInstalledRoute,
  IntegrationsCallbackRoute: IntegrationsCallbackRoute,
  AppsIndexRoute: AppsIndexRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  AppsPublisherNameRoute: AppsPublisherNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
