// Code generated by cmux pane-protocol codegen. DO NOT EDIT.
// Generated from pane-protocol IR 0.0.0-test (SHA-256 05390a990bb38d8ee4531f8ca47fe2111e8c7c722427e3f27db4758fc877c665).

package richpane

// IR the package was generated from.
const (
	IRVersion = "0.0.0-test"
	IRSHA256  = "05390a990bb38d8ee4531f8ca47fe2111e8c7c722427e3f27db4758fc877c665"
)

// Op names.
const (
	OpComExampleRichDocClose = "com.example.rich.doc.close"
	OpComExampleRichDocOpen  = "com.example.rich.doc.open"
)

// Event stream names.
const (
	EventComExampleRichDocChanged = "com.example.rich.doc.changed"
)

// Op error codes declared in the IR.
const (
	ErrComExampleRichLocked   = "com.example.rich.locked"
	ErrComExampleRichNotFound = "com.example.rich.not_found"
)

// ProviderNamespaces are the namespaces this package serves.
var ProviderNamespaces = []string{"com.example.rich"}
