// Code generated by cmux pane-protocol codegen. DO NOT EDIT.
// Generated from pane-protocol IR 0.0.0-test (SHA-256 05390a990bb38d8ee4531f8ca47fe2111e8c7c722427e3f27db4758fc877c665).

package richpane

import (
	"context"
	"encoding/json"
	"fmt"

	pane "github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane"
)

// App is the app id that owns com.example.rich.
const App = "com.example.rich"

// NewProvider creates a provider for App that owns ProviderNamespaces. Register
// a handler for each namespace, then call Run.
func NewProvider() (*pane.Provider, error) {
	p, err := pane.NewProvider(App, ProviderNamespaces...)
	if err != nil {
		return nil, err
	}
	p.IRVersion, p.IRSHA256 = IRVersion, IRSHA256
	return p, nil
}

// ComExampleRichHandler serves the ops of namespace com.example.rich. Params arrive validated;
// results are validated before they are sent. Return *pane.Error with a
// declared code for expected failures; any other error is logged and sent
// as cmux.internal.
type ComExampleRichHandler interface {
	// DocClose serves com.example.rich.doc.close (mutation, scope com.example.rich:edit; errors: none).
	DocClose(ctx context.Context, call *pane.Call, params ComExampleRichDocCloseParams) (ComExampleRichDocCloseResult, error)
	// DocOpen serves com.example.rich.doc.open (mutation, scope com.example.rich:edit; errors: com.example.rich.not_found, com.example.rich.locked).
	DocOpen(ctx context.Context, call *pane.Call, params ComExampleRichDocOpenParams) (Doc, error)
}

// RegisterComExampleRich registers h for every op and event of com.example.rich.
func RegisterComExampleRich(p *pane.Provider, h ComExampleRichHandler) error {
	if err := p.Register(pane.OpSpec{
		Name: OpComExampleRichDocClose, Kind: "mutation", Scope: "com.example.rich:edit", Errors: nil,
		Handle: func(ctx context.Context, call *pane.Call, raw json.RawMessage) (json.RawMessage, error) {
			params, err := pane.DecodeAndValidate[ComExampleRichDocCloseParams](raw, ValidateComExampleRichDocCloseParams, pane.CodeInvalidParams)
			if err != nil {
				return nil, err
			}
			result, err := h.DocClose(ctx, call, params)
			if err != nil {
				return nil, err
			}
			out, err := pane.EncodeAndValidate(result, ValidateComExampleRichDocCloseResult, pane.CodeInvalidResult)
			if err != nil {
				return nil, fmt.Errorf("%s returned an invalid result: %v", OpComExampleRichDocClose, err)
			}
			return out, nil
		},
	}); err != nil {
		return err
	}
	if err := p.Register(pane.OpSpec{
		Name: OpComExampleRichDocOpen, Kind: "mutation", Scope: "com.example.rich:edit", Errors: []string{"com.example.rich.not_found", "com.example.rich.locked"},
		Handle: func(ctx context.Context, call *pane.Call, raw json.RawMessage) (json.RawMessage, error) {
			params, err := pane.DecodeAndValidate[ComExampleRichDocOpenParams](raw, ValidateComExampleRichDocOpenParams, pane.CodeInvalidParams)
			if err != nil {
				return nil, err
			}
			result, err := h.DocOpen(ctx, call, params)
			if err != nil {
				return nil, err
			}
			out, err := pane.EncodeAndValidate(result, ValidateDoc, pane.CodeInvalidResult)
			if err != nil {
				return nil, fmt.Errorf("%s returned an invalid result: %v", OpComExampleRichDocOpen, err)
			}
			return out, nil
		},
	}); err != nil {
		return err
	}
	if err := p.RegisterEvent(pane.EventSpec{Name: EventComExampleRichDocChanged, Scope: "com.example.rich:read", Validate: ValidateDoc}); err != nil {
		return err
	}
	return nil
}

// PublishComExampleRichDocChanged publishes com.example.rich.doc.changed to its subscribers.
func PublishComExampleRichDocChanged(p *pane.Provider, data Doc) error {
	raw, err := pane.EncodeAndValidate(data, ValidateDoc, pane.CodeInvalidEvent)
	if err != nil {
		return err
	}
	return p.Publish(EventComExampleRichDocChanged, raw)
}
