#!/usr/bin/env bun
// Builds dist/cmux-app-runtime.js (one IIFE, engine-neutral). `--check` exits 1 when dist is stale.
import { readFileSync, writeFileSync, existsSync } from "node:fs"
const here = new URL(".", import.meta.url).pathname
const out = await Bun.build({ entrypoints: [`${here}src/index.ts`], format: "iife", target: "browser", minify: false, root: `${here}src` })
if (!out.success) {
  for (const log of out.logs) console.error(log)
  process.exit(1)
}
const banner = "// Generated by cmux-tui/crates/cmux-app-host/js/build.ts from js/src. Do not edit.\n"
// Bun names each module in a comment relative to the cwd; drop them so the output is cwd-independent.
const code = banner + (await out.outputs[0]!.text()).replace(/^\s*\/\/ \S+\.ts\n/gm, "")
const target = `${here}dist/cmux-app-runtime.js`
if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : ""
  if (current !== code) {
    console.error("dist/cmux-app-runtime.js is stale: run bun js/build.ts")
    process.exit(1)
  }
  console.log("dist up to date")
} else {
  writeFileSync(target, code)
  console.log(`wrote ${target} (${code.length} bytes)`)
}
