import Foundation
import Testing

#if canImport(cmux_DEV)
@testable import cmux_DEV
#elseif canImport(cmux)
@testable import cmux
#endif

@MainActor
struct SidebarAgentSurfaceNameTests {
    @Test
    func userSetSurfaceNameIsAppendedWithoutChangingUnnamedRowText() throws {
        let workspace = Workspace()
        let panelId = try #require(workspace.focusedPanelId)
        workspace.recordAgentPID(
            key: "claude_code.only",
            pid: 111,
            panelId: panelId,
            refreshPorts: false
        )
        workspace.panelTitles[panelId] = "workers"

        #expect(try #require(workspace.sidebarAgentStatusRows().first).paneLabel == "workers")

        #expect(workspace.setPanelCustomTitle(panelId: panelId, title: "  fix-pr93  "))
        #expect(
            try #require(workspace.sidebarAgentStatusRows().first).paneLabel
                == "workers · fix-pr93"
        )

        #expect(workspace.setPanelCustomTitle(panelId: panelId, title: nil))
        #expect(try #require(workspace.sidebarAgentStatusRows().first).paneLabel == "workers")
    }

    @Test
    func autoGeneratedTitleRemainsTheBaseUntilUserClaimsIt() throws {
        let workspace = Workspace()
        let panelId = try #require(workspace.focusedPanelId)
        workspace.recordAgentPID(
            key: "claude_code.only",
            pid: 111,
            panelId: panelId,
            refreshPorts: false
        )
        workspace.panelTitles[panelId] = "workers"

        #expect(
            workspace.setPanelCustomTitle(
                panelId: panelId,
                title: "Generated topic",
                source: .auto
            )
        )
        #expect(
            try #require(workspace.sidebarAgentStatusRows().first).paneLabel
                == "Generated topic"
        )

        #expect(
            workspace.setPanelCustomTitle(
                panelId: panelId,
                title: "Generated topic",
                source: .user
            )
        )
        #expect(
            try #require(workspace.sidebarAgentStatusRows().first).paneLabel
                == "workers · Generated topic"
        )
    }

    @Test
    func duplicateSurfaceNameIsNotRenderedTwice() throws {
        let workspace = Workspace()
        let panelId = try #require(workspace.focusedPanelId)
        workspace.recordAgentPID(
            key: "claude_code.only",
            pid: 111,
            panelId: panelId,
            refreshPorts: false
        )
        workspace.panelTitles[panelId] = "fix-pr93"

        #expect(workspace.setPanelCustomTitle(panelId: panelId, title: "fix-pr93"))
        #expect(try #require(workspace.sidebarAgentStatusRows().first).paneLabel == "fix-pr93")
    }
}
