from __future__ import annotations

import copy
import json
import shutil
import tempfile
import unittest
from pathlib import Path

from codegen.pane import generate as pane_generate
from codegen.pane.emit_go import render
from codegen.pane.ir import PaneIRError, parse_pane_ir

GO_PANE = Path(__file__).resolve().parents[2] / "go-pane"
SEED = GO_PANE / "testdata" / "pane-protocol.seed.json"
RICH = GO_PANE / "testdata" / "pane-protocol.rich.json"

# Committed generated packages and the arguments that produce them.
COMMITTED = (
    (SEED, GO_PANE / "examples" / "hello" / "hellopane", "hellopane", ("com.example.hello",)),
    (RICH, GO_PANE / "internal" / "richpane", "richpane", ("com.example.rich",)),
)


def seed() -> dict:
    return json.loads(SEED.read_text(encoding="utf-8"))


def parse(document: dict):
    return parse_pane_ir(json.dumps(document))


@unittest.skipUnless(shutil.which("gofmt"), "gofmt is required for Go generation")
class PaneGoEmitterTests(unittest.TestCase):
    def test_committed_packages_match_the_ir(self) -> None:
        for ir_path, out, package, provider_ns in COMMITTED:
            problems = pane_generate.run(
                ir_path=ir_path, out=out, package=package, provider_ns=provider_ns, mode="check"
            )
            self.assertEqual(problems, [], f"regenerate {out} with codegen/pane/generate.py --write")

    def test_output_is_deterministic(self) -> None:
        ir = parse(seed())
        first = render(ir, package="x", provider_namespaces=("com.example.hello",))
        second = render(parse(seed()), package="x", provider_namespaces=("com.example.hello",))
        self.assertEqual(first, second)
        self.assertEqual(sorted(first), ["client.go", "ops.go", "provider.go", "types.go", "validate.go"])

    def test_client_only_package_has_no_provider(self) -> None:
        files = render(parse(seed()), package="x")
        self.assertNotIn("provider.go", files)
        self.assertIn("func (c ComExampleHelloClient) GreetSay(", files["client.go"])

    def test_provider_has_one_handler_interface_per_owned_namespace(self) -> None:
        provider = render(parse(seed()), package="x", provider_namespaces=("com.example.hello",))["provider.go"]
        self.assertIn("type ComExampleHelloHandler interface", provider)
        self.assertNotIn("CmuxHandler", provider)
        self.assertIn('const App = "com.example.hello"', provider)

    def test_check_mode_reports_drift(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "pkg"
            args = dict(ir_path=SEED, out=out, package="pkg", provider_ns=("com.example.hello",))
            self.assertTrue(pane_generate.run(mode="check", **args))
            pane_generate.run(mode="write", **args)
            self.assertEqual(pane_generate.run(mode="check", **args), [])
            (out / "types.go").write_text("// edited\n", encoding="utf-8")
            (out / "extra.go").write_text(
                "// Code generated by cmux pane-protocol codegen. DO NOT EDIT.\npackage pkg\n",
                encoding="utf-8",
            )
            (out / "handwritten_test.go").write_text("package pkg\n", encoding="utf-8")
            problems = pane_generate.run(mode="check", **args)
            self.assertTrue(any("stale" in p and "types.go" in p for p in problems), problems)
            self.assertTrue(any("extra.go" in p for p in problems), problems)
            self.assertFalse(any("handwritten" in p for p in problems), problems)
            pane_generate.run(mode="write", **args)
            self.assertFalse((out / "extra.go").exists())
            self.assertTrue((out / "handwritten_test.go").exists())


class PaneIRTests(unittest.TestCase):
    def assertRefused(self, document: dict, fragment: str) -> None:
        with self.assertRaises(PaneIRError) as caught:
            parse(document)
        self.assertIn(fragment, str(caught.exception))

    def test_unsupported_keywords_are_refused(self) -> None:
        cases = {
            "pattern": ({"type": "string", "pattern": "^a"}, "pattern is not supported"),
            "oneOf": ({"oneOf": [{"type": "string"}, {"type": "integer"}]}, "oneOf is supported only"),
            "union": ({"type": ["string", "integer"]}, "union types"),
            "ref sibling": ({"$ref": "#/types/HelloResult", "minimum": 1}, "unsupported schema keyword"),
            "allOf": ({"allOf": [{"type": "string"}]}, "unsupported schema keyword"),
            "float format": ({"type": "integer", "format": "float"}, "integer format"),
            "external ref": ({"$ref": "other.json#/X"}, "unsupported $ref"),
        }
        for name, (schema, fragment) in cases.items():
            with self.subTest(name):
                document = seed()
                document["types"]["HelloParams"]["properties"]["name"] = schema
                self.assertRefused(document, fragment)

    def test_ops_must_stay_in_their_namespace(self) -> None:
        document = seed()
        document["ops"][2]["name"] = "com.example.other.greet.say"
        self.assertRefused(document, "outside every declared namespace")
        document = seed()
        document["ops"][0]["errors"] = ["com.example.hello.oops"]
        self.assertRefused(document, "outside namespace 'cmux'")
        document = seed()
        document["ops"][2]["name"] = "com.example.hello.say"
        self.assertRefused(document, "<namespace>.<family>.<verb>")

    def test_third_party_namespace_is_its_app_id(self) -> None:
        document = seed()
        document["namespaces"][1]["owner"] = "app:com.example.other"
        self.assertRefused(document, "is not its owner's app id")

    def test_unknown_refs_and_duplicates(self) -> None:
        document = seed()
        document["ops"][2]["result"] = {"$ref": "#/types/Missing"}
        self.assertRefused(document, "unknown type 'Missing'")
        with self.assertRaises(PaneIRError):
            parse_pane_ir('{"version":"1","version":"2","namespaces":[],"ops":[],"types":{}}')

    def test_provider_namespaces_must_share_one_owner(self) -> None:
        with self.assertRaises(PaneIRError):
            render(parse(seed()), package="x", provider_namespaces=("cmux", "com.example.hello"))
        with self.assertRaises(PaneIRError):
            render(parse(seed()), package="x", provider_namespaces=("com.nope",))

    def test_schemars_nullable_shape(self) -> None:
        document = copy.deepcopy(seed())
        document["types"]["HelloResult"]["properties"]["message"] = {
            "anyOf": [{"$ref": "#/$defs/HelloParams"}, {"type": "null"}],
            "description": "schemars Option<T>",
        }
        ir = parse(document)
        self.assertEqual(type(ir.types["HelloResult"].props[0].node).__name__, "Nullable")


if __name__ == "__main__":
    unittest.main()
