// JavaScript dialogs through getJsDialog().
const browser = await agent.browsers.getDefault();
const tab = await browser.tabs.new();
await tab.goto(`${PRIMARY}/dialogs.html`);
const pw = tab.playwright;
const openDialog = async (sel) => { pw.locator(sel).click().catch(() => {}); for (let i = 0; i < 50; i++) { const d = await tab.getJsDialog(); if (d) return d; await new Promise((r) => setTimeout(r, 100)); } return null; };
let d = await openDialog("#alert");
emit("alert", d && { type: d.type, message: d.message });
await d.dismiss();
emit("after-alert", await pw.locator("#r").textContent());
d = await openDialog("#confirm");
emit("confirm", d && { type: d.type, message: d.message });
await d.accept();
emit("after-confirm", await pw.locator("#r").textContent());
d = await openDialog("#prompt");
emit("prompt", d && { type: d.type, message: d.message, defaultValue: d.defaultValue ?? null });
await d.accept("typed answer");
emit("after-prompt", await pw.locator("#r").textContent());
emit("none-open", (await tab.getJsDialog()) ?? null);
await tab.close();
