/**
 * Regenerates apps/api/src/domains/public-suffix-data.ts from the Public
 * Suffix List (https://publicsuffix.org, MPL-2.0). IDN rules are stored in
 * their ASCII (punycode) form, the form domain claims use.
 *
 *   bun scripts/update-public-suffix.ts [path-to-public_suffix_list.dat]
 */
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

const source = process.argv[2]
  ? readFileSync(process.argv[2], "utf8")
  : await (await fetch("https://publicsuffix.org/list/public_suffix_list.dat")).text()
const ascii = (rule: string) => {
  const prefix = rule.startsWith("!") ? "!" : rule.startsWith("*.") ? "*." : ""
  const rest = rule.slice(prefix.length)
  return prefix + new URL(`http://${rest}`).hostname
}
const rules = source
  .split("\n")
  .map((l) => l.trim())
  .filter((l) => l && !l.startsWith("//"))
  .map((l) => ascii(l.split(/\s/)[0]!))
const out = `// Generated by backend/scripts/update-public-suffix.ts on ${new Date().toISOString().slice(0, 10)}. Do not edit.
// Data: the Public Suffix List, https://publicsuffix.org/list/public_suffix_list.dat
// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
// If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
export const PUBLIC_SUFFIX_RULES = ${JSON.stringify(rules.join("\n"))}
`
writeFileSync(fileURLToPath(new URL("../apps/api/src/domains/public-suffix-data.ts", import.meta.url)), out)
console.log(`wrote ${rules.length} rules`)
