// @generated by cmux-vm-codegen from workers/cmux-vm/openapi.json. Do not edit; run
// workers/cmux-vm/cli/scripts/regenerate.sh instead.

#[allow(unused_imports)]
pub use progenitor_client::{ByteStream, ClientInfo, Error, ResponseValue};
#[allow(unused_imports)]
use progenitor_client::{ClientHooks, OperationInfo, RequestBuilderExt, encode_path};
/// Types used as operation parameters and responses.
#[allow(clippy::all)]
pub mod types {
    ///`Conflict`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct Conflict {
        pub message: ::std::string::String,
        #[serde(rename = "_tag")]
        pub tag: ConflictTag,
    }
    ///`ConflictTag`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum ConflictTag {
        Conflict,
    }
    impl ::std::fmt::Display for ConflictTag {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Conflict => f.write_str("Conflict"),
            }
        }
    }
    impl ::std::str::FromStr for ConflictTag {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "Conflict" => Ok(Self::Conflict),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ConflictTag {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ConflictTag {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`CreateVmRequest`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
    pub struct CreateVmRequest {
        ///a string at most 100 character(s) long
        #[serde(
            rename = "displayName",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub display_name: ::std::option::Option<CreateVmRequestDisplayName>,
        #[serde(
            rename = "idleTimeoutSeconds",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub idle_timeout_seconds: ::std::option::Option<i64>,
        ///a string matching the pattern ^snap_[0123456789abcdefghjkmnpqrstvwxyz]{26}$
        #[serde(
            rename = "snapshotId",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub snapshot_id: ::std::option::Option<CreateVmRequestSnapshotId>,
    }
    ///a string at most 100 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct CreateVmRequestDisplayName(::std::string::String);
    impl ::std::ops::Deref for CreateVmRequestDisplayName {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<CreateVmRequestDisplayName> for ::std::string::String {
        fn from(value: CreateVmRequestDisplayName) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for CreateVmRequestDisplayName {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 100usize {
                return Err("longer than 100 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for CreateVmRequestDisplayName {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for CreateVmRequestDisplayName {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for CreateVmRequestDisplayName {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///a string matching the pattern ^snap_[0123456789abcdefghjkmnpqrstvwxyz]{26}$
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct CreateVmRequestSnapshotId(::std::string::String);
    impl ::std::ops::Deref for CreateVmRequestSnapshotId {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<CreateVmRequestSnapshotId> for ::std::string::String {
        fn from(value: CreateVmRequestSnapshotId) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for CreateVmRequestSnapshotId {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
                ::std::sync::LazyLock::new(|| {
                    ::regress::Regex::new("^snap_[0123456789abcdefghjkmnpqrstvwxyz]{26}$").unwrap()
                });
            if PATTERN.find(value).is_none() {
                return Err(
                    "doesn't match pattern \"^snap_[0123456789abcdefghjkmnpqrstvwxyz]{26}$\""
                        .into(),
                );
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for CreateVmRequestSnapshotId {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for CreateVmRequestSnapshotId {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for CreateVmRequestSnapshotId {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///`Forbidden`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct Forbidden {
        pub message: ::std::string::String,
        #[serde(
            rename = "missingScope",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub missing_scope: ::std::option::Option<::std::string::String>,
        #[serde(rename = "_tag")]
        pub tag: ForbiddenTag,
    }
    ///`ForbiddenTag`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum ForbiddenTag {
        Forbidden,
    }
    impl ::std::fmt::Display for ForbiddenTag {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Forbidden => f.write_str("Forbidden"),
            }
        }
    }
    impl ::std::str::FromStr for ForbiddenTag {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "Forbidden" => Ok(Self::Forbidden),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ForbiddenTag {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ForbiddenTag {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`ForkVmRequest`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
    pub struct ForkVmRequest {
        ///a string at most 100 character(s) long
        #[serde(
            rename = "displayName",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub display_name: ::std::option::Option<ForkVmRequestDisplayName>,
        #[serde(
            rename = "idleTimeoutSeconds",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub idle_timeout_seconds: ::std::option::Option<i64>,
    }
    ///a string at most 100 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct ForkVmRequestDisplayName(::std::string::String);
    impl ::std::ops::Deref for ForkVmRequestDisplayName {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<ForkVmRequestDisplayName> for ::std::string::String {
        fn from(value: ForkVmRequestDisplayName) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for ForkVmRequestDisplayName {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 100usize {
                return Err("longer than 100 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for ForkVmRequestDisplayName {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ForkVmRequestDisplayName {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for ForkVmRequestDisplayName {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///`Health`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct Health {
        pub ok: bool,
    }
    ///The request did not match the expected schema
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct HttpApiDecodeError {
        pub issues: ::std::vec::Vec<Issue>,
        pub message: ::std::string::String,
        #[serde(rename = "_tag")]
        pub tag: HttpApiDecodeErrorTag,
    }
    ///`HttpApiDecodeErrorTag`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum HttpApiDecodeErrorTag {
        HttpApiDecodeError,
    }
    impl ::std::fmt::Display for HttpApiDecodeErrorTag {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::HttpApiDecodeError => f.write_str("HttpApiDecodeError"),
            }
        }
    }
    impl ::std::str::FromStr for HttpApiDecodeErrorTag {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "HttpApiDecodeError" => Ok(Self::HttpApiDecodeError),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for HttpApiDecodeErrorTag {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for HttpApiDecodeErrorTag {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///an integer
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(transparent)]
    pub struct Int(pub i64);
    impl ::std::ops::Deref for Int {
        type Target = i64;
        fn deref(&self) -> &i64 {
            &self.0
        }
    }
    impl ::std::convert::From<Int> for i64 {
        fn from(value: Int) -> Self {
            value.0
        }
    }
    impl ::std::convert::From<i64> for Int {
        fn from(value: i64) -> Self {
            Self(value)
        }
    }
    impl ::std::fmt::Display for Int {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            self.0.fmt(f)
        }
    }
    impl ::std::str::FromStr for Int {
        type Err = <i64 as ::std::str::FromStr>::Err;
        fn from_str(value: &str) -> ::std::result::Result<Self, Self::Err> {
            Ok(Self(value.parse()?))
        }
    }
    impl ::std::convert::TryFrom<&str> for Int {
        type Error = <i64 as ::std::str::FromStr>::Err;
        fn try_from(value: &str) -> ::std::result::Result<Self, Self::Error> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<String> for Int {
        type Error = <i64 as ::std::str::FromStr>::Err;
        fn try_from(value: String) -> ::std::result::Result<Self, Self::Error> {
            value.parse()
        }
    }
    ///Represents an error encountered while parsing a value to match the schema
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct Issue {
        ///A descriptive message explaining the issue
        pub message: ::std::string::String,
        ///The path to the property where the issue occurred
        pub path: ::std::vec::Vec<PropertyKey>,
        ///The tag identifying the type of parse issue
        #[serde(rename = "_tag")]
        pub tag: ::std::string::String,
    }
    ///`NotFound`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct NotFound {
        pub message: ::std::string::String,
        #[serde(rename = "_tag")]
        pub tag: NotFoundTag,
    }
    ///`NotFoundTag`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum NotFoundTag {
        NotFound,
    }
    impl ::std::fmt::Display for NotFoundTag {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::NotFound => f.write_str("NotFound"),
            }
        }
    }
    impl ::std::str::FromStr for NotFoundTag {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "NotFound" => Ok(Self::NotFound),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for NotFoundTag {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for NotFoundTag {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`NotImplemented`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct NotImplemented {
        pub message: ::std::string::String,
        #[serde(rename = "_tag")]
        pub tag: NotImplementedTag,
    }
    ///`NotImplementedTag`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum NotImplementedTag {
        NotImplemented,
    }
    impl ::std::fmt::Display for NotImplementedTag {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::NotImplemented => f.write_str("NotImplemented"),
            }
        }
    }
    impl ::std::str::FromStr for NotImplementedTag {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "NotImplemented" => Ok(Self::NotImplemented),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for NotImplementedTag {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for NotImplementedTag {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`PaymentRequired`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct PaymentRequired {
        pub message: ::std::string::String,
        #[serde(rename = "_tag")]
        pub tag: PaymentRequiredTag,
    }
    ///`PaymentRequiredTag`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum PaymentRequiredTag {
        PaymentRequired,
    }
    impl ::std::fmt::Display for PaymentRequiredTag {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::PaymentRequired => f.write_str("PaymentRequired"),
            }
        }
    }
    impl ::std::str::FromStr for PaymentRequiredTag {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "PaymentRequired" => Ok(Self::PaymentRequired),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for PaymentRequiredTag {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for PaymentRequiredTag {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`PropertyKey`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(untagged)]
    pub enum PropertyKey {
        String(::std::string::String),
        Number(f64),
        Object {
            key: ::std::string::String,
            #[serde(rename = "_tag")]
            tag: PropertyKeyObjectTag,
        },
    }
    impl ::std::convert::From<f64> for PropertyKey {
        fn from(value: f64) -> Self {
            Self::Number(value)
        }
    }
    ///`PropertyKeyObjectTag`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum PropertyKeyObjectTag {
        #[serde(rename = "symbol")]
        Symbol,
    }
    impl ::std::fmt::Display for PropertyKeyObjectTag {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Symbol => f.write_str("symbol"),
            }
        }
    }
    impl ::std::str::FromStr for PropertyKeyObjectTag {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "symbol" => Ok(Self::Symbol),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for PropertyKeyObjectTag {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for PropertyKeyObjectTag {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`QuotaExceeded`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct QuotaExceeded {
        pub message: ::std::string::String,
        #[serde(
            rename = "retryAfterSeconds",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub retry_after_seconds: ::std::option::Option<Int>,
        #[serde(rename = "_tag")]
        pub tag: QuotaExceededTag,
    }
    ///`QuotaExceededTag`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum QuotaExceededTag {
        QuotaExceeded,
    }
    impl ::std::fmt::Display for QuotaExceededTag {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::QuotaExceeded => f.write_str("QuotaExceeded"),
            }
        }
    }
    impl ::std::str::FromStr for QuotaExceededTag {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "QuotaExceeded" => Ok(Self::QuotaExceeded),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for QuotaExceededTag {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for QuotaExceededTag {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`ServiceUnavailable`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ServiceUnavailable {
        pub message: ::std::string::String,
        #[serde(rename = "_tag")]
        pub tag: ServiceUnavailableTag,
    }
    ///`ServiceUnavailableTag`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum ServiceUnavailableTag {
        ServiceUnavailable,
    }
    impl ::std::fmt::Display for ServiceUnavailableTag {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::ServiceUnavailable => f.write_str("ServiceUnavailable"),
            }
        }
    }
    impl ::std::str::FromStr for ServiceUnavailableTag {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "ServiceUnavailable" => Ok(Self::ServiceUnavailable),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ServiceUnavailableTag {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ServiceUnavailableTag {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`Unauthorized`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct Unauthorized {
        pub message: ::std::string::String,
        #[serde(rename = "_tag")]
        pub tag: UnauthorizedTag,
    }
    ///`UnauthorizedTag`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum UnauthorizedTag {
        Unauthorized,
    }
    impl ::std::fmt::Display for UnauthorizedTag {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Unauthorized => f.write_str("Unauthorized"),
            }
        }
    }
    impl ::std::str::FromStr for UnauthorizedTag {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "Unauthorized" => Ok(Self::Unauthorized),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for UnauthorizedTag {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for UnauthorizedTag {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`Vm`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct Vm {
        #[serde(rename = "createdAt")]
        pub created_at: ::std::string::String,
        ///a string matching the pattern ^vm_[0123456789abcdefghjkmnpqrstvwxyz]{26}$
        pub id: VmId,
        #[serde(
            rename = "idleTimeoutSeconds",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub idle_timeout_seconds: ::std::option::Option<f64>,
        pub resources: VmResources,
        pub state: ::std::string::String,
        #[serde(rename = "updatedAt")]
        pub updated_at: ::std::string::String,
    }
    ///a string matching the pattern ^vm_[0123456789abcdefghjkmnpqrstvwxyz]{26}$
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmId(::std::string::String);
    impl ::std::ops::Deref for VmId {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmId> for ::std::string::String {
        fn from(value: VmId) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmId {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            static PATTERN: ::std::sync::LazyLock<::regress::Regex> =
                ::std::sync::LazyLock::new(|| {
                    ::regress::Regex::new("^vm_[0123456789abcdefghjkmnpqrstvwxyz]{26}$").unwrap()
                });
            if PATTERN.find(value).is_none() {
                return Err(
                    "doesn't match pattern \"^vm_[0123456789abcdefghjkmnpqrstvwxyz]{26}$\"".into(),
                );
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmId {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmId {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmId {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///`VmList`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct VmList {
        pub items: ::std::vec::Vec<Vm>,
        #[serde(
            rename = "nextCursor",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub next_cursor: ::std::option::Option<::std::string::String>,
    }
    ///`VmResources`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct VmResources {
        #[serde(rename = "diskMib")]
        pub disk_mib: f64,
        #[serde(rename = "memoryMib")]
        pub memory_mib: f64,
        pub vcpus: f64,
    }
    ///a string at most 255 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmsCreateVmIdempotencyKey(::std::string::String);
    impl ::std::ops::Deref for VmsCreateVmIdempotencyKey {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmsCreateVmIdempotencyKey> for ::std::string::String {
        fn from(value: VmsCreateVmIdempotencyKey) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmsCreateVmIdempotencyKey {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 255usize {
                return Err("longer than 255 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsCreateVmIdempotencyKey {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsCreateVmIdempotencyKey {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmsCreateVmIdempotencyKey {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///a string at most 128 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmsCreateVmXCmuxTeamId(::std::string::String);
    impl ::std::ops::Deref for VmsCreateVmXCmuxTeamId {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmsCreateVmXCmuxTeamId> for ::std::string::String {
        fn from(value: VmsCreateVmXCmuxTeamId) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmsCreateVmXCmuxTeamId {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 128usize {
                return Err("longer than 128 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsCreateVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsCreateVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmsCreateVmXCmuxTeamId {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///a string at most 128 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmsDeleteVmXCmuxTeamId(::std::string::String);
    impl ::std::ops::Deref for VmsDeleteVmXCmuxTeamId {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmsDeleteVmXCmuxTeamId> for ::std::string::String {
        fn from(value: VmsDeleteVmXCmuxTeamId) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmsDeleteVmXCmuxTeamId {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 128usize {
                return Err("longer than 128 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsDeleteVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsDeleteVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmsDeleteVmXCmuxTeamId {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///a string at most 255 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmsForkVmIdempotencyKey(::std::string::String);
    impl ::std::ops::Deref for VmsForkVmIdempotencyKey {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmsForkVmIdempotencyKey> for ::std::string::String {
        fn from(value: VmsForkVmIdempotencyKey) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmsForkVmIdempotencyKey {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 255usize {
                return Err("longer than 255 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsForkVmIdempotencyKey {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsForkVmIdempotencyKey {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmsForkVmIdempotencyKey {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///a string at most 128 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmsForkVmXCmuxTeamId(::std::string::String);
    impl ::std::ops::Deref for VmsForkVmXCmuxTeamId {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmsForkVmXCmuxTeamId> for ::std::string::String {
        fn from(value: VmsForkVmXCmuxTeamId) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmsForkVmXCmuxTeamId {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 128usize {
                return Err("longer than 128 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsForkVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsForkVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmsForkVmXCmuxTeamId {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///a string at most 128 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmsGetVmXCmuxTeamId(::std::string::String);
    impl ::std::ops::Deref for VmsGetVmXCmuxTeamId {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmsGetVmXCmuxTeamId> for ::std::string::String {
        fn from(value: VmsGetVmXCmuxTeamId) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmsGetVmXCmuxTeamId {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 128usize {
                return Err("longer than 128 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsGetVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsGetVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmsGetVmXCmuxTeamId {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///a string at most 512 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmsListVmsCursor(::std::string::String);
    impl ::std::ops::Deref for VmsListVmsCursor {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmsListVmsCursor> for ::std::string::String {
        fn from(value: VmsListVmsCursor) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmsListVmsCursor {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 512usize {
                return Err("longer than 512 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsListVmsCursor {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsListVmsCursor {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmsListVmsCursor {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///`VmsListVmsState`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
    )]
    pub enum VmsListVmsState {
        #[serde(rename = "starting")]
        Starting,
        #[serde(rename = "running")]
        Running,
        #[serde(rename = "pausing")]
        Pausing,
        #[serde(rename = "paused")]
        Paused,
        #[serde(rename = "stopped")]
        Stopped,
        #[serde(rename = "unknown")]
        Unknown,
    }
    impl ::std::fmt::Display for VmsListVmsState {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Starting => f.write_str("starting"),
                Self::Running => f.write_str("running"),
                Self::Pausing => f.write_str("pausing"),
                Self::Paused => f.write_str("paused"),
                Self::Stopped => f.write_str("stopped"),
                Self::Unknown => f.write_str("unknown"),
            }
        }
    }
    impl ::std::str::FromStr for VmsListVmsState {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "starting" => Ok(Self::Starting),
                "running" => Ok(Self::Running),
                "pausing" => Ok(Self::Pausing),
                "paused" => Ok(Self::Paused),
                "stopped" => Ok(Self::Stopped),
                "unknown" => Ok(Self::Unknown),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsListVmsState {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsListVmsState {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///a string at most 128 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmsListVmsXCmuxTeamId(::std::string::String);
    impl ::std::ops::Deref for VmsListVmsXCmuxTeamId {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmsListVmsXCmuxTeamId> for ::std::string::String {
        fn from(value: VmsListVmsXCmuxTeamId) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmsListVmsXCmuxTeamId {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 128usize {
                return Err("longer than 128 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsListVmsXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsListVmsXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmsListVmsXCmuxTeamId {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///a string at most 128 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmsPauseVmXCmuxTeamId(::std::string::String);
    impl ::std::ops::Deref for VmsPauseVmXCmuxTeamId {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmsPauseVmXCmuxTeamId> for ::std::string::String {
        fn from(value: VmsPauseVmXCmuxTeamId) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmsPauseVmXCmuxTeamId {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 128usize {
                return Err("longer than 128 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsPauseVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsPauseVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmsPauseVmXCmuxTeamId {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///a string at most 128 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmsResumeVmXCmuxTeamId(::std::string::String);
    impl ::std::ops::Deref for VmsResumeVmXCmuxTeamId {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmsResumeVmXCmuxTeamId> for ::std::string::String {
        fn from(value: VmsResumeVmXCmuxTeamId) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmsResumeVmXCmuxTeamId {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 128usize {
                return Err("longer than 128 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsResumeVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsResumeVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmsResumeVmXCmuxTeamId {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///a string at most 128 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmsStartVmXCmuxTeamId(::std::string::String);
    impl ::std::ops::Deref for VmsStartVmXCmuxTeamId {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmsStartVmXCmuxTeamId> for ::std::string::String {
        fn from(value: VmsStartVmXCmuxTeamId) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmsStartVmXCmuxTeamId {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 128usize {
                return Err("longer than 128 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsStartVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsStartVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmsStartVmXCmuxTeamId {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    ///a string at most 128 character(s) long
    #[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
    #[serde(transparent)]
    pub struct VmsStopVmXCmuxTeamId(::std::string::String);
    impl ::std::ops::Deref for VmsStopVmXCmuxTeamId {
        type Target = ::std::string::String;
        fn deref(&self) -> &::std::string::String {
            &self.0
        }
    }
    impl ::std::convert::From<VmsStopVmXCmuxTeamId> for ::std::string::String {
        fn from(value: VmsStopVmXCmuxTeamId) -> Self {
            value.0
        }
    }
    impl ::std::str::FromStr for VmsStopVmXCmuxTeamId {
        type Err = self::error::ConversionError;
        fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            if value.chars().count() > 128usize {
                return Err("longer than 128 characters".into());
            }
            if value.chars().count() < 1usize {
                return Err("shorter than 1 characters".into());
            }
            Ok(Self(value.to_string()))
        }
    }
    impl ::std::convert::TryFrom<&str> for VmsStopVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for VmsStopVmXCmuxTeamId {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl<'de> ::serde::Deserialize<'de> for VmsStopVmXCmuxTeamId {
        fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
        where
            D: ::serde::Deserializer<'de>,
        {
            ::std::string::String::deserialize(deserializer)?
                .parse()
                .map_err(|e: self::error::ConversionError| {
                    <D::Error as ::serde::de::Error>::custom(e.to_string())
                })
        }
    }
    /// Error types.
    pub mod error {
        /// Error from a `TryFrom` or `FromStr` implementation.
        pub struct ConversionError(::std::borrow::Cow<'static, str>);
        impl ::std::error::Error for ConversionError {}
        impl ::std::fmt::Display for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Display::fmt(&self.0, f)
            }
        }
        impl ::std::fmt::Debug for ConversionError {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Debug::fmt(&self.0, f)
            }
        }
        impl From<&'static str> for ConversionError {
            fn from(value: &'static str) -> Self {
                Self(value.into())
            }
        }
        impl From<String> for ConversionError {
            fn from(value: String) -> Self {
                Self(value.into())
            }
        }
    }
}
#[derive(Clone, Debug)]
/**Client for cmux VM API

Tenant-scoped virtual machines for cmux.

Version: 0.1.0*/
pub struct Client {
    pub(crate) baseurl: String,
    pub(crate) client: reqwest::Client,
}
impl Client {
    /// Create a new client.
    ///
    /// `baseurl` is the base URL provided to the internal
    /// `reqwest::Client`, and should include a scheme and hostname,
    /// as well as port and a path stem if applicable.
    pub fn new(baseurl: &str) -> Self {
        #[cfg(not(target_arch = "wasm32"))]
        let client = {
            let dur = ::std::time::Duration::from_secs(15u64);
            reqwest::ClientBuilder::new()
                .connect_timeout(dur)
                .timeout(dur)
        };
        #[cfg(target_arch = "wasm32")]
        let client = reqwest::ClientBuilder::new();
        Self::new_with_client(baseurl, client.build().unwrap())
    }
    /// Construct a new client with an existing `reqwest::Client`,
    /// allowing more control over its configuration.
    ///
    /// `baseurl` is the base URL provided to the internal
    /// `reqwest::Client`, and should include a scheme and hostname,
    /// as well as port and a path stem if applicable.
    pub fn new_with_client(baseurl: &str, client: reqwest::Client) -> Self {
        Self {
            baseurl: baseurl.to_string(),
            client,
        }
    }
}
impl ClientInfo<()> for Client {
    fn api_version() -> &'static str {
        "0.1.0"
    }
    fn baseurl(&self) -> &str {
        self.baseurl.as_str()
    }
    fn client(&self) -> &reqwest::Client {
        &self.client
    }
    fn inner(&self) -> &() {
        &()
    }
}
impl ClientHooks<()> for &Client {}
#[allow(clippy::all)]
impl Client {
    /**Liveness check; no credentials needed

    Sends a `GET` request to `/healthz`

    */
    pub async fn health_health<'a>(
        &'a self,
    ) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
        let url = format!("{}/healthz", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(1usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        #[allow(unused_mut)]
        let mut request = self.client.get(url).headers(header_map).build()?;
        let info = OperationInfo {
            operation_id: "health_health",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => Ok(ResponseValue::stream(response)),
            400u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**List the tenant's VMs

    List the tenant's VMs. Requires the vm:read scope.

    Sends a `GET` request to `/v1/vms`

    Arguments:
    - `cursor`: a string at most 512 character(s) long
    - `limit`: a string to be decoded into a number
    - `state`
    - `x_cmux_team_id`: a string at most 128 character(s) long
    */
    pub async fn vms_list_vms<'a>(
        &'a self,
        cursor: Option<&'a types::VmsListVmsCursor>,
        limit: Option<&'a str>,
        state: Option<types::VmsListVmsState>,
        x_cmux_team_id: Option<&'a types::VmsListVmsXCmuxTeamId>,
    ) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
        let url = format!("{}/v1/vms", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(2usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = x_cmux_team_id {
            header_map.append("x-cmux-team-id", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self
            .client
            .get(url)
            .query(&progenitor_client::QueryParam::new("cursor", &cursor))
            .query(&progenitor_client::QueryParam::new("limit", &limit))
            .query(&progenitor_client::QueryParam::new("state", &state))
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "vms_list_vms",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => Ok(ResponseValue::stream(response)),
            400u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            401u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            403u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            501u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            503u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Create a VM

    Create a VM. Requires the vm:write scope.

    Sends a `POST` request to `/v1/vms`

    Arguments:
    - `idempotency_key`: a string at most 255 character(s) long
    - `x_cmux_team_id`: a string at most 128 character(s) long
    - `body`
    */
    pub async fn vms_create_vm<'a>(
        &'a self,
        idempotency_key: Option<&'a types::VmsCreateVmIdempotencyKey>,
        x_cmux_team_id: Option<&'a types::VmsCreateVmXCmuxTeamId>,
        body: &'a types::CreateVmRequest,
    ) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
        let url = format!("{}/v1/vms", self.baseurl,);
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(3usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = idempotency_key {
            header_map.append("idempotency-key", value.to_string().try_into()?);
        }
        if let Some(value) = x_cmux_team_id {
            header_map.append("x-cmux-team-id", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "vms_create_vm",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            201u16 => Ok(ResponseValue::stream(response)),
            400u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            401u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            402u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            403u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            404u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            409u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            429u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            501u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            503u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Get a VM

    Get a VM. Requires the vm:read scope.

    Sends a `GET` request to `/v1/vms/{vmId}`

    Arguments:
    - `vm_id`
    - `x_cmux_team_id`: a string at most 128 character(s) long
    */
    pub async fn vms_get_vm<'a>(
        &'a self,
        vm_id: &'a str,
        x_cmux_team_id: Option<&'a types::VmsGetVmXCmuxTeamId>,
    ) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
        let url = format!(
            "{}/v1/vms/{}",
            self.baseurl,
            encode_path(&vm_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(2usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = x_cmux_team_id {
            header_map.append("x-cmux-team-id", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self.client.get(url).headers(header_map).build()?;
        let info = OperationInfo {
            operation_id: "vms_get_vm",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => Ok(ResponseValue::stream(response)),
            400u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            401u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            403u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            404u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            503u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Delete a VM permanently

    Delete a VM permanently. Requires the vm:write scope.

    Sends a `DELETE` request to `/v1/vms/{vmId}`

    Arguments:
    - `vm_id`
    - `x_cmux_team_id`: a string at most 128 character(s) long
    */
    pub async fn vms_delete_vm<'a>(
        &'a self,
        vm_id: &'a str,
        x_cmux_team_id: Option<&'a types::VmsDeleteVmXCmuxTeamId>,
    ) -> Result<ResponseValue<()>, Error<ByteStream>> {
        let url = format!(
            "{}/v1/vms/{}",
            self.baseurl,
            encode_path(&vm_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(2usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = x_cmux_team_id {
            header_map.append("x-cmux-team-id", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self.client.delete(url).headers(header_map).build()?;
        let info = OperationInfo {
            operation_id: "vms_delete_vm",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            204u16 => Ok(ResponseValue::empty(response)),
            400u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            401u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            403u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            404u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            409u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            501u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            503u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Fork a VM into a new VM with the same memory and disk

    Fork a VM into a new VM with the same memory and disk. Requires the vm:write scope.

    Sends a `POST` request to `/v1/vms/{vmId}/fork`

    Arguments:
    - `vm_id`
    - `idempotency_key`: a string at most 255 character(s) long
    - `x_cmux_team_id`: a string at most 128 character(s) long
    - `body`
    */
    pub async fn vms_fork_vm<'a>(
        &'a self,
        vm_id: &'a str,
        idempotency_key: Option<&'a types::VmsForkVmIdempotencyKey>,
        x_cmux_team_id: Option<&'a types::VmsForkVmXCmuxTeamId>,
        body: &'a types::ForkVmRequest,
    ) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
        let url = format!(
            "{}/v1/vms/{}/fork",
            self.baseurl,
            encode_path(&vm_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(3usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = idempotency_key {
            header_map.append("idempotency-key", value.to_string().try_into()?);
        }
        if let Some(value) = x_cmux_team_id {
            header_map.append("x-cmux-team-id", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self
            .client
            .post(url)
            .json(&body)
            .headers(header_map)
            .build()?;
        let info = OperationInfo {
            operation_id: "vms_fork_vm",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            201u16 => Ok(ResponseValue::stream(response)),
            400u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            401u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            402u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            403u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            404u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            409u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            429u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            501u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            503u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Pause a running VM, keeping its memory

    Pause a running VM, keeping its memory. Requires the vm:write scope.

    Sends a `POST` request to `/v1/vms/{vmId}/pause`

    Arguments:
    - `vm_id`
    - `x_cmux_team_id`: a string at most 128 character(s) long
    */
    pub async fn vms_pause_vm<'a>(
        &'a self,
        vm_id: &'a str,
        x_cmux_team_id: Option<&'a types::VmsPauseVmXCmuxTeamId>,
    ) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
        let url = format!(
            "{}/v1/vms/{}/pause",
            self.baseurl,
            encode_path(&vm_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(2usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = x_cmux_team_id {
            header_map.append("x-cmux-team-id", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self.client.post(url).headers(header_map).build()?;
        let info = OperationInfo {
            operation_id: "vms_pause_vm",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => Ok(ResponseValue::stream(response)),
            400u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            401u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            403u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            404u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            409u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            501u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            503u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Resume a paused VM

    Resume a paused VM. Requires the vm:write scope.

    Sends a `POST` request to `/v1/vms/{vmId}/resume`

    Arguments:
    - `vm_id`
    - `x_cmux_team_id`: a string at most 128 character(s) long
    */
    pub async fn vms_resume_vm<'a>(
        &'a self,
        vm_id: &'a str,
        x_cmux_team_id: Option<&'a types::VmsResumeVmXCmuxTeamId>,
    ) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
        let url = format!(
            "{}/v1/vms/{}/resume",
            self.baseurl,
            encode_path(&vm_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(2usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = x_cmux_team_id {
            header_map.append("x-cmux-team-id", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self.client.post(url).headers(header_map).build()?;
        let info = OperationInfo {
            operation_id: "vms_resume_vm",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => Ok(ResponseValue::stream(response)),
            400u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            401u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            403u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            404u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            409u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            501u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            503u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Start a stopped VM

    Start a stopped VM. Requires the vm:write scope.

    Sends a `POST` request to `/v1/vms/{vmId}/start`

    Arguments:
    - `vm_id`
    - `x_cmux_team_id`: a string at most 128 character(s) long
    */
    pub async fn vms_start_vm<'a>(
        &'a self,
        vm_id: &'a str,
        x_cmux_team_id: Option<&'a types::VmsStartVmXCmuxTeamId>,
    ) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
        let url = format!(
            "{}/v1/vms/{}/start",
            self.baseurl,
            encode_path(&vm_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(2usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = x_cmux_team_id {
            header_map.append("x-cmux-team-id", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self.client.post(url).headers(header_map).build()?;
        let info = OperationInfo {
            operation_id: "vms_start_vm",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => Ok(ResponseValue::stream(response)),
            400u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            401u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            403u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            404u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            409u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            501u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            503u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
    /**Stop a running VM

    Stop a running VM. Requires the vm:write scope.

    Sends a `POST` request to `/v1/vms/{vmId}/stop`

    Arguments:
    - `vm_id`
    - `x_cmux_team_id`: a string at most 128 character(s) long
    */
    pub async fn vms_stop_vm<'a>(
        &'a self,
        vm_id: &'a str,
        x_cmux_team_id: Option<&'a types::VmsStopVmXCmuxTeamId>,
    ) -> Result<ResponseValue<ByteStream>, Error<ByteStream>> {
        let url = format!(
            "{}/v1/vms/{}/stop",
            self.baseurl,
            encode_path(&vm_id.to_string()),
        );
        let mut header_map = ::reqwest::header::HeaderMap::with_capacity(2usize);
        header_map.append(
            ::reqwest::header::HeaderName::from_static("api-version"),
            ::reqwest::header::HeaderValue::from_static(Self::api_version()),
        );
        if let Some(value) = x_cmux_team_id {
            header_map.append("x-cmux-team-id", value.to_string().try_into()?);
        }
        #[allow(unused_mut)]
        let mut request = self.client.post(url).headers(header_map).build()?;
        let info = OperationInfo {
            operation_id: "vms_stop_vm",
        };
        self.pre(&mut request, &info).await?;
        let result = self.exec(request, &info).await;
        self.post(&result, &info).await?;
        let response = result?;
        match response.status().as_u16() {
            200u16 => Ok(ResponseValue::stream(response)),
            400u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            401u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            403u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            404u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            409u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            501u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            503u16 => Err(Error::ErrorResponse(ResponseValue::stream(response))),
            _ => Err(Error::UnexpectedResponse(response)),
        }
    }
}
/// Items consumers will typically use such as the Client.
pub mod prelude {
    #[allow(unused_imports)]
    pub use super::Client;
}
