#!/usr/bin/env python3
"""Contract check: checked-in shell completions stay in sync with the CLI.

The completion scripts under `completions/` are generated by
`scripts/generate-cli-completions.py` from the `topLevelCommandNames` registry
and the `usage()` help text in `CLI/cmux.swift`. This test regenerates them
from that same source and fails if the committed files drift -- so adding a CLI
command without regenerating turns CI red instead of silently shipping stale
completions. It also guards that every user-visible command is actually
completed, and that each script is shell-syntax valid.

Run:  python3 tests/test_cli_completions_contract.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATOR = REPO_ROOT / "scripts" / "generate-cli-completions.py"
COMPLETIONS_DIR = REPO_ROOT / "completions"
SHELLS = {"bash": "cmux.bash", "zsh": "cmux.zsh", "fish": "cmux.fish"}
SYNTAX_CHECK = {"bash": ["bash", "-n"], "zsh": ["zsh", "-n"], "fish": ["fish", "-n"]}

REGEN_HINT = "Run: scripts/generate-cli-completions.py --write"


def regenerate(shell: str) -> str:
    proc = subprocess.run(  # noqa: S603
        [sys.executable, str(GENERATOR), "--shell", shell],
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"generator failed for {shell}: {proc.stderr.strip()}")
    return proc.stdout


def main() -> int:
    failures: list[str] = []

    if not GENERATOR.exists():
        print(f"FAIL: generator missing at {GENERATOR}")
        return 1

    regenerated: dict[str, str] = {}
    for shell, filename in SHELLS.items():
        committed_path = COMPLETIONS_DIR / filename
        if not committed_path.exists():
            failures.append(f"{filename}: not committed. {REGEN_HINT}")
            continue
        try:
            fresh = regenerate(shell)
        except (RuntimeError, OSError, subprocess.TimeoutExpired) as exc:
            failures.append(f"{shell}: regeneration error: {exc}")
            continue
        regenerated[shell] = fresh
        committed = committed_path.read_text(encoding="utf-8")
        if committed != fresh:
            failures.append(
                f"{filename} is out of date with CLI/cmux.swift. {REGEN_HINT}"
            )

    # Drift guard: every visible command must appear in the bash command list.
    expected: list[str] = []
    try:
        proc = subprocess.run(  # noqa: S603
            [sys.executable, str(GENERATOR), "--list-commands"],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        if proc.returncode != 0:
            raise RuntimeError(proc.stderr.strip())
        expected = [line for line in proc.stdout.splitlines() if line.strip()]
    except (RuntimeError, OSError, subprocess.TimeoutExpired) as exc:
        failures.append(f"could not list commands for coverage check: {exc}")

    # Registry-coverage drift guard: every command documented in the usage()
    # help must be in topLevelCommandNames, or completions silently miss it.
    try:
        proc = subprocess.run(  # noqa: S603
            [sys.executable, str(GENERATOR), "--check"],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        if proc.returncode != 0:
            failures.append(
                f"registry-coverage drift: {proc.stderr.strip() or proc.stdout.strip()}"
            )
    except (OSError, subprocess.TimeoutExpired) as exc:
        failures.append(f"could not run registry-coverage check: {exc}")

    bash_text = regenerated.get("bash", "")
    # Normalize quotes/newlines to spaces so first/last tokens against a `"`
    # boundary still match on whole-word check.
    haystack = " " + bash_text.replace('"', " ").replace("\n", " ") + " "
    missing = [c for c in expected if f" {c} " not in haystack]
    if expected and missing:
        failures.append(
            f"{len(missing)} visible command(s) absent from bash completions: "
            f"{', '.join(missing[:10])}{'...' if len(missing) > 10 else ''}"
        )

    # Best-effort: the committed scripts must be shell-syntax valid.
    for shell, filename in SHELLS.items():
        binary = SYNTAX_CHECK[shell][0]
        if shutil.which(binary) is None:
            continue
        path = COMPLETIONS_DIR / filename
        if not path.exists():
            continue
        proc = subprocess.run(  # noqa: S603
            [*SYNTAX_CHECK[shell], str(path)],
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
        if proc.returncode != 0:
            failures.append(f"{filename}: {shell} syntax error: {proc.stderr.strip()}")

    if failures:
        print("FAIL: CLI completions contract")
        for failure in failures:
            print("")
            print(failure)
        return 1

    print(
        f"PASS: {len(SHELLS)} completion scripts in sync, "
        f"{len(expected)} commands covered"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
