import CmuxSettingsUI

typealias SettingsNavigationTarget = CmuxSettingsUI.SettingsNavigationTarget
typealias SettingsNavigationRequest = CmuxSettingsUI.SettingsNavigationRequest
typealias SettingsNavigationDestination = CmuxSettingsUI.SettingsNavigationDestination
typealias SettingsSearchHighlightState = CmuxSettingsUI.SettingsSearchHighlightState
typealias SettingsSearchEntryKind = CmuxSettingsUI.SettingsSearchEntryKind
typealias SettingsSearchEntry = CmuxSettingsUI.SettingsSearchEntry
typealias SettingsSearchIndex = CmuxSettingsUI.SettingsSearchIndex
typealias CmuxSettingsRootView = CmuxSettingsUI.CmuxSettingsRootView
