import CmuxSettingsUI

typealias SettingsScrollCoordinateSpace = CmuxSettingsUI.SettingsScrollCoordinateSpace
typealias SettingsLazyLoadTrigger = CmuxSettingsUI.SettingsLazyLoadTrigger
typealias SettingsLazyLoadFramePreferenceKey = CmuxSettingsUI.SettingsLazyLoadFramePreferenceKey
typealias SettingsLazyLoadMarker = CmuxSettingsUI.SettingsLazyLoadMarker
