/// Compact XPC dictionary keys shared by cmux and renderer workers.
///
/// Short keys reduce allocation and hashing cost for keyboard, mouse, resize,
/// and frame messages. The values are stable protocol ABI.
public enum RendererIPCKey {
    public static let operation = "o"
    public static let protocolVersion = "v"
    public static let workspaceID = "w"
    public static let surfaceID = "s"
    public static let requestID = "r"
    public static let generation = "g"
    public static let sequence = "q"
    public static let width = "x"
    public static let height = "y"
    public static let scaleX = "X"
    public static let scaleY = "Y"
    public static let columns = "c"
    public static let rows = "R"
    public static let value = "a"
    public static let secondaryValue = "b"
    public static let flags = "f"
    public static let data = "d"
    public static let text = "t"
    public static let token = "k"
    public static let endpoint = "e"
    public static let ioSurface = "i"
    public static let eventValue = "E"
    public static let error = "z"
    public static let action = "A"
    public static let modifiers = "m"
    public static let consumedModifiers = "M"
    public static let keycode = "K"
    public static let composing = "C"
    public static let unshiftedCodepoint = "u"
    public static let positionX = "p"
    public static let positionY = "P"
    public static let button = "B"
    public static let pressure = "D"
    public static let momentumPhase = "h"
    public static let scrollPhase = "H"
    public static let precision = "j"
    public static let configuration = "n"

}
