# Generated by cmux-tui/bindings/codegen. DO NOT EDIT.
# Source: cmux-tui/spec/sdk-schema.json

from __future__ import annotations

import base64
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, ClassVar, Dict, List, Literal, Mapping, Optional, Union


class MissingType:
    __slots__ = ()

    def __repr__(self) -> str:
        return "MISSING"

    def __bool__(self) -> bool:
        return False


MISSING = MissingType()


class EventBase:
    @property
    def bytes_data(self) -> Optional[bytes]:
        for name in ("data", "replay", "png"):
            value = getattr(self, name, MISSING)
            if value is not MISSING and value is not None:
                return base64.b64decode(value, validate=True)
        return None


@dataclass(frozen=True)
class UnknownEvent(EventBase):
    event: str
    raw: Mapping[str, Any]

class AgentReportSource(str, Enum):
    SOCKET = 'socket'
    HOOK = 'hook'

class AgentSource(str, Enum):
    DETECTED = 'detected'
    SOCKET = 'socket'
    HOOK = 'hook'

class AgentState(str, Enum):
    WORKING = 'working'
    BLOCKED = 'blocked'
    IDLE = 'idle'
    DONE = 'done'
    UNKNOWN = 'unknown'

class ClientTransport(str, Enum):
    LOCAL = 'local'
    UNIX = 'unix'
    WS = 'ws'

class CursorStyle(str, Enum):
    BLOCK = 'block'
    UNDERLINE = 'underline'
    BAR = 'bar'

class NotificationLevel(str, Enum):
    INFO = 'info'
    WARNING = 'warning'
    ERROR = 'error'

class PaneDirection(str, Enum):
    LEFT = 'left'
    RIGHT = 'right'
    UP = 'up'
    DOWN = 'down'

class RenderUnderline(str, Enum):
    SINGLE = 'single'
    DOUBLE = 'double'
    CURLY = 'curly'
    DOTTED = 'dotted'
    DASHED = 'dashed'

class SplitDirection(str, Enum):
    RIGHT = 'right'
    DOWN = 'down'

class TerminalLifecycle(str, Enum):
    LAUNCHING = 'launching'
    ADOPTING = 'adopting'
    RUNNING = 'running'
    EXITED = 'exited'
    TOMBSTONED = 'tombstoned'


@dataclass(frozen=True)
class AgentRecord:
    __cmux_schema_path__: ClassVar[str] = 'types/AgentRecord'
    surface: Id
    session: Union[str, None]
    source: AgentSource
    state: AgentState
    updated_at_ms: int


@dataclass(frozen=True)
class AppliedPane:
    __cmux_schema_path__: ClassVar[str] = 'types/AppliedPane'
    surface: Id
    pane: Id


@dataclass(frozen=True)
class ApplyLayoutResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ApplyLayoutResult'
    screen: Id
    panes: List[AppliedPane]


@dataclass(frozen=True)
class BrowserFrame:
    __cmux_schema_path__: ClassVar[str] = 'types/BrowserFrame'
    data: Base64
    height: int
    seq: int
    width: int


@dataclass(frozen=True)
class CellPixelFailure:
    __cmux_schema_path__: ClassVar[str] = 'types/CellPixelFailure'
    surface: Id
    error: str


@dataclass(frozen=True)
class CellPixelResize:
    __cmux_schema_path__: ClassVar[str] = 'types/CellPixelResize'
    surface: Id
    cols: int
    reservation_id: int
    rows: int


@dataclass(frozen=True)
class ClientInfo:
    __cmux_schema_path__: ClassVar[str] = 'types/ClientInfo'
    client: int
    attached: List[Id]
    connected_seconds: int
    kind: Union[str, None]
    name: Union[str, None]
    is_self: bool = field(metadata={'wire_name': 'self'})
    sizes: List[ClientSize]
    transport: ClientTransport


@dataclass(frozen=True)
class ClientSize:
    __cmux_schema_path__: ClassVar[str] = 'types/ClientSize'
    surface: Id
    cols: Union[int, None]
    rows: Union[int, None]
    size_participating: bool


@dataclass(frozen=True)
class CloseTerminalResult:
    __cmux_schema_path__: ClassVar[str] = 'types/CloseTerminalResult'
    surface: Union[Id, None]
    terminal_id: str
    already_closed: bool
    closed: Literal[True]
    generation: str
    registry_id: str
    terminal_incarnation: Union[str, None]
    terminal_revision: int


@dataclass(frozen=True)
class CopyResult:
    __cmux_schema_path__: ClassVar[str] = 'types/CopyResult'
    mode: Literal['screen', 'selection', 'scrollback']
    text: str


@dataclass(frozen=True)
class DeadPane:
    __cmux_schema_path__: ClassVar[str] = 'types/DeadPane'
    dead: Literal[True]
    id: Id


@dataclass(frozen=True)
class DeclarativeLayoutLeaf:
    __cmux_schema_path__: ClassVar[str] = 'types/DeclarativeLayout/variants/leaf'
    type: Literal['leaf']
    command: Union[List[str], None, MissingType] = field(default=MISSING)
    cwd: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class DeclarativeLayoutSplit:
    __cmux_schema_path__: ClassVar[str] = 'types/DeclarativeLayout/variants/split'
    a: DeclarativeLayout
    b: DeclarativeLayout
    dir: SplitDirection
    ratio: float
    type: Literal['split']


@dataclass(frozen=True)
class DeclarativeLayoutStack:
    __cmux_schema_path__: ClassVar[str] = 'types/DeclarativeLayout/variants/stack'
    expanded: Id
    panes: List[Id]
    type: Literal['stack']


@dataclass(frozen=True)
class EmptyResult:
    __cmux_schema_path__: ClassVar[str] = 'types/EmptyResult'
    pass


@dataclass(frozen=True)
class ExportLayoutResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ExportLayoutResult'
    layout: Layout
    panes: List[ExportedPane]


@dataclass(frozen=True)
class ExportedPane:
    __cmux_schema_path__: ClassVar[str] = 'types/ExportedPane'
    pane: Id
    surfaces: List[Id]


@dataclass(frozen=True)
class FocusDirectionResult:
    __cmux_schema_path__: ClassVar[str] = 'types/FocusDirectionResult'
    pane: Id


@dataclass(frozen=True)
class FrontendProjection:
    __cmux_schema_path__: ClassVar[str] = 'types/FrontendProjection'
    frontend: str
    projection: Union[JsonValue, None]
    projection_revision: int
    schema_version: int
    scope: str
    subject_key: str
    replayed: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class IdMapping:
    __cmux_schema_path__: ClassVar[str] = 'types/IdMapping'
    id: Id
    kind: Literal['workspace', 'screen', 'pane', 'surface']
    short_id: str


@dataclass(frozen=True)
class IdentifyResult:
    __cmux_schema_path__: ClassVar[str] = 'types/IdentifyResult'
    app: Literal['cmux-tui']
    daemon_handoff: Literal[1]
    generation: str
    pid: int
    protocol: int
    registry_id: str
    session: str
    terminal_revision: int
    version: str
    workspace_revision: int
    build_commit: Union[str, None, MissingType] = field(default=MISSING)
    capabilities: Union[List[str], MissingType] = field(default=MISSING)
    ghostty_commit: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class IdsResult:
    __cmux_schema_path__: ClassVar[str] = 'types/IdsResult'
    ids: List[IdMapping]


@dataclass(frozen=True)
class LayoutLeaf:
    __cmux_schema_path__: ClassVar[str] = 'types/Layout/variants/leaf'
    pane: Id
    type: Literal['leaf']


@dataclass(frozen=True)
class LayoutSplit:
    __cmux_schema_path__: ClassVar[str] = 'types/Layout/variants/split'
    a: Layout
    b: Layout
    dir: SplitDirection
    ratio: float
    type: Literal['split']
    split: Union[Id, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class LayoutStack:
    __cmux_schema_path__: ClassVar[str] = 'types/Layout/variants/stack'
    expanded: Id
    panes: List[Id]
    type: Literal['stack']


@dataclass(frozen=True)
class ListAgentsResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ListAgentsResult'
    agents: List[AgentRecord]


@dataclass(frozen=True)
class ListTerminalsResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ListTerminalsResult'
    generation: str
    registry_id: str
    terminal_revision: int
    terminals: List[TerminalRecord]


@dataclass(frozen=True)
class LivePane:
    __cmux_schema_path__: ClassVar[str] = 'types/LivePane'
    active_tab: int
    id: Id
    name: Union[str, None]
    tabs: List[Tab]
    focused_at: Union[int, MissingType] = field(default=MISSING)
    short_id: Union[str, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class MintTerminalRendererResult:
    __cmux_schema_path__: ClassVar[str] = 'types/MintTerminalRendererResult'
    terminal_id: str
    endpoint: str
    incarnation: str
    rights: int
    token: str
    ttl_ms: int


@dataclass(frozen=True)
class MoveTerminalResult:
    __cmux_schema_path__: ClassVar[str] = 'types/MoveTerminalResult'
    surface: Union[Id, None]
    pane: Union[Id, None]
    screen: Union[Id, None]
    workspace: Union[Id, None]
    terminal_id: str
    changed: bool
    generation: str
    lifecycle: TerminalLifecycle
    registry_id: str
    replayed: bool
    terminal_incarnation: Union[str, None]
    terminal_revision: int
    workspace_key: str


@dataclass(frozen=True)
class NotificationMarker:
    __cmux_schema_path__: ClassVar[str] = 'types/NotificationMarker'
    level: NotificationLevel
    notification: Id
    unread: bool


@dataclass(frozen=True)
class NotifyResult:
    __cmux_schema_path__: ClassVar[str] = 'types/NotifyResult'
    notification: Id


@dataclass(frozen=True)
class PaneNeighborResult:
    __cmux_schema_path__: ClassVar[str] = 'types/PaneNeighborResult'
    pane: Union[Id, None]


@dataclass(frozen=True)
class PingResult:
    __cmux_schema_path__: ClassVar[str] = 'types/PingResult'
    ok: Literal[True]
    protocol: int
    version: str
    build_commit: Union[str, None, MissingType] = field(default=MISSING)
    ghostty_commit: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ProcessInfoResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ProcessInfoResult'
    command: Union[str, None]
    cwd: Union[str, None]
    pid: Union[int, None]


@dataclass(frozen=True)
class ProviderWorkspaceMutationResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ProviderWorkspaceMutationResult'
    workspace: Id
    key: str
    workspace_revision: int


@dataclass(frozen=True)
class ReadScreenResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ReadScreenResult'
    text: str


@dataclass(frozen=True)
class ReadScrollbackResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ReadScrollbackResult'
    rows: List[RenderRow]
    start: int
    total: int


@dataclass(frozen=True)
class RenderCursor:
    __cmux_schema_path__: ClassVar[str] = 'types/RenderCursor'
    blink: bool
    color: Union[ColorHex, None]
    style: CursorStyle
    visible: bool
    x: int
    y: int


@dataclass(frozen=True)
class RenderRow:
    __cmux_schema_path__: ClassVar[str] = 'types/RenderRow'
    row: int
    runs: List[RenderRun]


@dataclass(frozen=True)
class RenderRun:
    __cmux_schema_path__: ClassVar[str] = 'types/RenderRun'
    attrs: int
    bg: Union[ColorHex, None]
    fg: Union[ColorHex, None]
    text: str
    underline: Union[RenderUnderline, MissingType] = field(default=MISSING)
    width_hint: Union[int, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ReportAgentResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ReportAgentResult'
    surface: Id
    session: Union[str, None]
    source: AgentReportSource
    state: AgentState


@dataclass(frozen=True)
class ResizeSurfaceResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ResizeSurfaceResult'
    accepted: bool
    reservation_id: Union[int, None]


@dataclass(frozen=True)
class ResolveTerminalResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ResolveTerminalResult'
    surface: Union[Id, None]
    terminal_id: str
    exit: Union[JsonValue, None]
    generation: str
    launch_spec: JsonValue
    lifecycle: TerminalLifecycle
    registry_id: str
    terminal_incarnation: Union[str, None]
    terminal_revision: int
    workspace_key: str


@dataclass(frozen=True)
class RunResult:
    __cmux_schema_path__: ClassVar[str] = 'types/RunResult'
    surface: Id
    pane: Id
    screen: Id
    workspace: Id
    terminal_id: Union[str, None]
    terminal_incarnation: Union[str, None]


@dataclass(frozen=True)
class Screen:
    __cmux_schema_path__: ClassVar[str] = 'types/Screen'
    active: bool
    active_pane: Id
    id: Id
    layout: Layout
    name: Union[str, None]
    panes: List[Pane]
    zoomed_pane: Union[Id, None]
    short_id: Union[str, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SetCellPixelsResult:
    __cmux_schema_path__: ClassVar[str] = 'types/SetCellPixelsResult'
    failures: List[CellPixelFailure]
    resizes: List[CellPixelResize]


@dataclass(frozen=True)
class ShutdownDaemonResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ShutdownDaemonResult'
    accepted: Literal[True]
    generation: str
    pid: int


@dataclass(frozen=True)
class SidebarPluginResult:
    __cmux_schema_path__: ClassVar[str] = 'types/SidebarPluginResult'
    surface: Union[Id, None]
    error: Union[str, None]
    retry_after_ms: Union[int, None]


@dataclass(frozen=True)
class Size:
    __cmux_schema_path__: ClassVar[str] = 'types/Size'
    cols: int
    rows: int


@dataclass(frozen=True)
class SurfaceResult:
    __cmux_schema_path__: ClassVar[str] = 'types/SurfaceResult'
    surface: Id
    terminal_id: Union[str, None, MissingType] = field(default=MISSING)
    terminal_incarnation: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class Tab:
    __cmux_schema_path__: ClassVar[str] = 'types/Tab'
    surface: Id
    browser_source: Union[Literal['external', 'launched'], None]
    dead: bool
    kind: Literal['pty', 'browser']
    name: Union[str, None]
    size: Union[Size, None]
    title: str
    terminal_id: Union[str, None, MissingType] = field(default=MISSING)
    browser_error: Union[str, None, MissingType] = field(default=MISSING)
    browser_frames_stalled: Union[bool, None, MissingType] = field(default=MISSING)
    browser_status: Union[Literal['starting', 'live', 'failed'], None, MissingType] = field(default=MISSING)
    notification: Union[NotificationMarker, None, MissingType] = field(default=MISSING)
    short_id: Union[str, MissingType] = field(default=MISSING)
    terminal_incarnation: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class TerminalColors:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalColors'
    bg: Union[ColorHex, None]
    fg: Union[ColorHex, None]
    selection_bg: Union[ColorHex, None]
    selection_fg: Union[ColorHex, None]
    cursor: Union[ColorHex, None, MissingType] = field(default=MISSING)
    cursor_blink: Union[bool, None, MissingType] = field(default=MISSING)
    cursor_style: Union[CursorStyle, None, MissingType] = field(default=MISSING)
    palette: Union[Dict[str, ColorHex], MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class TerminalEventsResult:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalEventsResult'
    events: List[TerminalRegistryEvent]
    generation: str
    registry_id: str
    terminal_revision: int


@dataclass(frozen=True)
class TerminalPlacement:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalPlacement'
    surface: Id
    pane: Id
    screen: Id
    workspace: Id
    terminal_id: Union[str, None]
    generation: str
    key: str
    lifecycle: Union[Literal['running'], None]
    registry_id: str
    replayed: bool
    terminal_incarnation: Union[str, None]
    terminal_revision: int


@dataclass(frozen=True)
class TerminalRecord:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalRecord'
    terminal_id: str
    exit: Union[JsonValue, None]
    launch_spec: JsonValue
    lifecycle: TerminalLifecycle
    terminal_incarnation: Union[str, None]
    workspace_key: str


@dataclass(frozen=True)
class TerminalRegistryEvent:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalRegistryEvent'
    terminal_id: str
    kind: str
    mutation_id: str
    origin: str
    result: JsonValue
    terminal_revision: int
    workspace_key: str


@dataclass(frozen=True)
class Tree:
    __cmux_schema_path__: ClassVar[str] = 'types/Tree'
    workspaces: List[Workspace]
    generation: Union[str, MissingType] = field(default=MISSING)
    pane_revision: Union[int, MissingType] = field(default=MISSING)
    registry_id: Union[str, MissingType] = field(default=MISSING)
    terminal_revision: Union[int, MissingType] = field(default=MISSING)
    workspace_revision: Union[int, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class VtStateResult:
    __cmux_schema_path__: ClassVar[str] = 'types/VtStateResult'
    cols: int
    data: Base64
    rows: int


@dataclass(frozen=True)
class WaitForResult:
    __cmux_schema_path__: ClassVar[str] = 'types/WaitForResult'
    elapsed_ms: int
    matched: Literal[True]
    text: str


@dataclass(frozen=True)
class Workspace:
    __cmux_schema_path__: ClassVar[str] = 'types/Workspace'
    active: bool
    id: Id
    name: str
    screens: List[Screen]
    key: Union[str, MissingType] = field(default=MISSING)
    short_id: Union[str, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class WorkspaceMutationResult:
    __cmux_schema_path__: ClassVar[str] = 'types/WorkspaceMutationResult'
    workspace: Id
    generation: str
    index: int
    key: str
    registry_id: str
    replayed: bool
    workspace_revision: int
    changed: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ZoomPaneResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ZoomPaneResult'
    pane: Id
    zoomed: bool
    zoomed_pane: Union[Id, None]


@dataclass(frozen=True)
class ApplyLayoutRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/apply-layout/request'
    layout: DeclarativeLayout
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    name: Union[str, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class AttachSurfaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/attach-surface/request'
    surface: Id
    cols: Union[int, None, MissingType] = field(default=MISSING)
    mode: Union[Literal['bytes', 'render'], None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class BrowserActivateRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-activate/request'
    surface: Id


@dataclass(frozen=True)
class BrowserBackRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-back/request'
    surface: Id


@dataclass(frozen=True)
class BrowserForwardRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-forward/request'
    surface: Id


@dataclass(frozen=True)
class BrowserInsertTextRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-insert-text/request'
    surface: Id
    text: str


@dataclass(frozen=True)
class BrowserKeyRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-key/request'
    surface: Id
    kind: Literal['down', 'up']
    key: str
    code: str
    windows_virtual_key_code: int
    modifiers: int
    text: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class BrowserMouseRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-mouse/request'
    surface: Id
    kind: Literal['down', 'up', 'move']
    x_px: float
    y_px: float
    button: Union[str, None, MissingType] = field(default=MISSING)
    click_count: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class BrowserNavigateRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-navigate/request'
    surface: Id
    url: str


@dataclass(frozen=True)
class BrowserReloadRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-reload/request'
    surface: Id


@dataclass(frozen=True)
class BrowserWheelRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-wheel/request'
    surface: Id
    x_px: float
    y_px: float
    delta_y_px: float


@dataclass(frozen=True)
class ClearWindowTitleRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/clear-window-title/request'
    pass


@dataclass(frozen=True)
class ClosePaneRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/close-pane/request'
    pane: Id


@dataclass(frozen=True)
class CloseProviderManagedWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/close-provider-managed-workspace/request'
    workspace: Id
    key: str
    authority: str


@dataclass(frozen=True)
class CloseScreenRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/close-screen/request'
    screen: Id


@dataclass(frozen=True)
class CloseSurfaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/close-surface/request'
    surface: Id


@dataclass(frozen=True)
class CloseTerminalRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/close-terminal/request'
    terminal_id: str
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    terminal_incarnation: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class CloseWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/close-workspace/request'
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    key: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class CopyRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/copy/request'
    surface: Id
    mode: Literal['screen', 'selection', 'scrollback']


@dataclass(frozen=True)
class CreateTerminalRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/create-terminal/request'
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    key: Union[str, None, MissingType] = field(default=MISSING)
    argv: Union[List[str], None, MissingType] = field(default=MISSING)
    command: Union[str, None, MissingType] = field(default=MISSING)
    cwd: Union[str, None, MissingType] = field(default=MISSING)
    name: Union[str, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)
    terminal_id: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class CreateWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/create-workspace/request'
    name: Union[str, None, MissingType] = field(default=MISSING)
    key: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class DetachClientRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/detach-client/request'
    client: int


@dataclass(frozen=True)
class ExportLayoutRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/export-layout/request'
    screen: Union[Id, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class FocusDirectionRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/focus-direction/request'
    dir: PaneDirection
    pane: Union[Id, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class FocusPaneRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/focus-pane/request'
    pane: Id


@dataclass(frozen=True)
class GetFrontendProjectionRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/get-frontend-projection/request'
    frontend: str
    scope: str
    subject_key: str


@dataclass(frozen=True)
class IdentifyRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/identify/request'
    pass


@dataclass(frozen=True)
class IdsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/ids/request'
    kind: Union[Literal['workspace', 'screen', 'pane', 'surface'], None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ListAgentsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/list-agents/request'
    surface: Union[Id, None, MissingType] = field(default=MISSING)
    state: Union[AgentState, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ListClientsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/list-clients/request'
    pass


@dataclass(frozen=True)
class ListTerminalsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/list-terminals/request'
    pass


@dataclass(frozen=True)
class ListWorkspacesRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/list-workspaces/request'
    pass


@dataclass(frozen=True)
class MarkWorkspacesProviderManagedRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/mark-workspaces-provider-managed/request'
    authority: str


@dataclass(frozen=True)
class MintTerminalRendererRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/mint-terminal-renderer/request'
    surface: Id
    ttl_ms: Union[int, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class MoveTabRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/move-tab/request'
    surface: Id
    pane: Id
    index: int


@dataclass(frozen=True)
class MoveTerminalRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/move-terminal/request'
    terminal_id: str
    workspace_key: str
    terminal_incarnation: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class MoveWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/move-workspace/request'
    index: int
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    key: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NewBrowserTabRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/new-browser-tab/request'
    url: str
    pane: Union[Id, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NewPaneRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/new-pane/request'
    pane: Id
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NewScreenRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/new-screen/request'
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NewTabRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/new-tab/request'
    pane: Union[Id, None, MissingType] = field(default=MISSING)
    cwd: Union[str, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NewWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/new-workspace/request'
    name: Union[str, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NotifyRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/notify/request'
    title: str
    body: str
    level: Union[NotificationLevel, None, MissingType] = field(default=MISSING)
    surface: Union[Id, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class PairingResponseRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/pairing-response/request'
    request: int
    approve: bool


@dataclass(frozen=True)
class PaneNeighborRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/pane-neighbor/request'
    pane: Id
    dir: PaneDirection


@dataclass(frozen=True)
class PingRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/ping/request'
    pass


@dataclass(frozen=True)
class ProcessInfoRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/process-info/request'
    surface: Id


@dataclass(frozen=True)
class PutFrontendProjectionRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/put-frontend-projection/request'
    frontend: str
    scope: str
    subject_key: str
    schema_version: int
    projection: Union[JsonValue, None]
    expected_projection_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ReadScreenRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/read-screen/request'
    surface: Id


@dataclass(frozen=True)
class ReadScrollbackRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/read-scrollback/request'
    surface: Id
    start: int
    count: int


@dataclass(frozen=True)
class ReleaseSurfaceSizeRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/release-surface-size/request'
    surface: Id


@dataclass(frozen=True)
class ReloadConfigRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/reload-config/request'
    pass


@dataclass(frozen=True)
class ReloadConfigResult:
    __cmux_schema_path__: ClassVar[str] = 'commands/reload-config/result'
    path: Union[str, None]
    reloaded: Literal[True]


@dataclass(frozen=True)
class RenamePaneRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/rename-pane/request'
    pane: Id
    name: str


@dataclass(frozen=True)
class RenameProviderManagedWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/rename-provider-managed-workspace/request'
    workspace: Id
    key: str
    name: str
    authority: str


@dataclass(frozen=True)
class RenameScreenRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/rename-screen/request'
    screen: Id
    name: str


@dataclass(frozen=True)
class RenameSurfaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/rename-surface/request'
    surface: Id
    name: str


@dataclass(frozen=True)
class RenameWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/rename-workspace/request'
    name: str
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    key: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ReportAgentRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/report-agent/request'
    surface: Id
    state: AgentState
    source: AgentReportSource
    session: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ResizeSurfaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/resize-surface/request'
    surface: Id
    cols: int
    rows: int


@dataclass(frozen=True)
class ResolveTerminalRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/resolve-terminal/request'
    terminal_id: str


@dataclass(frozen=True)
class RunRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/run/request'
    pane: Union[Id, None, MissingType] = field(default=MISSING)
    argv: Union[List[str], None, MissingType] = field(default=MISSING)
    command: Union[str, None, MissingType] = field(default=MISSING)
    cwd: Union[str, None, MissingType] = field(default=MISSING)
    new_workspace: Union[bool, MissingType] = field(default=MISSING)
    key: Union[str, None, MissingType] = field(default=MISSING)
    name: Union[str, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ScrollSurfaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/scroll-surface/request'
    surface: Id
    delta: int


@dataclass(frozen=True)
class SelectScreenRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/select-screen/request'
    index: Union[int, None, MissingType] = field(default=MISSING)
    delta: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SelectTabRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/select-tab/request'
    pane: Union[Id, None, MissingType] = field(default=MISSING)
    index: Union[int, None, MissingType] = field(default=MISSING)
    delta: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SelectWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/select-workspace/request'
    index: Union[int, None, MissingType] = field(default=MISSING)
    delta: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SendRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/send/request'
    surface: Id
    text: Union[str, None, MissingType] = field(default=MISSING)
    bytes_data: Union[Base64, None, MissingType] = field(default=MISSING, metadata={'wire_name': 'bytes'})
    paste: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SendKeyRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/send-key/request'
    surface: Id
    keys: List[str]


@dataclass(frozen=True)
class SetCellPixelsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-cell-pixels/request'
    width_px: int
    height_px: int


@dataclass(frozen=True)
class SetClientInfoRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-client-info/request'
    name: Union[str, None, MissingType] = field(default=MISSING)
    kind: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SetClientSizingRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-client-sizing/request'
    surface: Id
    enabled: bool
    client: Union[int, None, MissingType] = field(default=MISSING)
    exclusive: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SetDefaultColorsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-default-colors/request'
    fg: Union[ColorHex, None, MissingType] = field(default=MISSING)
    bg: Union[ColorHex, None, MissingType] = field(default=MISSING)
    cursor: Union[ColorHex, None, MissingType] = field(default=MISSING)
    selection_bg: Union[ColorHex, None, MissingType] = field(default=MISSING)
    selection_fg: Union[ColorHex, None, MissingType] = field(default=MISSING)
    cursor_style: Union[CursorStyle, None, MissingType] = field(default=MISSING)
    cursor_blink: Union[bool, None, MissingType] = field(default=MISSING)
    palette: Union[Dict[str, ColorHex], None, MissingType] = field(default=MISSING)
    complete: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SetRatioRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-ratio/request'
    pane: Id
    dir: SplitDirection
    ratio: float


@dataclass(frozen=True)
class SetSplitRatioRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-split-ratio/request'
    split: Id
    ratio: float


@dataclass(frozen=True)
class SetWindowTitleRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-window-title/request'
    title: str


@dataclass(frozen=True)
class ShutdownDaemonRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/shutdown-daemon/request'
    pid: int
    generation: str


@dataclass(frozen=True)
class SidebarPluginRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/sidebar-plugin/request'
    cols: int
    rows: int
    relaunch: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SplitRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/split/request'
    pane: Id
    dir: SplitDirection
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SubscribeRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/subscribe/request'
    surface: Union[Id, None, MissingType] = field(default=MISSING)
    tree_events: Union[Literal['coarse', 'deltas'], None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SwapPaneRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/swap-pane/request'
    pane: Id
    dir: Union[PaneDirection, None, MissingType] = field(default=MISSING)
    target: Union[Id, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class TerminalEventsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/terminal-events/request'
    after_revision: Union[int, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class VtStateRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/vt-state/request'
    surface: Id


@dataclass(frozen=True)
class WaitForRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/wait-for/request'
    surface: Id
    pattern: str
    timeout_ms: int


@dataclass(frozen=True)
class ZoomPaneRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/zoom-pane/request'
    pane: Union[Id, None, MissingType] = field(default=MISSING)
    mode: Union[Literal['toggle', 'on', 'off'], None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class BellEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/bell/payload'
    surface: Id
    event: Literal['bell']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class BrowserStateEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/browser-state/payload'
    surface: Id
    cols: int
    error: Union[str, None]
    event: Literal['browser-state']
    frames_stalled: bool
    rows: int
    status: Literal['starting', 'live', 'failed']
    title: str
    url: str
    frame: Union[BrowserFrame, None, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ClientAttachedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/client-attached/payload'
    client: int
    event: Literal['client-attached']
    kind: Union[str, None]
    name: Union[str, None]
    transport: Literal['unix', 'ws']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ClientChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/client-changed/payload'
    client: int
    event: Literal['client-changed']
    kind: Union[str, None]
    name: Union[str, None]
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ClientDetachedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/client-detached/payload'
    client: int
    event: Literal['client-detached']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ClientListInvalidatedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/client-list-invalidated/payload'
    event: Literal['client-list-invalidated']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ColorsChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/colors-changed/payload'
    bg: Union[ColorHex, None]
    event: Literal['colors-changed']
    fg: Union[ColorHex, None]
    selection_bg: Union[ColorHex, None]
    selection_fg: Union[ColorHex, None]
    surface: Union[Id, MissingType] = field(default=MISSING)
    cursor: Union[ColorHex, None, MissingType] = field(default=MISSING)
    cursor_blink: Union[bool, None, MissingType] = field(default=MISSING)
    cursor_style: Union[CursorStyle, None, MissingType] = field(default=MISSING)
    palette: Union[Dict[str, ColorHex], MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ConfigReloadRequestedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/config-reload-requested/payload'
    event: Literal['config-reload-requested']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class DetachedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/detached/payload'
    surface: Id
    event: Literal['detached']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class EmptyEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/empty/payload'
    event: Literal['empty']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class FrameEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/frame/payload'
    surface: Id
    data: Base64
    event: Literal['frame']
    height: int
    seq: int
    width: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class FrontendProjectionChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/frontend-projection-changed/payload'
    event: Literal['frontend-projection-changed']
    frontend: str
    mutation_id: str
    origin: str
    projection_revision: int
    scope: str
    subject_key: str
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class LayoutChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/layout-changed/payload'
    screen: Id
    event: Literal['layout-changed']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class NotificationEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/notification/payload'
    surface: Union[Id, None]
    body: str
    event: Literal['notification']
    level: NotificationLevel
    notification: Id
    title: str
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class OutputEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/output/payload'
    surface: Id
    data: Base64
    event: Literal['output']
    colors: Union[TerminalColors, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class OverflowEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/overflow/payload'
    error: str
    event: Literal['overflow']
    surface: Union[Id, MissingType] = field(default=MISSING)
    scope: Union[Literal['surface'], MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class PairingRequestedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/pairing-requested/payload'
    request: int
    code: str
    event: Literal['pairing-requested']
    expires_in: int
    peer: str
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class PairingResolvedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/pairing-resolved/payload'
    request: int
    event: Literal['pairing-resolved']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class PaneAddedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/pane-added/payload'
    pane: Id
    screen: Id
    workspace: Id
    entity: Pane
    event: Literal['pane-added']
    index: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class PaneClosedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/pane-closed/payload'
    pane: Id
    screen: Id
    workspace: Id
    entity: Pane
    event: Literal['pane-closed']
    index: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class RenderDeltaEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/render-delta/payload'
    surface: Id
    cursor: RenderCursor
    event: Literal['render-delta']
    full: bool
    rows: List[RenderRow]
    default_bg: Union[ColorHex, MissingType] = field(default=MISSING)
    default_fg: Union[ColorHex, MissingType] = field(default=MISSING)
    scrollback_rows: Union[int, MissingType] = field(default=MISSING)
    size: Union[Size, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class RenderStateEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/render-state/payload'
    surface: Id
    cursor: RenderCursor
    default_bg: ColorHex
    default_fg: ColorHex
    event: Literal['render-state']
    rows: List[RenderRow]
    scrollback_rows: int
    size: Size
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ResizedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/resized/payload'
    surface: Id
    cols: int
    event: Literal['resized']
    rows: int
    colors: Union[TerminalColors, MissingType] = field(default=MISSING)
    data: Union[Base64, MissingType] = field(default=MISSING)
    replay: Union[Base64, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ScreenAddedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/screen-added/payload'
    screen: Id
    workspace: Id
    entity: Screen
    event: Literal['screen-added']
    index: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ScreenClosedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/screen-closed/payload'
    screen: Id
    workspace: Id
    entity: Screen
    event: Literal['screen-closed']
    index: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ScreenRenamedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/screen-renamed/payload'
    screen: Id
    workspace: Id
    entity: Screen
    event: Literal['screen-renamed']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ScrollChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/scroll-changed/payload'
    surface: Id
    at_bottom: bool
    event: Literal['scroll-changed']
    offset: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class StatusEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/status/payload'
    event: Literal['status']
    message: str
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class SurfaceExitedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/surface-exited/payload'
    surface: Id
    event: Literal['surface-exited']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class SurfaceOutputEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/surface-output/payload'
    surface: Id
    event: Literal['surface-output']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class SurfaceResizeFailedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/surface-resize-failed/payload'
    surface: Id
    cols: int
    error: str
    event: Literal['surface-resize-failed']
    reservation_id: Union[int, None]
    retry_after_ms: Union[int, None]
    rows: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class SurfaceResizedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/surface-resized/payload'
    surface: Id
    cols: int
    event: Literal['surface-resized']
    reservation_id: Union[int, None]
    rows: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class TabAddedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/tab-added/payload'
    surface: Id
    pane: Id
    screen: Id
    workspace: Id
    entity: Tab
    event: Literal['tab-added']
    index: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class TabClosedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/tab-closed/payload'
    surface: Id
    pane: Id
    screen: Id
    workspace: Id
    entity: Tab
    event: Literal['tab-closed']
    index: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class TabRenamedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/tab-renamed/payload'
    surface: Id
    pane: Id
    screen: Id
    workspace: Id
    entity: Tab
    event: Literal['tab-renamed']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class TerminalRegistryChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/terminal-registry-changed/payload'
    event: Literal['terminal-registry-changed']
    generation: str
    refetch: Literal['terminal-events-or-list-terminals']
    registry_id: str
    terminal_revision: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class TitleChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/title-changed/payload'
    surface: Id
    event: Literal['title-changed']
    title: Union[str, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class TreeChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/tree-changed/payload'
    event: Literal['tree-changed']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class VtStateEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/vt-state/payload'
    surface: Id
    cols: int
    data: Base64
    event: Literal['vt-state']
    rows: int
    colors: Union[TerminalColors, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class WindowTitleRequestedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/window-title-requested/payload'
    event: Literal['window-title-requested']
    title: str
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class WorkspaceAddedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/workspace-added/payload'
    workspace: Id
    entity: Workspace
    event: Literal['workspace-added']
    generation: str
    index: int
    registry_id: str
    workspace_revision: int
    mutation_id: Union[str, MissingType] = field(default=MISSING)
    origin: Union[str, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class WorkspaceClosedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/workspace-closed/payload'
    workspace: Id
    entity: Workspace
    event: Literal['workspace-closed']
    generation: str
    index: int
    registry_id: str
    workspace_revision: int
    mutation_id: Union[str, MissingType] = field(default=MISSING)
    origin: Union[str, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class WorkspaceMovedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/workspace-moved/payload'
    workspace: Id
    entity: Workspace
    event: Literal['workspace-moved']
    generation: str
    index: int
    registry_id: str
    workspace_revision: int
    mutation_id: Union[str, MissingType] = field(default=MISSING)
    origin: Union[str, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class WorkspaceRenamedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/workspace-renamed/payload'
    workspace: Id
    entity: Workspace
    event: Literal['workspace-renamed']
    generation: str
    registry_id: str
    workspace_revision: int
    mutation_id: Union[str, MissingType] = field(default=MISSING)
    origin: Union[str, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


# Named protocol aliases.
Base64 = str
ColorHex = str
DeclarativeLayout = Union[DeclarativeLayoutLeaf, DeclarativeLayoutSplit, DeclarativeLayoutStack]
Id = int
JsonValue = Any
Layout = Union[LayoutLeaf, LayoutSplit, LayoutStack]
Pane = Union[LivePane, DeadPane]

KnownEvent = Union[BellEvent, BrowserStateEvent, ClientAttachedEvent, ClientChangedEvent, ClientDetachedEvent, ClientListInvalidatedEvent, ColorsChangedEvent, ConfigReloadRequestedEvent, DetachedEvent, EmptyEvent, FrameEvent, FrontendProjectionChangedEvent, LayoutChangedEvent, NotificationEvent, OutputEvent, OverflowEvent, PairingRequestedEvent, PairingResolvedEvent, PaneAddedEvent, PaneClosedEvent, RenderDeltaEvent, RenderStateEvent, ResizedEvent, ScreenAddedEvent, ScreenClosedEvent, ScreenRenamedEvent, ScrollChangedEvent, StatusEvent, SurfaceExitedEvent, SurfaceOutputEvent, SurfaceResizeFailedEvent, SurfaceResizedEvent, TabAddedEvent, TabClosedEvent, TabRenamedEvent, TerminalRegistryChangedEvent, TitleChangedEvent, TreeChangedEvent, VtStateEvent, WindowTitleRequestedEvent, WorkspaceAddedEvent, WorkspaceClosedEvent, WorkspaceMovedEvent, WorkspaceRenamedEvent]
AnyEvent = Union[KnownEvent, UnknownEvent]

__all__ = [
    'MISSING',
    'MissingType',
    'EventBase',
    'UnknownEvent',
    'KnownEvent',
    'AnyEvent',
    'AgentReportSource',
    'AgentSource',
    'AgentState',
    'ClientTransport',
    'CursorStyle',
    'NotificationLevel',
    'PaneDirection',
    'RenderUnderline',
    'SplitDirection',
    'TerminalLifecycle',
    'AgentRecord',
    'AppliedPane',
    'ApplyLayoutResult',
    'BrowserFrame',
    'CellPixelFailure',
    'CellPixelResize',
    'ClientInfo',
    'ClientSize',
    'CloseTerminalResult',
    'CopyResult',
    'DeadPane',
    'DeclarativeLayoutLeaf',
    'DeclarativeLayoutSplit',
    'DeclarativeLayoutStack',
    'EmptyResult',
    'ExportLayoutResult',
    'ExportedPane',
    'FocusDirectionResult',
    'FrontendProjection',
    'IdMapping',
    'IdentifyResult',
    'IdsResult',
    'LayoutLeaf',
    'LayoutSplit',
    'LayoutStack',
    'ListAgentsResult',
    'ListTerminalsResult',
    'LivePane',
    'MintTerminalRendererResult',
    'MoveTerminalResult',
    'NotificationMarker',
    'NotifyResult',
    'PaneNeighborResult',
    'PingResult',
    'ProcessInfoResult',
    'ProviderWorkspaceMutationResult',
    'ReadScreenResult',
    'ReadScrollbackResult',
    'RenderCursor',
    'RenderRow',
    'RenderRun',
    'ReportAgentResult',
    'ResizeSurfaceResult',
    'ResolveTerminalResult',
    'RunResult',
    'Screen',
    'SetCellPixelsResult',
    'ShutdownDaemonResult',
    'SidebarPluginResult',
    'Size',
    'SurfaceResult',
    'Tab',
    'TerminalColors',
    'TerminalEventsResult',
    'TerminalPlacement',
    'TerminalRecord',
    'TerminalRegistryEvent',
    'Tree',
    'VtStateResult',
    'WaitForResult',
    'Workspace',
    'WorkspaceMutationResult',
    'ZoomPaneResult',
    'ApplyLayoutRequest',
    'AttachSurfaceRequest',
    'BrowserActivateRequest',
    'BrowserBackRequest',
    'BrowserForwardRequest',
    'BrowserInsertTextRequest',
    'BrowserKeyRequest',
    'BrowserMouseRequest',
    'BrowserNavigateRequest',
    'BrowserReloadRequest',
    'BrowserWheelRequest',
    'ClearWindowTitleRequest',
    'ClosePaneRequest',
    'CloseProviderManagedWorkspaceRequest',
    'CloseScreenRequest',
    'CloseSurfaceRequest',
    'CloseTerminalRequest',
    'CloseWorkspaceRequest',
    'CopyRequest',
    'CreateTerminalRequest',
    'CreateWorkspaceRequest',
    'DetachClientRequest',
    'ExportLayoutRequest',
    'FocusDirectionRequest',
    'FocusPaneRequest',
    'GetFrontendProjectionRequest',
    'IdentifyRequest',
    'IdsRequest',
    'ListAgentsRequest',
    'ListClientsRequest',
    'ListTerminalsRequest',
    'ListWorkspacesRequest',
    'MarkWorkspacesProviderManagedRequest',
    'MintTerminalRendererRequest',
    'MoveTabRequest',
    'MoveTerminalRequest',
    'MoveWorkspaceRequest',
    'NewBrowserTabRequest',
    'NewPaneRequest',
    'NewScreenRequest',
    'NewTabRequest',
    'NewWorkspaceRequest',
    'NotifyRequest',
    'PairingResponseRequest',
    'PaneNeighborRequest',
    'PingRequest',
    'ProcessInfoRequest',
    'PutFrontendProjectionRequest',
    'ReadScreenRequest',
    'ReadScrollbackRequest',
    'ReleaseSurfaceSizeRequest',
    'ReloadConfigRequest',
    'ReloadConfigResult',
    'RenamePaneRequest',
    'RenameProviderManagedWorkspaceRequest',
    'RenameScreenRequest',
    'RenameSurfaceRequest',
    'RenameWorkspaceRequest',
    'ReportAgentRequest',
    'ResizeSurfaceRequest',
    'ResolveTerminalRequest',
    'RunRequest',
    'ScrollSurfaceRequest',
    'SelectScreenRequest',
    'SelectTabRequest',
    'SelectWorkspaceRequest',
    'SendRequest',
    'SendKeyRequest',
    'SetCellPixelsRequest',
    'SetClientInfoRequest',
    'SetClientSizingRequest',
    'SetDefaultColorsRequest',
    'SetRatioRequest',
    'SetSplitRatioRequest',
    'SetWindowTitleRequest',
    'ShutdownDaemonRequest',
    'SidebarPluginRequest',
    'SplitRequest',
    'SubscribeRequest',
    'SwapPaneRequest',
    'TerminalEventsRequest',
    'VtStateRequest',
    'WaitForRequest',
    'ZoomPaneRequest',
    'BellEvent',
    'BrowserStateEvent',
    'ClientAttachedEvent',
    'ClientChangedEvent',
    'ClientDetachedEvent',
    'ClientListInvalidatedEvent',
    'ColorsChangedEvent',
    'ConfigReloadRequestedEvent',
    'DetachedEvent',
    'EmptyEvent',
    'FrameEvent',
    'FrontendProjectionChangedEvent',
    'LayoutChangedEvent',
    'NotificationEvent',
    'OutputEvent',
    'OverflowEvent',
    'PairingRequestedEvent',
    'PairingResolvedEvent',
    'PaneAddedEvent',
    'PaneClosedEvent',
    'RenderDeltaEvent',
    'RenderStateEvent',
    'ResizedEvent',
    'ScreenAddedEvent',
    'ScreenClosedEvent',
    'ScreenRenamedEvent',
    'ScrollChangedEvent',
    'StatusEvent',
    'SurfaceExitedEvent',
    'SurfaceOutputEvent',
    'SurfaceResizeFailedEvent',
    'SurfaceResizedEvent',
    'TabAddedEvent',
    'TabClosedEvent',
    'TabRenamedEvent',
    'TerminalRegistryChangedEvent',
    'TitleChangedEvent',
    'TreeChangedEvent',
    'VtStateEvent',
    'WindowTitleRequestedEvent',
    'WorkspaceAddedEvent',
    'WorkspaceClosedEvent',
    'WorkspaceMovedEvent',
    'WorkspaceRenamedEvent',
    'Base64',
    'ColorHex',
    'DeclarativeLayout',
    'Id',
    'JsonValue',
    'Layout',
    'Pane',
]
