// Generated by Scripts/generate_terminal_macos_key_map.py.
// Do not edit. Regenerate after changing Ghostty's canonical input tables.
// The Chromium-derived key table retains its BSD-style license in ghostty/LICENSE.
// key.zig SHA-256: 4b31521358a316a5c71a0c221feda19978531ade1e305a86ad014f6c87744bf6
// keycodes.zig SHA-256: eb6a10047e79c9d4749f51c674fdadb7f484f2bf3f2bfc37d624ccdae1c4e44b

/// Stable Ghostty/W3C physical-key values used across the process boundary.
///
/// Raw values are generated from Ghostty's `input.Key` declaration so the
/// Swift frontend can encode physical keys without importing or linking Ghostty.
public enum TerminalW3CKey: UInt32, Equatable, Hashable, Sendable {
    /// The W3C `Unidentified` physical key.
    case unidentified = 0
    /// The W3C `Backquote` physical key.
    case backquote = 1
    /// The W3C `Backslash` physical key.
    case backslash = 2
    /// The W3C `BracketLeft` physical key.
    case bracketLeft = 3
    /// The W3C `BracketRight` physical key.
    case bracketRight = 4
    /// The W3C `Comma` physical key.
    case comma = 5
    /// The W3C `Digit0` physical key.
    case digit0 = 6
    /// The W3C `Digit1` physical key.
    case digit1 = 7
    /// The W3C `Digit2` physical key.
    case digit2 = 8
    /// The W3C `Digit3` physical key.
    case digit3 = 9
    /// The W3C `Digit4` physical key.
    case digit4 = 10
    /// The W3C `Digit5` physical key.
    case digit5 = 11
    /// The W3C `Digit6` physical key.
    case digit6 = 12
    /// The W3C `Digit7` physical key.
    case digit7 = 13
    /// The W3C `Digit8` physical key.
    case digit8 = 14
    /// The W3C `Digit9` physical key.
    case digit9 = 15
    /// The W3C `Equal` physical key.
    case equal = 16
    /// The W3C `IntlBackslash` physical key.
    case intlBackslash = 17
    /// The W3C `IntlRo` physical key.
    case intlRo = 18
    /// The W3C `IntlYen` physical key.
    case intlYen = 19
    /// The W3C `KeyA` physical key.
    case keyA = 20
    /// The W3C `KeyB` physical key.
    case keyB = 21
    /// The W3C `KeyC` physical key.
    case keyC = 22
    /// The W3C `KeyD` physical key.
    case keyD = 23
    /// The W3C `KeyE` physical key.
    case keyE = 24
    /// The W3C `KeyF` physical key.
    case keyF = 25
    /// The W3C `KeyG` physical key.
    case keyG = 26
    /// The W3C `KeyH` physical key.
    case keyH = 27
    /// The W3C `KeyI` physical key.
    case keyI = 28
    /// The W3C `KeyJ` physical key.
    case keyJ = 29
    /// The W3C `KeyK` physical key.
    case keyK = 30
    /// The W3C `KeyL` physical key.
    case keyL = 31
    /// The W3C `KeyM` physical key.
    case keyM = 32
    /// The W3C `KeyN` physical key.
    case keyN = 33
    /// The W3C `KeyO` physical key.
    case keyO = 34
    /// The W3C `KeyP` physical key.
    case keyP = 35
    /// The W3C `KeyQ` physical key.
    case keyQ = 36
    /// The W3C `KeyR` physical key.
    case keyR = 37
    /// The W3C `KeyS` physical key.
    case keyS = 38
    /// The W3C `KeyT` physical key.
    case keyT = 39
    /// The W3C `KeyU` physical key.
    case keyU = 40
    /// The W3C `KeyV` physical key.
    case keyV = 41
    /// The W3C `KeyW` physical key.
    case keyW = 42
    /// The W3C `KeyX` physical key.
    case keyX = 43
    /// The W3C `KeyY` physical key.
    case keyY = 44
    /// The W3C `KeyZ` physical key.
    case keyZ = 45
    /// The W3C `Minus` physical key.
    case minus = 46
    /// The W3C `Period` physical key.
    case period = 47
    /// The W3C `Quote` physical key.
    case quote = 48
    /// The W3C `Semicolon` physical key.
    case semicolon = 49
    /// The W3C `Slash` physical key.
    case slash = 50
    /// The W3C `AltLeft` physical key.
    case altLeft = 51
    /// The W3C `AltRight` physical key.
    case altRight = 52
    /// The W3C `Backspace` physical key.
    case backspace = 53
    /// The W3C `CapsLock` physical key.
    case capsLock = 54
    /// The W3C `ContextMenu` physical key.
    case contextMenu = 55
    /// The W3C `ControlLeft` physical key.
    case controlLeft = 56
    /// The W3C `ControlRight` physical key.
    case controlRight = 57
    /// The W3C `Enter` physical key.
    case enter = 58
    /// The W3C `MetaLeft` physical key.
    case metaLeft = 59
    /// The W3C `MetaRight` physical key.
    case metaRight = 60
    /// The W3C `ShiftLeft` physical key.
    case shiftLeft = 61
    /// The W3C `ShiftRight` physical key.
    case shiftRight = 62
    /// The W3C `Space` physical key.
    case space = 63
    /// The W3C `Tab` physical key.
    case tab = 64
    /// The W3C `Convert` physical key.
    case convert = 65
    /// The W3C `KanaMode` physical key.
    case kanaMode = 66
    /// The W3C `NonConvert` physical key.
    case nonConvert = 67
    /// The W3C `Delete` physical key.
    case delete = 68
    /// The W3C `End` physical key.
    case end = 69
    /// The W3C `Help` physical key.
    case help = 70
    /// The W3C `Home` physical key.
    case home = 71
    /// The W3C `Insert` physical key.
    case insert = 72
    /// The W3C `PageDown` physical key.
    case pageDown = 73
    /// The W3C `PageUp` physical key.
    case pageUp = 74
    /// The W3C `ArrowDown` physical key.
    case arrowDown = 75
    /// The W3C `ArrowLeft` physical key.
    case arrowLeft = 76
    /// The W3C `ArrowRight` physical key.
    case arrowRight = 77
    /// The W3C `ArrowUp` physical key.
    case arrowUp = 78
    /// The W3C `NumLock` physical key.
    case numLock = 79
    /// The W3C `Numpad0` physical key.
    case numpad0 = 80
    /// The W3C `Numpad1` physical key.
    case numpad1 = 81
    /// The W3C `Numpad2` physical key.
    case numpad2 = 82
    /// The W3C `Numpad3` physical key.
    case numpad3 = 83
    /// The W3C `Numpad4` physical key.
    case numpad4 = 84
    /// The W3C `Numpad5` physical key.
    case numpad5 = 85
    /// The W3C `Numpad6` physical key.
    case numpad6 = 86
    /// The W3C `Numpad7` physical key.
    case numpad7 = 87
    /// The W3C `Numpad8` physical key.
    case numpad8 = 88
    /// The W3C `Numpad9` physical key.
    case numpad9 = 89
    /// The W3C `NumpadAdd` physical key.
    case numpadAdd = 90
    /// The W3C `NumpadBackspace` physical key.
    case numpadBackspace = 91
    /// The W3C `NumpadClear` physical key.
    case numpadClear = 92
    /// The W3C `NumpadClearEntry` physical key.
    case numpadClearEntry = 93
    /// The W3C `NumpadComma` physical key.
    case numpadComma = 94
    /// The W3C `NumpadDecimal` physical key.
    case numpadDecimal = 95
    /// The W3C `NumpadDivide` physical key.
    case numpadDivide = 96
    /// The W3C `NumpadEnter` physical key.
    case numpadEnter = 97
    /// The W3C `NumpadEqual` physical key.
    case numpadEqual = 98
    /// The W3C `NumpadMemoryAdd` physical key.
    case numpadMemoryAdd = 99
    /// The W3C `NumpadMemoryClear` physical key.
    case numpadMemoryClear = 100
    /// The W3C `NumpadMemoryRecall` physical key.
    case numpadMemoryRecall = 101
    /// The W3C `NumpadMemoryStore` physical key.
    case numpadMemoryStore = 102
    /// The W3C `NumpadMemorySubtract` physical key.
    case numpadMemorySubtract = 103
    /// The W3C `NumpadMultiply` physical key.
    case numpadMultiply = 104
    /// The W3C `NumpadParenLeft` physical key.
    case numpadParenLeft = 105
    /// The W3C `NumpadParenRight` physical key.
    case numpadParenRight = 106
    /// The W3C `NumpadSubtract` physical key.
    case numpadSubtract = 107
    /// The W3C `NumpadSeparator` physical key.
    case numpadSeparator = 108
    /// The W3C `NumpadUp` physical key.
    case numpadUp = 109
    /// The W3C `NumpadDown` physical key.
    case numpadDown = 110
    /// The W3C `NumpadRight` physical key.
    case numpadRight = 111
    /// The W3C `NumpadLeft` physical key.
    case numpadLeft = 112
    /// The W3C `NumpadBegin` physical key.
    case numpadBegin = 113
    /// The W3C `NumpadHome` physical key.
    case numpadHome = 114
    /// The W3C `NumpadEnd` physical key.
    case numpadEnd = 115
    /// The W3C `NumpadInsert` physical key.
    case numpadInsert = 116
    /// The W3C `NumpadDelete` physical key.
    case numpadDelete = 117
    /// The W3C `NumpadPageUp` physical key.
    case numpadPageUp = 118
    /// The W3C `NumpadPageDown` physical key.
    case numpadPageDown = 119
    /// The W3C `Escape` physical key.
    case escape = 120
    /// The W3C `F1` physical key.
    case f1 = 121
    /// The W3C `F2` physical key.
    case f2 = 122
    /// The W3C `F3` physical key.
    case f3 = 123
    /// The W3C `F4` physical key.
    case f4 = 124
    /// The W3C `F5` physical key.
    case f5 = 125
    /// The W3C `F6` physical key.
    case f6 = 126
    /// The W3C `F7` physical key.
    case f7 = 127
    /// The W3C `F8` physical key.
    case f8 = 128
    /// The W3C `F9` physical key.
    case f9 = 129
    /// The W3C `F10` physical key.
    case f10 = 130
    /// The W3C `F11` physical key.
    case f11 = 131
    /// The W3C `F12` physical key.
    case f12 = 132
    /// The W3C `F13` physical key.
    case f13 = 133
    /// The W3C `F14` physical key.
    case f14 = 134
    /// The W3C `F15` physical key.
    case f15 = 135
    /// The W3C `F16` physical key.
    case f16 = 136
    /// The W3C `F17` physical key.
    case f17 = 137
    /// The W3C `F18` physical key.
    case f18 = 138
    /// The W3C `F19` physical key.
    case f19 = 139
    /// The W3C `F20` physical key.
    case f20 = 140
    /// The W3C `F21` physical key.
    case f21 = 141
    /// The W3C `F22` physical key.
    case f22 = 142
    /// The W3C `F23` physical key.
    case f23 = 143
    /// The W3C `F24` physical key.
    case f24 = 144
    /// The W3C `F25` physical key.
    case f25 = 145
    /// The W3C `Fn` physical key.
    case fn = 146
    /// The W3C `FnLock` physical key.
    case fnLock = 147
    /// The W3C `PrintScreen` physical key.
    case printScreen = 148
    /// The W3C `ScrollLock` physical key.
    case scrollLock = 149
    /// The W3C `Pause` physical key.
    case pause = 150
    /// The W3C `BrowserBack` physical key.
    case browserBack = 151
    /// The W3C `BrowserFavorites` physical key.
    case browserFavorites = 152
    /// The W3C `BrowserForward` physical key.
    case browserForward = 153
    /// The W3C `BrowserHome` physical key.
    case browserHome = 154
    /// The W3C `BrowserRefresh` physical key.
    case browserRefresh = 155
    /// The W3C `BrowserSearch` physical key.
    case browserSearch = 156
    /// The W3C `BrowserStop` physical key.
    case browserStop = 157
    /// The W3C `Eject` physical key.
    case eject = 158
    /// The W3C `LaunchApp1` physical key.
    case launchApp1 = 159
    /// The W3C `LaunchApp2` physical key.
    case launchApp2 = 160
    /// The W3C `LaunchMail` physical key.
    case launchMail = 161
    /// The W3C `MediaPlayPause` physical key.
    case mediaPlayPause = 162
    /// The W3C `MediaSelect` physical key.
    case mediaSelect = 163
    /// The W3C `MediaStop` physical key.
    case mediaStop = 164
    /// The W3C `MediaTrackNext` physical key.
    case mediaTrackNext = 165
    /// The W3C `MediaTrackPrevious` physical key.
    case mediaTrackPrevious = 166
    /// The W3C `Power` physical key.
    case power = 167
    /// The W3C `Sleep` physical key.
    case sleep = 168
    /// The W3C `AudioVolumeDown` physical key.
    case audioVolumeDown = 169
    /// The W3C `AudioVolumeMute` physical key.
    case audioVolumeMute = 170
    /// The W3C `AudioVolumeUp` physical key.
    case audioVolumeUp = 171
    /// The W3C `WakeUp` physical key.
    case wakeUp = 172
    /// The W3C `Copy` physical key.
    case copy = 173
    /// The W3C `Cut` physical key.
    case cut = 174
    /// The W3C `Paste` physical key.
    case paste = 175
}
