/**
 * cmux-next Postgres schema (Drizzle). Generated by `drizzle-kit pull` from the database the
 * committed migrations build, and kept in that form: test-pg/drizzle-schema.test.ts pulls again
 * and fails on any difference. home_message_search is hash-partitioned, which Drizzle does not
 * model; it stays in raw SQL (migrations/0006_home.sql, apps/api/src/home-search.ts).
 */
import { pgTable, unique, text, bigint, timestamp, check, index, boolean, integer, jsonb, primaryKey, uniqueIndex } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const users = pgTable("users", {
	id: text().primaryKey().notNull(),
	stackUserId: text("stack_user_id").notNull(),
	email: text(),
	displayName: text("display_name").notNull(),
	personalTeam: text("personal_team").notNull(),
	sourceStream: text("source_stream").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceSeq: bigint("source_seq", { mode: "number" }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("users_stack_user_id_key").on(table.stackUserId),
]);

export const teams = pgTable("teams", {
	id: text().primaryKey().notNull(),
	kind: text().notNull(),
	stackTeamId: text("stack_team_id"),
	displayName: text("display_name").notNull(),
	sourceStream: text("source_stream").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceSeq: bigint("source_seq", { mode: "number" }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("teams_stack_team_id_key").on(table.stackTeamId),
	check("teams_kind_check", sql`kind = ANY (ARRAY['personal'::text, 'stack'::text])`),
]);

export const automations = pgTable("automations", {
	id: text().primaryKey().notNull(),
	teamId: text("team_id").notNull(),
	name: text().notNull(),
	enabled: boolean().notNull(),
	version: integer().notNull(),
	definition: jsonb().notNull(),
	createdBy: text("created_by").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).notNull(),
	nextRunAt: timestamp("next_run_at", { withTimezone: true, mode: 'string' }),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
	sourceStream: text("source_stream").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceSeq: bigint("source_seq", { mode: "number" }).notNull(),
}, (table) => [
	index("automations_team").using("btree", table.teamId.asc().nullsLast().op("text_ops")).where(sql`(deleted_at IS NULL)`),
]);

export const installs = pgTable("installs", {
	id: text().primaryKey().notNull(),
	userId: text("user_id").notNull(),
	deviceId: text("device_id").notNull(),
	kind: text().notNull(),
	name: text().notNull(),
	deviceName: text("device_name").notNull(),
	platform: text().notNull(),
	thumbprint: text().notNull(),
	grantId: text("grant_id").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).notNull(),
	revokedAt: timestamp("revoked_at", { withTimezone: true, mode: 'string' }),
	sourceStream: text("source_stream").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceSeq: bigint("source_seq", { mode: "number" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("installs_user").using("btree", table.userId.asc().nullsLast().op("text_ops")),
]);

export const hosts = pgTable("hosts", {
	id: text().primaryKey().notNull(),
	teamId: text("team_id").notNull(),
	ownerUser: text("owner_user").notNull(),
	enrolledBy: text("enrolled_by").notNull(),
	name: text().notNull(),
	platform: text().notNull(),
	enrolledAt: timestamp("enrolled_at", { withTimezone: true, mode: 'string' }).notNull(),
	deletedAt: timestamp("deleted_at", { withTimezone: true, mode: 'string' }),
	sourceStream: text("source_stream").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceSeq: bigint("source_seq", { mode: "number" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("hosts_team").using("btree", table.teamId.asc().nullsLast().op("text_ops")).where(sql`(deleted_at IS NULL)`),
]);

export const automationRuns = pgTable("automation_runs", {
	id: text().primaryKey().notNull(),
	teamId: text("team_id").notNull(),
	automationId: text("automation_id").notNull(),
	automationVersion: integer("automation_version").notNull(),
	triggerType: text("trigger_type").notNull(),
	trigger: jsonb().notNull(),
	state: text().notNull(),
	step: integer().notNull(),
	error: jsonb(),
	outcome: jsonb(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).notNull(),
	startedAt: timestamp("started_at", { withTimezone: true, mode: 'string' }),
	finishedAt: timestamp("finished_at", { withTimezone: true, mode: 'string' }),
	sourceStream: text("source_stream").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceSeq: bigint("source_seq", { mode: "number" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("automation_runs_automation").using("btree", table.automationId.asc().nullsLast().op("text_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	index("automation_runs_team").using("btree", table.teamId.asc().nullsLast().op("text_ops"), table.createdAt.desc().nullsFirst().op("text_ops")),
]);

export const connections = pgTable("connections", {
	id: text().primaryKey().notNull(),
	teamId: text("team_id").notNull(),
	createdBy: text("created_by").notNull(),
	provider: text().notNull(),
	accountKey: text("account_key"),
	accountName: text("account_name"),
	scopesRequested: jsonb("scopes_requested").notNull(),
	scopesGranted: jsonb("scopes_granted").notNull(),
	status: text().notNull(),
	sharing: text().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).notNull(),
	sourceStream: text("source_stream").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceSeq: bigint("source_seq", { mode: "number" }).notNull(),
}, (table) => [
	index("connections_account").using("btree", table.accountKey.asc().nullsLast().op("text_ops")).where(sql`(account_key IS NOT NULL)`),
	index("connections_team").using("btree", table.teamId.asc().nullsLast().op("text_ops")),
]);

export const homeConversations = pgTable("home_conversations", {
	id: text().primaryKey().notNull(),
	kind: text().notNull(),
	teamId: text("team_id"),
	title: text(),
	createdBy: text("created_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	lastSeq: bigint("last_seq", { mode: "number" }).notNull(),
	lastAt: timestamp("last_at", { withTimezone: true, mode: 'string' }).notNull(),
	participantCount: integer("participant_count").notNull(),
	state: text().notNull(),
	sourceStream: text("source_stream").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceSeq: bigint("source_seq", { mode: "number" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("home_conversations_team").using("btree", table.teamId.asc().nullsLast().op("text_ops"), table.lastAt.desc().nullsFirst().op("text_ops")).where(sql`(team_id IS NOT NULL)`),
	check("home_conversations_kind_check", sql`kind = ANY (ARRAY['chief'::text, 'dm'::text, 'group'::text])`),
	check("home_conversations_state_check", sql`state = ANY (ARRAY['active'::text, 'archived'::text])`),
]);

export const homeInvites = pgTable("home_invites", {
	id: text().primaryKey().notNull(),
	conversationId: text("conversation_id").notNull(),
	invitedBy: text("invited_by").notNull(),
	addressId: text("address_id").notNull(),
	channel: text().notNull(),
	status: text().notNull(),
	deliveryState: text("delivery_state").notNull(),
	copyVariant: text("copy_variant").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).notNull(),
	expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'string' }).notNull(),
	acceptedBy: text("accepted_by"),
	acceptedAt: timestamp("accepted_at", { withTimezone: true, mode: 'string' }),
	sourceStream: text("source_stream").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceSeq: bigint("source_seq", { mode: "number" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("home_invites_address").using("btree", table.addressId.asc().nullsLast().op("text_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	index("home_invites_conversation").using("btree", table.conversationId.asc().nullsLast().op("text_ops")),
	index("home_invites_inviter").using("btree", table.invitedBy.asc().nullsLast().op("timestamptz_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	check("home_invites_channel_check", sql`channel = ANY (ARRAY['email'::text, 'sms'::text])`),
	check("home_invites_status_check", sql`status = ANY (ARRAY['pending'::text, 'pending_approval'::text, 'accepted'::text, 'revoked'::text, 'expired'::text])`),
]);

export const memberships = pgTable("memberships", {
	teamId: text("team_id").notNull(),
	userId: text("user_id").notNull(),
	role: text().notNull(),
	sourceStream: text("source_stream").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceSeq: bigint("source_seq", { mode: "number" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("memberships_user").using("btree", table.userId.asc().nullsLast().op("text_ops")),
	primaryKey({ columns: [table.teamId, table.userId], name: "memberships_pkey"}),
	check("memberships_role_check", sql`role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text])`),
]);

export const homeParticipants = pgTable("home_participants", {
	conversationId: text("conversation_id").notNull(),
	participantId: text("participant_id").notNull(),
	kind: text().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	visibleFromSeq: bigint("visible_from_seq", { mode: "number" }).default(0).notNull(),
	joinedAt: timestamp("joined_at", { withTimezone: true, mode: 'string' }).notNull(),
	leftAt: timestamp("left_at", { withTimezone: true, mode: 'string' }),
	sourceStream: text("source_stream").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceSeq: bigint("source_seq", { mode: "number" }).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("home_participants_member").using("btree", table.participantId.asc().nullsLast().op("text_ops"), table.conversationId.asc().nullsLast().op("text_ops")).where(sql`(left_at IS NULL)`),
	primaryKey({ columns: [table.conversationId, table.participantId], name: "home_participants_pkey"}),
	check("home_participants_kind_check", sql`kind = ANY (ARRAY['human'::text, 'agent'::text, 'address'::text])`),
]);

export const auditEvents = pgTable("audit_events", {
	teamId: text("team_id").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	n: bigint({ mode: "number" }).notNull(),
	op: text().notNull(),
	actor: text().notNull(),
	onBehalfOf: text("on_behalf_of"),
	transaction: text().notNull(),
	at: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
	summary: text().notNull(),
	detail: jsonb().notNull(),
	prevHash: text("prev_hash").notNull(),
	hash: text().notNull(),
	sourceStream: text("source_stream").notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	sourceSeq: bigint("source_seq", { mode: "number" }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	uniqueIndex("audit_events_source").using("btree", table.sourceStream.asc().nullsLast().op("text_ops"), table.sourceSeq.asc().nullsLast().op("int8_ops")),
	index("audit_events_team_at").using("btree", table.teamId.asc().nullsLast().op("text_ops"), table.at.desc().nullsFirst().op("text_ops")),
	primaryKey({ columns: [table.teamId, table.n], name: "audit_events_pkey"}),
]);
