// GENERATED by scripts/cmux-next/gen-protected-folders.py from
// cmux-tui/crates/acpmux/data/protected-folders.json. Do not edit; edit the JSON and rerun.

/// One folder macOS guards with a privacy prompt (LAUNCH-NO-TCC-PROMPTS): a path relative to
/// the home folder (`inHome`) or an absolute one (`roots`), and its kind.
nonisolated struct ProtectedFolderEntry: Sendable, Equatable {
    let path: String
    let kind: String

    /// The guarded folders inside the home folder.
    static let inHome: [ProtectedFolderEntry] = [
        ProtectedFolderEntry(path: "Desktop", kind: "desktop"),
        ProtectedFolderEntry(path: "Documents", kind: "documents"),
        ProtectedFolderEntry(path: "Downloads", kind: "downloads"),
        ProtectedFolderEntry(path: "Pictures", kind: "pictures"),
        ProtectedFolderEntry(path: "Music", kind: "music"),
        ProtectedFolderEntry(path: "Movies", kind: "movies"),
        ProtectedFolderEntry(path: "Library/Mobile Documents", kind: "iCloudDrive"),
        ProtectedFolderEntry(path: "Library/CloudStorage", kind: "cloudStorage"),
        ProtectedFolderEntry(path: "Library/Containers", kind: "appData"),
        ProtectedFolderEntry(path: "Library/Group Containers", kind: "appData"),
        ProtectedFolderEntry(path: "Library/Mail", kind: "appData"),
        ProtectedFolderEntry(path: "Library/Messages", kind: "appData"),
        ProtectedFolderEntry(path: "Library/Safari", kind: "appData"),
        ProtectedFolderEntry(path: "Library/Calendars", kind: "appData"),
    ]

    /// The guarded folders outside any home folder: other and network volumes.
    static let roots: [ProtectedFolderEntry] = [
        ProtectedFolderEntry(path: "/Volumes", kind: "volumes"),
        ProtectedFolderEntry(path: "/Network", kind: "network"),
        ProtectedFolderEntry(path: "/net", kind: "network"),
    ]
}
