import Foundation

extension AgentLaunchSanitizer {
    /// Keeps safe interactive Prime Agent launch options while removing a
    /// previously selected session. The cmux integration supplies the session
    /// file explicitly from the extension's session manager.
    static let primeAgentPolicy = Policy(
        valueOptions: [
            "--api-key",
            "--append-system-prompt",
            "--cwd",
            "--extension",
            "-e",
            "--fork",
            "--model",
            "--models",
            "--prompt-template",
            "--provider",
            "--session-dir",
            "--skill",
            "--system-prompt",
            "--theme",
            "--thinking",
            "--tools",
            "-t",
        ],
        optionalValueOptions: [
            "--resume",
            "-r",
        ],
        booleanOptions: [
            "--continue",
            "-c",
            "--no-builtin-tools",
            "-nbt",
            "--no-context-files",
            "-nc",
            "--no-extensions",
            "-ne",
            "--no-skills",
            "-ns",
            "--no-themes",
            "--no-tools",
            "-nt",
            "--no-prompt-templates",
            "-np",
            "--offline",
            "--verbose",
        ],
        nonRestorableCommands: [
            "agents",
            "attach",
            "config",
            "daemon",
            "doctor",
            "help",
            "init",
            "install",
            "list",
            "login",
            "logout",
            "model",
            "package",
            "rename",
            "schedule",
            "session",
            "send",
            "shutdown",
            "status",
            "stop",
            "update",
            "version",
        ],
        droppedOptions: [
            "--api-key",
            "--continue",
            "-c",
            "--fork",
            "--resume",
            "-r",
        ],
        droppedOptionPrefixes: [
            "--api-key=",
            "--continue=",
            "--fork=",
            "--resume=",
        ],
        rejectOptions: [
            "--acp",
            "--autonomous",
            "--autonomous-gate",
            "--autonomous-gate-retries",
            "--autonomous-gate-timeout-ms",
            "--autonomous-max-continuations",
            "--autonomous-max-tokens",
            "--autonomous-max-turns",
            "--autonomous-timeout-ms",
            "--daemon-socket",
            "--daemon",
            "--export",
            "--json",
            "--list-models",
            "--mode",
            "--no-session",
            "--print",
            "--prompt",
            "-p",
            "--rpc",
            "--version",
            "-h",
            "-v",
            "--goal",
            "--goal-token-budget",
            "--help",
        ]
    )
}
