import Foundation

extension AgentLaunchSanitizer {
    static let grokPolicy = Policy(
        valueOptions: [
            "--agent",
            "--agents",
            "--allow",
            "--cwd",
            "--deny",
            "--debug-file",
            "--disallowed-tools",
            "--effort",
            "--json-schema",
            "--leader-socket",
            "--max-turns",
            "--model",
            "-m",
            "--permission-mode",
            "--reasoning-effort",
            "--resume",
            "-r",
            "--rules",
            "--sandbox",
            "--session-id",
            "--system-prompt-override",
            "--tools",
            "--worktree",
            "--worktree-ref",
            "-w"
        ],
        optionalValueOptions: [
            "--resume",
            "-r",
            "--worktree",
            "-w"
        ],
        booleanOptions: [
            "--always-approve",
            "--debug",
            "--disable-web-search",
            "--experimental-memory",
            "--fullscreen",
            "--minimal",
            "--no-alt-screen",
            "--no-memory",
            "--no-plan",
            "--no-subagents",
            "--oauth",
            "--verbatim",
        ],
        nonRestorableCommands: [
            "agent",
            "completions",
            "dashboard",
            "export",
            "help",
            "import",
            "inspect",
            "leader",
            "login",
            "logout",
            "mcp",
            "memory",
            "models",
            "plugin",
            "sessions",
            "setup",
            "share",
            "ssh",
            "trace",
            "update",
            "version",
            "v",
            "worktree",
            "wrap"
        ],
        droppedOptions: [
            "--continue",
            "-c",
            "--restore-code",
            "--resume",
            "-r",
            "--fork-session",
            "--session-id",
            "--worktree",
            "--worktree-ref",
            "-w"
        ],
        droppedOptionPrefixes: [
            "--resume=",
            "-r=",
            "--fork-session=",
            "--session-id=",
            "--worktree=",
            "--worktree-ref=",
            "-w="
        ],
        rejectOptions: [
            "--best-of-n",
            "--output-format",
            "--prompt-file",
            "--prompt-json",
            "--single",
            "-p"
        ]
    )
}
