// Every string key the Cloud page uses. Values live in `Localizable.xcstrings` next to this file;
// scripts/pages/gen-strings.mjs writes `generated/strings.json`. Placeholders are `{name}` and are
// filled by `format`. strings.test.ts checks that every key has every required language.

export const L = {
  title: "page.title",
  disconnected: "page.disconnected",
  loading: "page.loading",
  dismissError: "page.dismissError",
  retry: "page.retry",
  actionFailed: "page.actionFailed",
  unavailable: "page.unavailable",
  gigabytes: "unit.gigabytes",
  hours: "unit.hours",
  bytes: "unit.bytes",
  kilobytes: "unit.kilobytes",
  megabytes: "unit.megabytes",
  signedOutTitle: "auth.signedOutTitle",
  signedOutBody: "auth.signedOutBody",
  signIn: "auth.signIn",
  signOut: "auth.signOut",
  team: "team.label",
  machines: "machines.title",
  empty: "machines.empty",
  emptyBody: "machines.emptyBody",
  create: "machines.create",
  classic: "machines.classic",
  classicReadOnly: "machines.classicReadOnly",
  migrationTitle: "migration.title",
  migrationBody: "migration.body",
  migrationMove: "migration.move",
  migrationLater: "migration.later",
  statusProvisioning: "status.provisioning",
  statusStarting: "status.starting",
  statusRunning: "status.running",
  statusPausing: "status.pausing",
  statusFailed: "status.failed",
  statusPaused: "status.paused",
  statusDeleting: "status.deleting",
  statusUnknown: "status.unknown",
  pendingCreate: "intent.create",
  pendingStart: "intent.start",
  pendingPause: "intent.pause",
  pendingRename: "intent.rename",
  pendingResize: "intent.resize",
  pendingDelete: "intent.delete",
  pendingIdle: "intent.idle",
  pendingUpgrade: "intent.upgrade",
  pause: "action.pause",
  resume: "action.resume",
  connect: "action.connect",
  upgradeMachine: "action.upgrade",
  rename: "action.rename",
  save: "action.save",
  cancel: "action.cancel",
  delete: "action.delete",
  restore: "action.restore",
  createSheetTitle: "create.title",
  createName: "create.name",
  createNamePlaceholder: "create.namePlaceholder",
  createSize: "create.size",
  createSnapshot: "create.snapshot",
  createBaseImage: "create.baseImage",
  createSubmit: "create.submit",
  createSubmitting: "create.submitting",
  planRequired: "error.planRequired",
  quotaExceeded: "error.quotaExceeded",
  sizeLocked: "error.sizeLocked",
  seePlans: "plan.seePlans",
  createLimit: "create.limit",
  createLimitReached: "create.limitReached",
  sizeNotInPlan: "create.sizeNotInPlan",
  sizeSpec: "size.spec",
  overview: "detail.overview",
  snapshots: "detail.snapshots",
  fieldId: "field.id",
  fieldSize: "field.size",
  fieldImage: "field.image",
  fieldCreated: "field.created",
  fieldIdle: "field.idle",
  idleNever: "idle.never",
  idleMinutes: "idle.minutes",
  idleHours: "idle.hours",
  noSnapshots: "snapshots.empty",
  snapshotCreate: "snapshots.create",
  snapshotUnnamed: "snapshots.unnamed",
  files: "files.title",
  filesBrowse: "files.browse",
  filesUp: "files.up",
  filesNewFolder: "files.newFolder",
  filesUpload: "files.upload",
  filesDownload: "files.download",
  filesEdit: "files.edit",
  filesEmpty: "files.empty",
  filesFolder: "files.folder",
  filesTooLarge: "files.tooLarge",
  filesBinary: "files.binary",
  filesNoPreview: "files.noPreview",
  filesClosePreview: "files.closePreview",
  transfers: "files.transfers",
  transferRunning: "files.transferRunning",
  transferDone: "files.transferDone",
  transferFailed: "files.transferFailed",
  transferCancelled: "files.transferCancelled",
  transferBusy: "files.transferBusy",
  ports: "ports.title",
  portsForward: "ports.forward",
  portsEmpty: "ports.empty",
  portsUp: "ports.up",
  portsDown: "ports.down",
  portsClose: "ports.close",
  openBrowser: "ports.openBrowser",
  browserProxy: "ports.browserProxy",
  browserTabUnavailable: "ports.browserTabUnavailable",
  browserTabRefused: "ports.browserTabRefused",
  plan: "plan.title",
  planMachines: "plan.machines",
  planUsed: "plan.used",
  usage: "usage.title",
  usageCompute: "usage.compute",
  selectMachine: "detail.selectMachine",
} as const;

export type StringKey = (typeof L)[keyof typeof L];

/** Fills `{name}` placeholders. Missing values stay visible as `{name}`. */
export function format(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{([a-z]+)\}/g, (match, name: string) => (name in values ? String(values[name]) : match));
}
