//! Service definition goldens: every variant runs `<current>/bin/cmux host run`.

use cmux_server_core::layout::{Layout, LayoutEnv, layout};
use cmux_server_core::units::{
    UnitError, host_run_argv, launch_agent_plist, launch_daemon_plist, scheduled_task_xml,
    systemd_system_unit, systemd_user_unit, windows_service_create_argv,
    windows_service_failure_argv,
};
use cmux_server_core::{InstallMode, Platform};

fn unix(mode: InstallMode, platform: Platform, home: &str) -> Layout {
    layout(mode, platform, &LayoutEnv { home: Some(home.to_owned()), ..LayoutEnv::default() }).unwrap()
}

fn win(mode: InstallMode) -> Layout {
    let env = LayoutEnv {
        local_app_data: Some(r"C:\Users\ana\AppData\Local".to_owned()),
        app_data: Some(r"C:\Users\ana\AppData\Roaming".to_owned()),
        program_data: Some(r"C:\ProgramData".to_owned()),
        program_files: Some(r"C:\Program Files".to_owned()),
        ..LayoutEnv::default()
    };
    layout(mode, Platform::Windows, &env).unwrap()
}

#[test]
fn systemd_user_unit_golden() {
    let l = unix(InstallMode::User, Platform::Linux, "/home/ana");
    assert_eq!(host_run_argv(&l), ["/home/ana/.local/share/cmux/current/bin/cmux", "host", "run"]);
    assert_eq!(
        systemd_user_unit(&l).unwrap(),
        "# Generated by cmux. Do not edit: `cmux server install` rewrites this file.
[Unit]
Description=cmux server
Documentation=https://cmux.com/docs/server
Wants=network-online.target
After=network-online.target

[Service]
Type=exec
ExecStart=\"/home/ana/.local/share/cmux/current/bin/cmux\" host run
Environment=CMUX_SERVER_MODE=user
Restart=always
RestartSec=2
# The session host keeps its terminal hosts across a restart: stop only the
# supervisor process (lane 1 handoff contract).
KillMode=process
TimeoutStopSec=30
NoNewPrivileges=yes

[Install]
WantedBy=default.target
"
    );
}

#[test]
fn systemd_system_unit_golden() {
    let l = unix(InstallMode::System, Platform::Linux, "/root");
    assert_eq!(
        systemd_system_unit(&l).unwrap(),
        "# Generated by cmux. Do not edit: `cmux server install --system` rewrites this file.
[Unit]
Description=cmux server
Documentation=https://cmux.com/docs/server
Wants=network-online.target
After=network-online.target

[Service]
Type=exec
User=cmux
Group=cmux
ExecStart=\"/opt/cmux/current/bin/cmux\" host run
Environment=CMUX_SERVER_MODE=system
Restart=always
RestartSec=2
KillMode=process
TimeoutStopSec=30
StateDirectory=cmux
StateDirectoryMode=0700
RuntimeDirectory=cmux
RuntimeDirectoryMode=0755
RuntimeDirectoryPreserve=yes
ConfigurationDirectory=cmux
UMask=0027
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=full
ProtectHome=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes
LockPersonality=yes

[Install]
WantedBy=multi-user.target
"
    );
    assert_eq!(systemd_user_unit(&l), Err(UnitError::WrongLayout));
}

#[test]
fn systemd_refuses_unsafe_exec_path() {
    let l = unix(InstallMode::User, Platform::Linux, "/home/a$b");
    assert_eq!(systemd_user_unit(&l), Err(UnitError::UnsafePath("current_cmux")));
}

#[test]
fn launch_agent_plist_golden() {
    let l = unix(InstallMode::User, Platform::MacOs, "/Users/ana");
    assert_eq!(
        launch_agent_plist(&l).unwrap(),
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
  <key>Label</key>
  <string>com.cmux.server</string>
  <key>ProgramArguments</key>
  <array>
    <string>/Users/ana/Library/Application Support/cmux/current/bin/cmux</string>
    <string>host</string>
    <string>run</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>CMUX_SERVER_MODE</key>
    <string>user</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ProcessType</key>
  <string>Standard</string>
  <key>ThrottleInterval</key>
  <integer>2</integer>
  <key>StandardOutPath</key>
  <string>/Users/ana/Library/Application Support/cmux/server/logs/server.log</string>
  <key>StandardErrorPath</key>
  <string>/Users/ana/Library/Application Support/cmux/server/logs/server.log</string>
</dict>
</plist>
"
    );
}

#[test]
fn launch_daemon_and_app_variants() {
    let l = unix(InstallMode::User, Platform::MacOs, "/Users/a&b");
    let daemon = launch_daemon_plist(&l, "ana").unwrap();
    assert!(daemon.contains("  <key>UserName</key>\n  <string>ana</string>\n"));
    assert!(daemon.contains("<string>/Users/a&amp;b/Library/Application Support/cmux/current/bin/cmux</string>"));
    assert_eq!(launch_daemon_plist(&l, "ana</string>"), Err(UnitError::BadUser));

    let mut env = LayoutEnv { home: Some("/Users/ana".to_owned()), ..LayoutEnv::default() };
    env.mac_app_bundle = Some("/Applications/cmux.app".to_owned());
    let app = layout(InstallMode::User, Platform::MacOs, &env).unwrap();
    let plist = launch_agent_plist(&app).unwrap();
    assert!(plist.contains("<key>BundleProgram</key>\n  <string>Contents/Resources/bin/cmux</string>"));
    assert!(plist.contains("<string>/Applications/cmux.app/Contents/Resources/bin/cmux</string>"));

    let system = unix(InstallMode::System, Platform::MacOs, "/var/root");
    assert_eq!(launch_agent_plist(&system), Err(UnitError::WrongLayout));
    assert!(launch_daemon_plist(&system, "_cmux").unwrap().contains("<string>/Library/Application Support/cmux/current/bin/cmux</string>"));
}

#[test]
fn windows_service_argv_golden() {
    let l = win(InstallMode::System);
    assert_eq!(
        windows_service_create_argv(&l).unwrap(),
        [
            "sc.exe",
            "create",
            "cmux-server",
            "binPath=",
            r#""C:\ProgramData\cmux\current\bin\cmux.exe" host run"#,
            "start=",
            "auto",
            "obj=",
            r"NT SERVICE\cmux-server",
            "DisplayName=",
            "cmux server",
        ]
    );
    assert_eq!(
        windows_service_failure_argv(),
        ["sc.exe", "failure", "cmux-server", "reset=", "86400", "actions=", "restart/2000/restart/2000/restart/60000"]
    );
    assert_eq!(windows_service_create_argv(&win(InstallMode::User)), Err(UnitError::WrongLayout));
}

#[test]
fn scheduled_task_xml_golden_parts() {
    let l = win(InstallMode::User);
    let xml = scheduled_task_xml(&l, r"DESKTOP-1\ana").unwrap();
    assert!(xml.starts_with("<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n<Task version=\"1.4\""));
    assert!(xml.contains("    <LogonTrigger>\n      <Enabled>true</Enabled>\n      <UserId>DESKTOP-1\\ana</UserId>\n    </LogonTrigger>\n"));
    assert!(xml.contains("      <RunLevel>LeastPrivilege</RunLevel>\n"));
    assert!(xml.contains("    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n"));
    assert!(xml.contains("    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\n"));
    assert!(xml.contains(
        "      <Command>C:\\Users\\ana\\AppData\\Local\\cmux\\current\\bin\\cmux.exe</Command>\n      <Arguments>host run</Arguments>\n"
    ));
    assert_eq!(scheduled_task_xml(&l, "ana<x>"), Err(UnitError::BadUser));
    assert_eq!(scheduled_task_xml(&l, r"\ana"), Err(UnitError::BadUser));
    assert_eq!(scheduled_task_xml(&win(InstallMode::System), "ana"), Err(UnitError::WrongLayout));
}
