import type { Locale } from "./approval-strings"

/** Localized strings for the team VM card on the Team page (English and Japanese, the languages cmux ships). */
const en = {
  "card.title": "Team VM",
  "card.loading": "Loading",
  "card.error.load": "The team VM status did not load: {error}",
  "status.none": "Not created",
  "status.provisioning": "Creating",
  "status.starting": "Starting",
  "status.running": "Running",
  "status.paused": "Paused",
  "status.failed": "Failed",
  "field.vm": "VM",
  "field.epoch": "Epoch",
  "badge.clean": "Not tainted",
  "badge.tainted": "Tainted",
  "badge.accepted": "Tainted, risk accepted",
  "taint.detail": "A removed member held a team SSH certificate while this VM ran. Members are root on the VM (sudo, docker), so cmux cannot prove that the VM is clean.",
  "taint.blocked": "Until an owner or admin accepts the risk or rebuilds the VM, only owners and admins get new team SSH certificates, and the VM cannot bind again.",
  "taint.users": "Removed members",
  "taint.since": "Tainted {when}",
  "taint.accepted": "{who} accepted the risk {when}. Members get certificates again.",
  "taint.member_hint": "Ask a team owner or admin to accept the risk or rebuild the VM.",
  "action.accept": "Accept the risk",
  "action.rebuild": "Rebuild from snapshot",
  "action.delete": "Delete",
  "action.download": "Download files",
  "action.cancel": "Cancel",
  "rebuild.full": "Delete a retired VM first. cmux keeps at most 3 retired VMs.",
  "confirm.accept.title": "Accept the risk and keep this VM?",
  "confirm.accept.body": "The removed members may have left changes on the VM. Members get team SSH certificates again, and the VM may bind again. This is recorded in the team audit log.",
  "confirm.accept.button": "Accept the risk",
  "confirm.rebuild.title": "Rebuild the team VM from the base snapshot?",
  "confirm.rebuild.body": "cmux starts a new VM at epoch {epoch} from the base snapshot. The current VM is paused and kept as a retired VM.",
  "confirm.rebuild.files": "Team files on /srv/team are NOT carried to the new VM. They stay on the paused old VM. Download the team files first: after the rebuild, download the team files from the retired VM row before you delete that VM.",
  "confirm.rebuild.button": "Rebuild from snapshot",
  "retired.title": "Retired VMs",
  "retired.intro": "A rebuild pauses the old VM and keeps it, with its team files on /srv/team, until an owner or admin deletes it. Download files saves /srv/team as a .tar archive without starting the VM.",
  "retired.pausing": "Pausing",
  "retired.paused": "Paused",
  "retired.by": "Rebuilt by {who} {when}",
  "confirm.delete.title": "Delete retired VM {vm}?",
  "confirm.delete.body": "This deletes the VM and all of its files, including the team files on /srv/team. You cannot undo this.",
  "confirm.download_first": "Download the team files first, then open the archive to check it.",
  "confirm.delete.check": "I copied the team files off this VM",
  "confirm.delete.button": "Delete VM",
  "download.busy": "Preparing the download of {vm}",
  "download.started": "The download started. Open the archive to check it before you delete the VM.",
  "download.skipped": "{count} entries are not in the archive (symlinks or special files).",
  "download.failed": "The download failed ({code}): {text}",
  "error.prefix": "The action failed ({code}): {text}"
} as const

export type TeamVmTextKey = keyof typeof en

const ja: Record<TeamVmTextKey, string> = {
  "card.title": "チーム VM",
  "card.loading": "読み込み中",
  "card.error.load": "チーム VM の状態を読み込めませんでした: {error}",
  "status.none": "未作成",
  "status.provisioning": "作成中",
  "status.starting": "起動中",
  "status.running": "実行中",
  "status.paused": "一時停止",
  "status.failed": "失敗",
  "field.vm": "VM",
  "field.epoch": "エポック",
  "badge.clean": "汚染なし",
  "badge.tainted": "汚染あり",
  "badge.accepted": "汚染あり (リスク承諾済み)",
  "taint.detail": "削除されたメンバーが、この VM の稼働中にチーム SSH 証明書を持っていました。メンバーは VM 上で root 権限 (sudo、docker) を持つため、cmux は VM がクリーンであることを証明できません。",
  "taint.blocked": "オーナーまたは管理者がリスクを承諾するか VM を再構築するまで、新しいチーム SSH 証明書はオーナーと管理者にのみ発行され、VM は再バインドできません。",
  "taint.users": "削除されたメンバー",
  "taint.since": "汚染: {when}",
  "taint.accepted": "{who} が {when} にリスクを承諾しました。メンバーは再び証明書を取得できます。",
  "taint.member_hint": "チームのオーナーまたは管理者に、リスクの承諾または VM の再構築を依頼してください。",
  "action.accept": "リスクを承諾",
  "action.rebuild": "スナップショットから再構築",
  "action.delete": "削除",
  "action.download": "ファイルをダウンロード",
  "action.cancel": "キャンセル",
  "rebuild.full": "先に退役した VM を削除してください。退役した VM は最大 3 台まで保持されます。",
  "confirm.accept.title": "リスクを承諾して、この VM を使い続けますか?",
  "confirm.accept.body": "削除されたメンバーが VM に変更を残した可能性があります。メンバーは再びチーム SSH 証明書を取得でき、VM は再バインドできます。この操作はチームの監査ログに記録されます。",
  "confirm.accept.button": "リスクを承諾",
  "confirm.rebuild.title": "ベーススナップショットからチーム VM を再構築しますか?",
  "confirm.rebuild.body": "cmux はベーススナップショットからエポック {epoch} の新しい VM を起動します。現在の VM は一時停止され、退役した VM として保持されます。",
  "confirm.rebuild.files": "/srv/team のチームファイルは新しい VM に引き継がれません。一時停止した古い VM に残ります。先にチームファイルをダウンロードしてください。再構築後、その VM を削除する前に、退役した VM の行からチームファイルをダウンロードしてください。",
  "confirm.rebuild.button": "スナップショットから再構築",
  "retired.title": "退役した VM",
  "retired.intro": "再構築すると古い VM は一時停止され、/srv/team のチームファイルとともに、オーナーまたは管理者が削除するまで保持されます。「ファイルをダウンロード」は VM を起動せずに /srv/team を .tar アーカイブとして保存します。",
  "retired.pausing": "一時停止中",
  "retired.paused": "一時停止",
  "retired.by": "{who} が {when} に再構築",
  "confirm.delete.title": "退役した VM {vm} を削除しますか?",
  "confirm.delete.body": "VM と、/srv/team のチームファイルを含むすべてのファイルを削除します。元に戻せません。",
  "confirm.download_first": "先にチームファイルをダウンロードし、アーカイブを開いて確認してください。",
  "confirm.delete.check": "この VM からチームファイルをコピーしました",
  "confirm.delete.button": "VM を削除",
  "download.busy": "{vm} のダウンロードを準備中",
  "download.started": "ダウンロードを開始しました。VM を削除する前に、アーカイブを開いて確認してください。",
  "download.skipped": "{count} 件の項目はアーカイブに含まれていません (シンボリックリンクまたは特殊ファイル)。",
  "download.failed": "ダウンロードに失敗しました ({code}): {text}",
  "error.prefix": "操作に失敗しました ({code}): {text}"
}

/** A localized sentence per error code the team VM admin ops answer; unknown codes get a generic text. */
const errorsEn: Record<string, string> = {
  "team_vm.retired_files_unconfirmed": "Confirm that you copied the team files off this VM before you delete it.",
  "team_vm.stale_taint": "The taint changed since this page loaded. Check the removed members again.",
  "team_vm.not_tainted": "This VM is no longer tainted.",
  "team_vm.stale_epoch": "The team VM changed since this page loaded, or a new VM is already being created.",
  "team_vm.retired_full": "Delete a retired VM first. cmux keeps at most 3 retired VMs.",
  "team_vm.in_use": "The VM is in use. Try again later.",
  "team_vm.not_configured": "Team VMs are not configured for this team.",
  "team_vm.plan_gate_missing": "The team plan does not include a team VM.",
  "selector.not_found": "This VM is no longer in the list.",
  "team_vm.retired_not_fenced": "This VM is still pausing. Try the download again in a few minutes.",
  "team_vm.export_too_large": "The team files are larger than 2 GiB or have more than 5000 entries, the download limit.",
  "team_vm.export_no_files": "This VM has no team files on /srv/team.",
  "team_vm.export_timeout": "Listing the team files took too long. Try again.",
  "team_vm.export_ticket_invalid": "The download link expired. Start the download again.",
  "team_vm.provider_failed": "The VM provider did not answer. Try again.",
  "team_vm.vm_missing": "The VM no longer exists at the provider.",
  "auth.forbidden": "Only team owners and admins can do this.",
  "auth.unauthenticated": "Sign in again.",
  "owner.unreachable": "cmux could not reach the team VM service. Try again.",
  unknown: "Something went wrong."
}

const errorsJa: Record<keyof typeof errorsEn, string> = {
  "team_vm.retired_files_unconfirmed": "削除する前に、この VM からチームファイルをコピーしたことを確認してください。",
  "team_vm.stale_taint": "このページの読み込み後に汚染の内容が変わりました。削除されたメンバーを再確認してください。",
  "team_vm.not_tainted": "この VM はもう汚染されていません。",
  "team_vm.stale_epoch": "このページの読み込み後にチーム VM が変わったか、新しい VM をすでに作成中です。",
  "team_vm.retired_full": "先に退役した VM を削除してください。退役した VM は最大 3 台まで保持されます。",
  "team_vm.in_use": "VM は使用中です。しばらくしてから再試行してください。",
  "team_vm.not_configured": "このチームではチーム VM が設定されていません。",
  "team_vm.plan_gate_missing": "チームのプランにチーム VM が含まれていません。",
  "selector.not_found": "この VM はもう一覧にありません。",
  "team_vm.retired_not_fenced": "この VM はまだ一時停止の処理中です。数分後にもう一度ダウンロードしてください。",
  "team_vm.export_too_large": "チームファイルがダウンロードの上限 (2 GiB または 5000 項目) を超えています。",
  "team_vm.export_no_files": "この VM の /srv/team にチームファイルがありません。",
  "team_vm.export_timeout": "チームファイルの一覧取得に時間がかかりすぎました。再試行してください。",
  "team_vm.export_ticket_invalid": "ダウンロードリンクの有効期限が切れました。もう一度ダウンロードを開始してください。",
  "team_vm.provider_failed": "VM プロバイダーが応答しませんでした。再試行してください。",
  "team_vm.vm_missing": "この VM はプロバイダーにもう存在しません。",
  "auth.forbidden": "この操作はチームのオーナーと管理者のみが実行できます。",
  "auth.unauthenticated": "もう一度サインインしてください。",
  "owner.unreachable": "cmux はチーム VM サービスに接続できませんでした。再試行してください。",
  unknown: "問題が発生しました。"
}

const CATALOG: Record<Locale, Record<TeamVmTextKey, string>> = { en, ja }
const ERRORS: Record<Locale, Record<string, string>> = { en: errorsEn, ja: errorsJa }

export const teamVmText = (locale: Locale, key: TeamVmTextKey, vars: Record<string, string> = {}): string =>
  CATALOG[locale][key].replace(/\{(\w+)\}/g, (m, name: string) => vars[name] ?? m)

export const teamVmErrorText = (locale: Locale, code: string): string => ERRORS[locale][code] ?? ERRORS[locale].unknown!
