import { expect, test } from "bun:test";
import styles from "../src/styles.css" with { type: "text" };

test("toolbar and files pane use theme surfaces", () => {
  expect(styles).toContain("--cmux-diff-chrome-bg: light-dark(");
  expect(styles).toContain("--cmux-diff-page-bg: light-dark(");
  expect(styles).toContain("--cmux-diff-accent: light-dark(#667489, #aeb8c5)");
  expect(styles).toContain("--cmux-diff-card-bg: light-dark(");
  expect(styles).toContain("--cmux-diff-card-header-bg: light-dark(");
  expect(styles).toContain("--cmux-diff-toolbar-bg: color-mix(in lab, var(--cmux-diff-chrome-bg) 94%, transparent)");
  expect(styles).toContain("--cmux-diff-sidebar-bg: color-mix(in lab, var(--cmux-diff-chrome-bg) 96%, transparent)");
  expect(styles).toMatch(/#toolbar\s*\{[^}]*border-bottom: 1px solid var\(--cmux-diff-border\)[^}]*background: var\(--cmux-diff-toolbar-bg\)/s);
  expect(styles).toMatch(/#toolbar\s*\{[^}]*backdrop-filter: saturate\(160%\) blur\(18px\);/s);
  expect(styles).toMatch(/#toolbar\s*\{[^}]*flex-direction: column;[^}]*padding: 0;/s);
  expect(styles).toMatch(/#review-tabs\s*\{[^}]*border-bottom: 1px solid var\(--cmux-diff-hairline\)/s);
  expect(styles).toMatch(/#toolbar-main\s*\{[^}]*padding: 4px 7px 5px 10px;/s);
  expect(styles).toMatch(/\.review-tab\[aria-selected="true"\]\s*\{[^}]*background: var\(--cmux-diff-card-bg\)/s);
  expect(styles).toMatch(/#files-sidebar\s*\{[^}]*background: var\(--cmux-diff-sidebar-bg\)/s);
  expect(styles).toMatch(/#files-sidebar\s*\{[^}]*backdrop-filter: saturate\(150%\) blur\(16px\);/s);
  expect(styles).toMatch(/#files-header\s*\{[^}]*border-bottom: 1px solid var\(--cmux-diff-hairline\)[^}]*background: var\(--cmux-diff-sidebar-bg\)/s);
  expect(styles).toMatch(/#file-list\s*\{[^}]*background: var\(--cmux-diff-sidebar-bg\)/s);
  expect(styles).toContain("--trees-bg-override: var(--cmux-diff-sidebar-bg)");
  expect(styles).toContain("--trees-selected-bg-override: color-mix(in lab, var(--cmux-diff-accent) 13%, var(--cmux-diff-control-bg))");
  expect(styles).toMatch(/\.toolbar-actions\s*\{[^}]*gap: 4px;/s);
  expect(styles).toMatch(/\.toolbar-icon\s*\{[^}]*width: 24px;[^}]*height: 24px;/s);
  expect(styles).toMatch(/\.toolbar-icon svg,\s*\.menu-item svg,\s*\.review-tab svg,[^{]*\{[^}]*width: 14px;[^}]*height: 14px;/s);
  expect(styles).toMatch(/\.toolbar-icon svg,\s*\.menu-item svg,\s*\.review-tab svg,[^{]*\{[^}]*stroke-width: 1;/s);
  expect(styles).toMatch(/#file-search-toggle svg\s*\{[^}]*stroke-width: 1;/s);
  expect(styles).toMatch(/#viewer diffs-container\s*\{[^}]*background: var\(--cmux-diff-card-bg\)[^}]*0 8px 22px var\(--cmux-diff-card-shadow\)/s);
  expect(styles).toMatch(/#viewer\s*\{[^}]*linear-gradient\(\s*180deg,/s);
  expect(styles).not.toContain("#source-detail");
  expect(styles).not.toContain("box-shadow: 0 -1px 0 var(--cmux-diff-border), 0 1px 0 var(--cmux-diff-border)");
});
