from __future__ import annotations

import json
import re
from collections.abc import Mapping
from pathlib import PurePosixPath
from typing import Any

from codegen.ir import SdkIR
from codegen.writer import Emitter


HEADER = """// This file is generated by cmux-tui/bindings/codegen. Do not edit by hand.\n// Source: cmux-tui/spec/sdk-schema.json\n"""

SWIFT_KEYWORDS = {
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func",
    "import", "init", "inout", "internal", "let", "open", "operator", "private",
    "precedencegroup", "protocol", "public", "rethrows", "static", "struct", "subscript",
    "typealias", "var", "break", "case", "continue", "default", "defer", "do", "else",
    "fallthrough", "for", "guard", "if", "in", "repeat", "return", "switch", "where",
    "while", "as", "Any", "catch", "false", "is", "nil", "super", "self", "Self", "throw",
    "throws", "true", "try", "associativity", "didSet", "get", "infix", "left", "mutating",
    "none", "nonmutating", "override", "postfix", "prefix", "right", "set", "willSet",
    "actor", "async", "await", "convenience", "dynamic", "final", "indirect", "lazy", "nonisolated",
    "required", "some", "unowned", "weak", "borrowing", "consuming", "sending",
}

SCALARS = {
    "string": "String",
    "boolean": "Bool",
    "int32": "Int32",
    "uint16": "UInt16",
    "uint32": "UInt32",
    "float32": "Float",
    "float64": "Double",
    "int64": "Int64",
    "uint64": "UInt64",
}


def plain(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(k): plain(v) for k, v in value.items()}
    if isinstance(value, (tuple, list)):
        return [plain(v) for v in value]
    return value


def pascal(value: str) -> str:
    pieces = [p for p in re.split(r"[^A-Za-z0-9]+", value) if p]
    result = "".join(p[:1].upper() + p[1:] for p in pieces)
    return result or "Value"


def camel(value: str) -> str:
    p = pascal(value)
    result = p[:1].lower() + p[1:]
    if result == "self":
        return "selfValue"
    return f"`{result}`" if result in SWIFT_KEYWORDS else result


def swift_case(value: str) -> str:
    result = camel(value).replace("`", "")
    if result and result[0].isdigit():
        result = "v" + result
    return f"`{result}`" if result in SWIFT_KEYWORDS else result


def quote(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False).replace("\\/", "/")


def literal_type(value: Any) -> str:
    if isinstance(value, bool):
        return "Bool"
    if isinstance(value, int):
        return "UInt64" if value >= 0 else "Int64"
    if isinstance(value, float):
        return "Double"
    return "String"


def literal_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    return quote(value)


def key_case(field: str) -> str:
    return swift_case(field)


class SwiftEmitter:
    def __init__(self, ir: SdkIR):
        self.ir = ir
        self.document = plain(ir.document)
        self.type_names: dict[str, str] = {}
        self.expressions: dict[str, Mapping[str, Any]] = {}
        self.tagged_variants: dict[str, list[tuple[str, str, Mapping[str, Any]]]] = {}
        self.untagged_variants: dict[str, list[tuple[str, str, Mapping[str, Any]]]] = {}
        self._collect()

    def _collect(self) -> None:
        used: set[str] = set()

        def unique(name: str) -> str:
            candidate = pascal(name)
            if candidate not in used:
                used.add(candidate)
                return candidate
            index = 2
            while f"{candidate}{index}" in used:
                index += 1
            result = f"{candidate}{index}"
            used.add(result)
            return result

        def visit(expr: Mapping[str, Any], name: str, path: str, *, skip_tag: str | None = None) -> str:
            kind = expr["kind"]
            if kind == "ref":
                return self.type_names.get(f"types/{expr['name']}", pascal(expr["name"]))
            if kind in {"scalar", "literal"}:
                return ""
            existing = self.type_names.get(path)
            if existing:
                return existing
            resolved = unique(name)
            self.type_names[path] = resolved
            self.expressions[path] = expr
            if kind == "object":
                for wire_name, field in expr["fields"].items():
                    if skip_tag and wire_name == skip_tag:
                        continue
                    visit(field["type"], resolved + pascal(wire_name), f"{path}/fields/{wire_name}/type")
            elif kind == "array":
                visit(expr["items"], resolved + "Item", f"{path}/items")
            elif kind == "map":
                visit(expr["values"], resolved + "Value", f"{path}/values")
            elif kind == "alias":
                visit(expr["target"], resolved + "Value", f"{path}/target")
            elif kind == "tagged_union":
                variants: list[tuple[str, str, Mapping[str, Any]]] = []
                for wire_variant, variant in expr["variants"].items():
                    variant_name = visit(variant, resolved + pascal(wire_variant), f"{path}/variants/{wire_variant}", skip_tag=expr["tag"])
                    variants.append((wire_variant, variant_name, variant))
                self.tagged_variants[path] = variants
            elif kind == "untagged_union":
                variants = []
                for index, variant in enumerate(expr["variants"], start=1):
                    variant_name = visit(variant, resolved + "Variant" + str(index), f"{path}/variants/{index - 1}")
                    variants.append((str(index), variant_name, variant))
                self.untagged_variants[path] = variants
            return resolved

        for name, expr in self.document["types"].items():
            if expr["kind"] == "alias":
                # Alias names are emitted explicitly and their target is visited for
                # nested anonymous objects without consuming the alias name twice.
                self.type_names[f"types/{name}"] = unique(name)
                self.expressions[f"types/{name}"] = expr
                visit(expr["target"], name + "Value", f"types/{name}/target")
            else:
                visit(expr, name, f"types/{name}")
        for wire_name, command in self.document["commands"].items():
            stem = pascal(wire_name)
            visit(command["request"], stem + "Request", f"commands/{wire_name}/request")
            visit(command["result"], stem + "Result", f"commands/{wire_name}/result")
        for wire_name, event in self.document["events"].items():
            visit(event["payload"], pascal(wire_name) + "Event", f"events/{wire_name}/payload")

    def type_name(self, expr: Mapping[str, Any], path: str | None = None) -> str:
        kind = expr["kind"]
        if kind == "scalar":
            return SCALARS[expr["name"]]
        if kind == "literal":
            return literal_type(expr["value"])
        if kind == "enum":
            if path is None:
                raise ValueError("enum path is required")
            return "CloudTuiGenerated." + self.type_names[path]
        if kind == "ref":
            return "CloudTuiGenerated." + self.type_names[f"types/{expr['name']}"]
        if kind in {"object", "tagged_union", "untagged_union"}:
            if path is None:
                raise ValueError(f"path is required for {kind}")
            return "CloudTuiGenerated." + self.type_names[path]
        if kind == "array":
            return "[" + self.type_name(expr["items"], (path or "") + "/items") + "]"
        if kind == "map":
            return "[String: " + self.type_name(expr["values"], (path or "") + "/values") + "]"
        if kind == "alias":
            return self.type_name(expr["target"], (path or "") + "/target")
        if kind == "opaque_json":
            return "CloudTuiGenerated.JSONValue"
        raise ValueError(f"unsupported Swift type expression: {kind}")

    def field_type(self, field: Mapping[str, Any], path: str) -> str:
        expr = field["type"]
        type_path = path + "/type"
        base = self.type_name(expr, type_path)
        if field["presence"] == "optional":
            return f"CloudTuiGenerated.OptionalField<{base}>"
        if field["nullable"]:
            return f"{base}?"
        return base

    def render(self) -> dict[str, str]:
        return {
            "CloudTuiGeneratedSupport.swift": self.render_support(),
            "CloudTuiGeneratedTypes.swift": self.render_types(),
            "CloudTuiGeneratedCommands.swift": self.render_commands(),
            "CloudTuiGeneratedEvents.swift": self.render_events(),
            "CloudTuiGeneratedMetadata.swift": self.render_metadata(),
        }

    def render_support(self) -> str:
        return HEADER + f"// Protocol {self.ir.mux_protocol}, IR {self.ir.ir_sha256}.\n\n" + r'''import Foundation

/// Namespace for the schema-generated cmux-tui Swift wire SDK.
enum CloudTuiGenerated {
    /// A JSON value used only for schema fields intentionally declared opaque.
    enum JSONValue: Codable, Sendable, Equatable {
        case null
        case bool(Bool)
        case number(Double)
        case string(String)
        case array([JSONValue])
        case object([String: JSONValue])

        init(from decoder: Decoder) throws {
            if let keyed = try? decoder.container(keyedBy: DynamicCodingKey.self) {
                var value: [String: JSONValue] = [:]
                for key in keyed.allKeys {
                    value[key.stringValue] = try keyed.decode(JSONValue.self, forKey: key)
                }
                self = .object(value)
                return
            }
            if var unkeyed = try? decoder.unkeyedContainer() {
                var value: [JSONValue] = []
                while !unkeyed.isAtEnd { value.append(try unkeyed.decode(JSONValue.self)) }
                self = .array(value)
                return
            }
            let single = try decoder.singleValueContainer()
            if single.decodeNil() { self = .null }
            else if let value = try? single.decode(Bool.self) { self = .bool(value) }
            else if let value = try? single.decode(Double.self) { self = .number(value) }
            else { self = .string(try single.decode(String.self)) }
        }

        func encode(to encoder: Encoder) throws {
            switch self {
            case .null:
                var single = encoder.singleValueContainer(); try single.encodeNil()
            case .bool(let value):
                var single = encoder.singleValueContainer(); try single.encode(value)
            case .number(let value):
                var single = encoder.singleValueContainer(); try single.encode(value)
            case .string(let value):
                var single = encoder.singleValueContainer(); try single.encode(value)
            case .array(let values):
                var unkeyed = encoder.unkeyedContainer(); for value in values { try unkeyed.encode(value) }
            case .object(let values):
                var keyed = encoder.container(keyedBy: DynamicCodingKey.self)
                for (key, value) in values { try keyed.encode(value, forKey: DynamicCodingKey(stringValue: key)) }
            }
        }
    }

    /// Preserves whether an optional schema field was omitted, null, or present.
    enum OptionalField<Value: Codable & Sendable & Equatable>: Codable, Sendable, Equatable {
        case missing
        case null
        case value(Value)

        init(from decoder: Decoder) throws {
            let single = try decoder.singleValueContainer()
            if single.decodeNil() { self = .null }
            else { self = .value(try Value(from: decoder)) }
        }

        func encode(to encoder: Encoder) throws {
            switch self {
            case .missing:
                var single = encoder.singleValueContainer(); try single.encodeNil()
            case .null:
                var single = encoder.singleValueContainer(); try single.encodeNil()
            case .value(let value):
                try value.encode(to: encoder)
            }
        }
    }

    struct DynamicCodingKey: CodingKey, Hashable, Sendable {
        let stringValue: String
        let intValue: Int?
        init(stringValue: String) { self.stringValue = stringValue; self.intValue = nil }
        init?(intValue: Int) { self.stringValue = String(intValue); self.intValue = intValue }
    }

    enum CodecError: Error, Equatable, Sendable {
        case missingRequiredField(String)
        case invalidLiteral(String)
        case unknownCommand(String)
        case unknownEvent(String)
    }

    static func encodeTagged<Payload: Encodable>(
        _ payload: Payload,
        tag: String,
        value: String,
        encoder: Encoder
    ) throws {
        let payloadData = try JSONEncoder().encode(payload)
        guard var object = try JSONSerialization.jsonObject(with: payloadData) as? [String: Any] else {
            throw CodecError.invalidLiteral("tagged payload was not an object")
        }
        object[tag] = value
        let data = try JSONSerialization.data(withJSONObject: object)
        try JSONDecoder().decode(JSONValue.self, from: data).encode(to: encoder)
    }

    static func encodeCommand<Payload: Encodable>(id: UInt64, command: String, payload: Payload) throws -> Data {
        let payloadData = try JSONEncoder().encode(payload)
        guard var object = try JSONSerialization.jsonObject(with: payloadData) as? [String: Any] else {
            throw CodecError.invalidLiteral("command payload was not an object")
        }
        object["id"] = id
        object["cmd"] = command
        return try JSONSerialization.data(withJSONObject: object) + Data([0x0A])
    }

    static func decodeJSONObject(_ data: Data) throws -> [String: Any] {
        guard let object = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw CodecError.invalidLiteral("wire message was not an object")
        }
        return object
    }
}
'''

    def _coding_key(self, wire_name: str) -> str:
        return wire_name

    def _literal_check(self, field: Mapping[str, Any], key: str, value_expr: str) -> list[str]:
        expr = field["type"]
        if expr["kind"] != "literal": return []
        literal = literal_value(expr["value"])
        return [f"        guard {value_expr} == {literal} else {{ throw CodecError.invalidLiteral({quote(key)}) }}"]

    def _emit_object(self, path: str, expr: Mapping[str, Any], name: str, *, skip_tag: str | None = None) -> list[str]:
        fields = [(wire, field) for wire, field in expr["fields"].items() if wire != skip_tag]
        lines = [f"    struct {name}: Codable, Sendable, Equatable {{"]
        for wire, field in fields:
            swift_name = camel(wire)
            field_path = f"{path}/fields/{wire}"
            lines.append(f"        let {swift_name}: {self.field_type(field, field_path)}")
        lines.append("")
        params = []
        assigns = []
        for wire, field in fields:
            swift_name = camel(wire)
            ft = self.field_type(field, f"{path}/fields/{wire}")
            default = " = .missing" if field["presence"] == "optional" else (" = " + literal_value(field["type"]["value"]) if field["type"]["kind"] == "literal" else "")
            params.append(f"{swift_name}: {ft}{default}")
            assigns.append(f"            self.{swift_name} = {swift_name}")
        lines.append(f"        init({', '.join(params)}) {{")
        lines.extend(assigns)
        lines.append("        }")
        lines.append("")
        if fields:
            lines.append("        enum CodingKeys: String, CodingKey {")
            for wire, _ in fields:
                lines.append(f"            case {camel(wire)} = {quote(wire)}")
            lines.append("        }")
            lines.append("")
        lines.append("        init(from decoder: Decoder) throws {")
        if fields:
            lines.append("            let container = try decoder.container(keyedBy: CodingKeys.self)")
        else:
            # Swift's synthesized empty Encodable shape fails with
            # `Top-level ... did not encode any values`. Open an empty keyed
            # container explicitly so command payloads such as `identify`
            # encode as `{}` while still accepting any empty JSON object.
            lines.append("            _ = try decoder.container(keyedBy: DynamicCodingKey.self)")
        for wire, field in fields:
            swift_name = camel(wire)
            ft = self.type_name(field["type"], f"{path}/fields/{wire}/type")
            key = f".{swift_name}"
            if field["presence"] == "optional":
                lines.append(f"            if !container.contains({key}) {{")
                lines.append(f"                self.{swift_name} = .missing")
                lines.append("            } else if try container.decodeNil(forKey: " + key + ") {")
                if field["nullable"]:
                    lines.append(f"                self.{swift_name} = .null")
                else:
                    lines.append(f"                throw CodecError.invalidLiteral({quote(wire)})")
                lines.append("            } else {")
                lines.append(f"                self.{swift_name} = .value(try container.decode({ft}.self, forKey: {key}))")
                lines.append("            }")
            else:
                if field["nullable"]:
                    lines.append(f"            guard container.contains({key}) else {{ throw CodecError.missingRequiredField({quote(wire)}) }}")
                    lines.append(f"            self.{swift_name} = try container.decodeIfPresent({ft}.self, forKey: {key})")
                else:
                    lines.append(f"            self.{swift_name} = try container.decode({ft}.self, forKey: {key})")
                lines.extend(self._literal_check(field, wire, f"self.{swift_name}"))
        lines.append("        }")
        lines.append("")
        lines.append("        func encode(to encoder: Encoder) throws {")
        if fields:
            lines.append("            var container = encoder.container(keyedBy: CodingKeys.self)")
        else:
            lines.append("            _ = encoder.container(keyedBy: DynamicCodingKey.self)")
        for wire, field in fields:
            swift_name = camel(wire)
            key = f".{swift_name}"
            if field["presence"] == "optional":
                lines.append(f"            switch {swift_name} {{")
                lines.append("            case .missing: break")
                if field["nullable"]:
                    lines.append(f"            case .null: try container.encodeNil(forKey: {key})")
                else:
                    lines.append(f"            case .null: throw CodecError.invalidLiteral({quote(wire)})")
                lines.append(f"            case .value(let value): try container.encode(value, forKey: {key})")
                lines.append("            }")
            else:
                lines.append(f"            try container.encode({swift_name}, forKey: {key})")
        lines.append("        }")
        lines.append("    }")
        return lines

    def _emit_enum(self, path: str, expr: Mapping[str, Any], name: str) -> list[str]:
        lines = [f"    enum {name}: String, Codable, Sendable, Equatable {{"]
        for value in expr["values"]:
            lines.append(f"        case {swift_case(str(value))} = {quote(value)}")
        lines.append("    }")
        return lines

    def _union_variant_type(self, path: str, variant_name: str, expr: Mapping[str, Any]) -> str:
        if expr["kind"] == "ref":
            return self.type_names[f"types/{expr['name']}"]
        return variant_name

    def _emit_tagged_union(self, path: str, expr: Mapping[str, Any], name: str) -> list[str]:
        variants = self.tagged_variants[path]
        lines: list[str] = []
        for wire_variant, variant_name, variant_expr in variants:
            if variant_expr["kind"] == "object":
                lines.extend(self._emit_object(f"{path}/variants/{wire_variant}", variant_expr, variant_name, skip_tag=expr["tag"]))
                lines.append("")
        lines.append(f"    indirect enum {name}: Codable, Sendable, Equatable {{")
        for wire_variant, variant_name, variant_expr in variants:
            associated = self._union_variant_type(path, variant_name, variant_expr)
            lines.append(f"        case {swift_case(wire_variant)}({associated})")
        lines.append("")
        lines.append("        init(from decoder: Decoder) throws {")
        lines.append("            let tag = try decoder.container(keyedBy: DynamicCodingKey.self)")
        lines.append(f"            let value = try tag.decode(String.self, forKey: DynamicCodingKey(stringValue: {quote(expr['tag'])}))")
        lines.append("            switch value {")
        for wire_variant, variant_name, _ in variants:
            lines.append(f"            case {quote(wire_variant)}: self = .{swift_case(wire_variant)}(try {variant_name}(from: decoder))")
        lines.append(f"            default: throw CodecError.invalidLiteral({quote(name + '.' + expr['tag'])})")
        lines.append("            }")
        lines.append("        }")
        lines.append("")
        lines.append("        func encode(to encoder: Encoder) throws {")
        lines.append("            switch self {")
        for wire_variant, _, _ in variants:
            lines.append(f"            case .{swift_case(wire_variant)}(let value): try CloudTuiGenerated.encodeTagged(value, tag: {quote(expr['tag'])}, value: {quote(wire_variant)}, encoder: encoder)")
        lines.append("            }")
        lines.append("        }")
        lines.append("    }")
        return lines

    def _emit_untagged_union(self, path: str, expr: Mapping[str, Any], name: str) -> list[str]:
        variants = self.untagged_variants[path]
        lines: list[str] = []
        for _, variant_name, variant_expr in variants:
            if variant_expr["kind"] == "object":
                lines.extend(self._emit_object(f"{path}/variants/{int(_)-1}", variant_expr, variant_name))
                lines.append("")
        lines.append(f"    indirect enum {name}: Codable, Sendable, Equatable {{")
        for _, variant_name, variant_expr in variants:
            associated = self._union_variant_type(path, variant_name, variant_expr)
            lines.append(f"        case {swift_case(variant_name)}({associated})")
        lines.append("")
        lines.append("        init(from decoder: Decoder) throws {")
        for _, variant_name, variant_expr in variants:
            associated = self._union_variant_type(path, variant_name, variant_expr)
            lines.append(f"            if let value = try? {associated}(from: decoder) {{ self = .{swift_case(variant_name)}(value); return }}")
        lines.append(f"            throw CodecError.invalidLiteral({quote(name)})")
        lines.append("        }")
        lines.append("")
        lines.append("        func encode(to encoder: Encoder) throws {")
        lines.append("            switch self {")
        for _, variant_name, _ in variants:
            lines.append(f"            case .{swift_case(variant_name)}(let value): try value.encode(to: encoder)")
        lines.append("            }")
        lines.append("        }")
        lines.append("    }")
        return lines

    def render_types(self) -> str:
        lines = [HEADER, f"// Protocol {self.ir.mux_protocol}, IR {self.ir.ir_sha256}.", "", "import Foundation", "", "extension CloudTuiGenerated {"]
        # Emit root aliases/enums/objects in deterministic registration order.
        for path, expr in self.expressions.items():
            name = self.type_names[path]
            kind = expr["kind"]
            parts = path.split("/")
            is_command_event_root = (
                len(parts) == 3
                and parts[0] in {"commands", "events"}
                and parts[2] in {"request", "result", "payload"}
            )
            if is_command_event_root or "/variants/" in path:
                # Command/event roots are emitted with their request/result/event files.
                # Union variants are emitted together with their union so recursive
                # types and shared names are defined exactly once.
                continue
            if kind == "alias":
                lines.append(f"    typealias {name} = {self.type_name(expr['target'], path + '/target')}")
            elif kind == "opaque_json":
                lines.append("    typealias JsonValue = JSONValue")
            elif kind == "object":
                lines.extend(self._emit_object(path, expr, name))
            elif kind == "array":
                lines.append(f"    typealias {name} = [{self.type_name(expr['items'], path + '/items')}]")
            elif kind == "map":
                lines.append(f"    typealias {name} = [String: {self.type_name(expr['values'], path + '/values')}]")
            elif kind == "enum":
                lines.extend(self._emit_enum(path, expr, name))
            elif kind == "tagged_union":
                lines.extend(self._emit_tagged_union(path, expr, name))
            elif kind == "untagged_union":
                lines.extend(self._emit_untagged_union(path, expr, name))
            lines.append("")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def render_commands(self) -> str:
        lines = [HEADER, f"// Protocol {self.ir.mux_protocol}, IR {self.ir.ir_sha256}.", "", "import Foundation", "", "extension CloudTuiGenerated {"]
        command_cases: list[tuple[str, str, Mapping[str, Any]]] = []
        for wire_name, command in self.document["commands"].items():
            path = f"commands/{wire_name}/request"
            request_name = self.type_names[path]
            expr = command["request"]
            if expr["kind"] == "object":
                lines.extend(self._emit_object(path, expr, request_name))
                lines.append("")
            command_cases.append((wire_name, request_name, command))
        lines.append("    enum Command: Sendable {")
        for wire_name, request_name, _ in command_cases:
            lines.append(f"        case {swift_case(wire_name)}(id: UInt64, request: {request_name})")
        lines.append("")
        lines.append("        var wireName: String {")
        lines.append("            switch self {")
        for wire_name, _, _ in command_cases:
            lines.append(f"            case .{swift_case(wire_name)}: return {quote(wire_name)}")
        lines.append("            }")
        lines.append("        }")
        lines.append("")
        lines.append("        func line() throws -> Data {")
        lines.append("            switch self {")
        for wire_name, _, _ in command_cases:
            lines.append(f"            case .{swift_case(wire_name)}(let id, let request): return try CloudTuiGenerated.encodeCommand(id: id, command: {quote(wire_name)}, payload: request)")
        lines.append("            }")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def render_events(self) -> str:
        lines = [HEADER, f"// Protocol {self.ir.mux_protocol}, IR {self.ir.ir_sha256}.", "", "import Foundation", "", "extension CloudTuiGenerated {"]
        events: list[tuple[str, str, Mapping[str, Any]]] = []
        for wire_name, event in self.document["events"].items():
            path = f"events/{wire_name}/payload"
            name = self.type_names[path]
            expr = event["payload"]
            if expr["kind"] == "object":
                lines.extend(self._emit_object(path, expr, name))
                lines.append("")
            events.append((wire_name, name, event))
        lines.append("    enum Event: Codable, Sendable, Equatable {")
        for wire_name, name, _ in events:
            lines.append(f"        case {swift_case(wire_name)}({name})")
        lines.append("        case unknown(JSONValue)")
        lines.append("")
        lines.append("        init(from decoder: Decoder) throws {")
        lines.append("            let object = try decoder.container(keyedBy: DynamicCodingKey.self)")
        lines.append("            let name = try object.decode(String.self, forKey: DynamicCodingKey(stringValue: \"event\"))")
        lines.append("            switch name {")
        for wire_name, name, _ in events:
            lines.append(f"            case {quote(wire_name)}: self = .{swift_case(wire_name)}(try {name}(from: decoder))")
        lines.append("            default: self = .unknown(try JSONValue(from: decoder))")
        lines.append("            }")
        lines.append("        }")
        lines.append("")
        lines.append("        func encode(to encoder: Encoder) throws {")
        lines.append("            switch self {")
        for wire_name, _, _ in events:
            lines.append(f"            case .{swift_case(wire_name)}(let value): try value.encode(to: encoder)")
        lines.append("            case .unknown(let value): try value.encode(to: encoder)")
        lines.append("            }")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def render_metadata(self) -> str:
        commands = self.document["commands"]
        events = self.document["events"]
        return HEADER + f"// Protocol {self.ir.mux_protocol}, IR {self.ir.ir_sha256}.\n\nimport Foundation\n\nextension CloudTuiGenerated {{\n    static let schemaVersion = {self.ir.schema_version}\n    static let protocolVersion = {self.ir.mux_protocol}\n    static let irSHA256 = {quote(self.ir.ir_sha256)}\n    static let commandNames: Set<String> = [{', '.join(quote(k) for k in commands)}]\n    static let eventNames: Set<String> = [{', '.join(quote(k) for k in events)}]\n}}\n"


def emit(ir: SdkIR) -> Mapping[str | PurePosixPath, str | bytes]:
    emitter = SwiftEmitter(ir)
    return emitter.render()


EMITTER = Emitter(
    language="swift",
    output_root=PurePosixPath("swift/generated"),
    render=emit,
)
