// GENERATED by scripts/cmux-next/gen-protected-folders.py from
// cmux-tui/crates/acpmux/data/protected-folders.json. Do not edit; edit the JSON and rerun.

/// One folder macOS guards with a privacy prompt (LAUNCH-NO-TCC-PROMPTS).
export interface ProtectedFolderEntry {
  readonly path: string;
  readonly kind: string;
}

/// The guarded folders inside the home folder, relative to it.
export const PROTECTED_IN_HOME: readonly ProtectedFolderEntry[] = [
  { path: "Desktop", kind: "desktop" },
  { path: "Documents", kind: "documents" },
  { path: "Downloads", kind: "downloads" },
  { path: "Pictures", kind: "pictures" },
  { path: "Music", kind: "music" },
  { path: "Movies", kind: "movies" },
  { path: "Library/Mobile Documents", kind: "iCloudDrive" },
  { path: "Library/CloudStorage", kind: "cloudStorage" },
  { path: "Library/Containers", kind: "appData" },
  { path: "Library/Group Containers", kind: "appData" },
  { path: "Library/Mail", kind: "appData" },
  { path: "Library/Messages", kind: "appData" },
  { path: "Library/Safari", kind: "appData" },
  { path: "Library/Calendars", kind: "appData" },
];

/// The guarded folders outside any home folder: other and network volumes.
export const PROTECTED_ROOTS: readonly ProtectedFolderEntry[] = [
  { path: "/Volumes", kind: "volumes" },
  { path: "/Network", kind: "network" },
  { path: "/net", kind: "network" },
];
