#!/usr/bin/env python3
"""Write the Swift and TypeScript copies of the protected-folder list (LAUNCH-NO-TCC-PROMPTS).

The one list is cmux-tui/crates/acpmux/data/protected-folders.json; acpmux reads it with
include_str!, scripts/cmux-next/launch-tcc-smoke.py reads it at run time, and this script writes
the copies the app's Swift modules and the webviews compile in.

    python3 scripts/cmux-next/gen-protected-folders.py           # write the copies
    python3 scripts/cmux-next/gen-protected-folders.py --check   # exit 1 when a copy drifted
"""
import json, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
SOURCE = "cmux-tui/crates/acpmux/data/protected-folders.json"
SWIFT_COPIES = [
    "Packages/macOS/CmuxNext/Sources/CmuxNextOnboarding/System/ProtectedFolderEntry.generated.swift",
    "Packages/macOS/CmuxNext/Sources/CmuxNextPalette/FolderPicker/ProtectedFolderEntry.generated.swift",
    "Packages/macOS/CmuxNext/Sources/CmuxNextSettings/ProtectedFolderEntry.generated.swift",
]
TS_COPY = "webviews/src/agent-session/acpmux/protectedFolders.generated.ts"
HEADER = "GENERATED by scripts/cmux-next/gen-protected-folders.py from\n{c} {src}. Do not edit; edit the JSON and rerun."


def load():
    with open(os.path.join(ROOT, SOURCE)) as handle:
        data = json.load(handle)
    for group in ("inHome", "roots"):
        for entry in data[group]:
            assert set(entry) == {"path", "kind"}, entry
            if group == "roots":
                assert entry["path"].startswith("/"), entry
            else:
                assert not entry["path"].startswith("/") and ".." not in entry["path"].split("/"), entry
    return data


def swift(data):
    def rows(group):
        return "\n".join('        ProtectedFolderEntry(path: %s, kind: %s),' % (json.dumps(e["path"]), json.dumps(e["kind"]))
                         for e in data[group])
    return """// {header}

/// One folder macOS guards with a privacy prompt (LAUNCH-NO-TCC-PROMPTS): a path relative to
/// the home folder (`inHome`) or an absolute one (`roots`), and its kind.
nonisolated struct ProtectedFolderEntry: Sendable, Equatable {{
    let path: String
    let kind: String

    /// The guarded folders inside the home folder.
    static let inHome: [ProtectedFolderEntry] = [
{home}
    ]

    /// The guarded folders outside any home folder: other and network volumes.
    static let roots: [ProtectedFolderEntry] = [
{roots}
    ]
}}
""".format(header=HEADER.format(c="//", src=SOURCE), home=rows("inHome"), roots=rows("roots"))


def typescript(data):
    def rows(group):
        return "\n".join('  { path: %s, kind: %s },' % (json.dumps(e["path"]), json.dumps(e["kind"])) for e in data[group])
    return """// {header}

/// One folder macOS guards with a privacy prompt (LAUNCH-NO-TCC-PROMPTS).
export interface ProtectedFolderEntry {{
  readonly path: string;
  readonly kind: string;
}}

/// The guarded folders inside the home folder, relative to it.
export const PROTECTED_IN_HOME: readonly ProtectedFolderEntry[] = [
{home}
];

/// The guarded folders outside any home folder: other and network volumes.
export const PROTECTED_ROOTS: readonly ProtectedFolderEntry[] = [
{roots}
];
""".format(header=HEADER.format(c="//", src=SOURCE), home=rows("inHome"), roots=rows("roots"))


def main():
    check = "--check" in sys.argv[1:]
    data = load()
    outputs = {path: swift(data) for path in SWIFT_COPIES}
    outputs[TS_COPY] = typescript(data)
    drifted = []
    for path, text in outputs.items():
        full = os.path.join(ROOT, path)
        current = open(full).read() if os.path.exists(full) else None
        if current == text:
            continue
        if check:
            drifted.append(path)
        else:
            with open(full, "w") as handle:
                handle.write(text)
            print("wrote " + path)
    if drifted:
        print("protected-folder copies differ from %s:\n  %s\nrun: python3 scripts/cmux-next/gen-protected-folders.py"
              % (SOURCE, "\n  ".join(drifted)), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
