// Code generated by cmux pane-protocol codegen. DO NOT EDIT.
// Generated from pane-protocol IR 0.1.0 (SHA-256 1956c86a86923440430fca7c6be1a406d4c0d7f045a6bb350ac710c46031f7a3).

package hellopane

import (
	"context"
	"encoding/json"

	pane "github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane"
)

// Client is a typed pane-protocol client on one connection. It validates
// params before sending and results and events after receiving.
type Client struct{ Conn *pane.Conn }

// NewClient wraps a serving *pane.Conn.
func NewClient(c *pane.Conn) *Client { return &Client{Conn: c} }

// CmuxClient calls ops in namespace cmux.
type CmuxClient struct{ conn *pane.Conn }

// Cmux returns the cmux namespace client.
func (c *Client) Cmux() CmuxClient { return CmuxClient{conn: c.Conn} }

// GitDiff calls cmux.git.diff (read, scope git:read; errors: cmux.git.not_a_repo, cmux.git.bad_ref).
func (c CmuxClient) GitDiff(ctx context.Context, params GitDiffParams) (GitDiff, error) {
	var zero GitDiff
	raw, err := pane.EncodeAndValidate(params, ValidateGitDiffParams, pane.CodeInvalidParams)
	if err != nil {
		return zero, err
	}
	value, err := c.conn.Call(ctx, OpCmuxGitDiff, raw)
	if err != nil {
		return zero, err
	}
	return pane.DecodeAndValidate[GitDiff](value, ValidateGitDiff, pane.CodeInvalidResult)
}

// GitStatus calls cmux.git.status (read, scope git:read; errors: cmux.git.not_a_repo).
func (c CmuxClient) GitStatus(ctx context.Context, params GitStatusParams) (GitStatus, error) {
	var zero GitStatus
	raw, err := pane.EncodeAndValidate(params, ValidateGitStatusParams, pane.CodeInvalidParams)
	if err != nil {
		return zero, err
	}
	value, err := c.conn.Call(ctx, OpCmuxGitStatus, raw)
	if err != nil {
		return zero, err
	}
	return pane.DecodeAndValidate[GitStatus](value, ValidateGitStatus, pane.CodeInvalidResult)
}

// SubscribeGitStatusChanged subscribes to cmux.git.status.changed (scope git:read).
func (c CmuxClient) SubscribeGitStatusChanged(ctx context.Context, filter json.RawMessage) (*pane.TypedSubscription[GitStatus], error) {
	sub, err := c.conn.Subscribe(ctx, EventCmuxGitStatusChanged, filter)
	if err != nil {
		return nil, err
	}
	return pane.NewTypedSubscription[GitStatus](sub, ValidateGitStatus), nil
}

// ComExampleHelloClient calls ops in namespace com.example.hello.
type ComExampleHelloClient struct{ conn *pane.Conn }

// ComExampleHello returns the com.example.hello namespace client.
func (c *Client) ComExampleHello() ComExampleHelloClient { return ComExampleHelloClient{conn: c.Conn} }

// GreetSay calls com.example.hello.greet.say (read, scope com.example.hello:use; errors: none).
func (c ComExampleHelloClient) GreetSay(ctx context.Context, params HelloParams) (HelloResult, error) {
	var zero HelloResult
	raw, err := pane.EncodeAndValidate(params, ValidateHelloParams, pane.CodeInvalidParams)
	if err != nil {
		return zero, err
	}
	value, err := c.conn.Call(ctx, OpComExampleHelloGreetSay, raw)
	if err != nil {
		return zero, err
	}
	return pane.DecodeAndValidate[HelloResult](value, ValidateHelloResult, pane.CodeInvalidResult)
}
