// Code generated by cmux pane-protocol codegen. DO NOT EDIT.
// Generated from pane-protocol IR 0.1.0 (SHA-256 1956c86a86923440430fca7c6be1a406d4c0d7f045a6bb350ac710c46031f7a3).

package hellopane

import (
	"context"
	"encoding/json"
	"fmt"

	pane "github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane"
)

// App is the app id that owns com.example.hello.
const App = "com.example.hello"

// NewProvider creates a provider for App that owns ProviderNamespaces. Register
// a handler for each namespace, then call Run.
func NewProvider() (*pane.Provider, error) {
	p, err := pane.NewProvider(App, ProviderNamespaces...)
	if err != nil {
		return nil, err
	}
	p.IRVersion, p.IRSHA256 = IRVersion, IRSHA256
	return p, nil
}

// ComExampleHelloHandler serves the ops of namespace com.example.hello. Params arrive validated;
// results are validated before they are sent. Return *pane.Error with a
// declared code for expected failures; any other error is logged and sent
// as cmux.internal.
type ComExampleHelloHandler interface {
	// GreetSay serves com.example.hello.greet.say (read, scope com.example.hello:use; errors: none).
	GreetSay(ctx context.Context, call *pane.Call, params HelloParams) (HelloResult, error)
}

// RegisterComExampleHello registers h for every op and event of com.example.hello.
func RegisterComExampleHello(p *pane.Provider, h ComExampleHelloHandler) error {
	if err := p.Register(pane.OpSpec{
		Name: OpComExampleHelloGreetSay, Kind: "read", Scope: "com.example.hello:use", Errors: nil,
		Handle: func(ctx context.Context, call *pane.Call, raw json.RawMessage) (json.RawMessage, error) {
			params, err := pane.DecodeAndValidate[HelloParams](raw, ValidateHelloParams, pane.CodeInvalidParams)
			if err != nil {
				return nil, err
			}
			result, err := h.GreetSay(ctx, call, params)
			if err != nil {
				return nil, err
			}
			out, err := pane.EncodeAndValidate(result, ValidateHelloResult, pane.CodeInvalidResult)
			if err != nil {
				return nil, fmt.Errorf("%s returned an invalid result: %v", OpComExampleHelloGreetSay, err)
			}
			return out, nil
		},
	}); err != nil {
		return err
	}
	return nil
}
