// Code generated by cmux pane-protocol codegen. DO NOT EDIT.
// Generated from pane-protocol IR 0.1.0 (SHA-256 1956c86a86923440430fca7c6be1a406d4c0d7f045a6bb350ac710c46031f7a3).

package hellopane

import pane "github.com/manaflow-ai/cmux/cmux-tui/bindings/go-pane"

// ValidateGitDiff checks a decoded JSON value (pane.DecodeValue)
// against types.GitDiff.
func ValidateGitDiff(v any) error { return validateGitDiff(v, "") }

func validateGitDiff(v any, path string) error {
	{
		o1, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o1, path, "files"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o1, path, "files"); err != nil {
			return err
		}
		if x2, ok := o1["files"]; ok {
			{
				a3, err := pane.AsArray(x2, pane.Field(path, "files"))
				if err != nil {
					return err
				}
				for i4, x5 := range a3 {
					if err := validateGitDiffFile(x5, pane.Index(pane.Field(path, "files"), i4)); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// ValidateGitDiffFile checks a decoded JSON value (pane.DecodeValue)
// against types.GitDiffFile.
func ValidateGitDiffFile(v any) error { return validateGitDiffFile(v, "") }

func validateGitDiffFile(v any, path string) error {
	{
		o6, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o6, path, "path", "additions", "deletions"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o6, path, "path", "additions", "deletions", "patch"); err != nil {
			return err
		}
		if x7, ok := o6["path"]; ok {
			if err := pane.CheckString(x7, pane.Field(path, "path")); err != nil {
				return err
			}
		}
		if x8, ok := o6["additions"]; ok {
			if err := pane.CheckInt(x8, pane.Field(path, "additions"), nil, nil); err != nil {
				return err
			}
		}
		if x9, ok := o6["deletions"]; ok {
			if err := pane.CheckInt(x9, pane.Field(path, "deletions"), nil, nil); err != nil {
				return err
			}
		}
		if x10, ok := o6["patch"]; ok {
			if x10 != nil {
				if err := pane.CheckString(x10, pane.Field(path, "patch")); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

// ValidateGitDiffParams checks a decoded JSON value (pane.DecodeValue)
// against types.GitDiffParams.
func ValidateGitDiffParams(v any) error { return validateGitDiffParams(v, "") }

func validateGitDiffParams(v any, path string) error {
	{
		o11, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o11, path, "cwd"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o11, path, "cwd", "base", "include_patch"); err != nil {
			return err
		}
		if x12, ok := o11["cwd"]; ok {
			if err := pane.CheckString(x12, pane.Field(path, "cwd")); err != nil {
				return err
			}
		}
		if x13, ok := o11["base"]; ok {
			if x13 != nil {
				if err := pane.CheckString(x13, pane.Field(path, "base")); err != nil {
					return err
				}
			}
		}
		if x14, ok := o11["include_patch"]; ok {
			if err := pane.CheckBool(x14, pane.Field(path, "include_patch")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateGitFileStatus checks a decoded JSON value (pane.DecodeValue)
// against types.GitFileStatus.
func ValidateGitFileStatus(v any) error { return validateGitFileStatus(v, "") }

func validateGitFileStatus(v any, path string) error {
	{
		o15, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o15, path, "path", "index", "worktree"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o15, path, "path", "index", "worktree"); err != nil {
			return err
		}
		if x16, ok := o15["path"]; ok {
			if err := pane.CheckString(x16, pane.Field(path, "path")); err != nil {
				return err
			}
		}
		if x17, ok := o15["index"]; ok {
			if err := pane.CheckString(x17, pane.Field(path, "index")); err != nil {
				return err
			}
		}
		if x18, ok := o15["worktree"]; ok {
			if err := pane.CheckString(x18, pane.Field(path, "worktree")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateGitStatus checks a decoded JSON value (pane.DecodeValue)
// against types.GitStatus.
func ValidateGitStatus(v any) error { return validateGitStatus(v, "") }

func validateGitStatus(v any, path string) error {
	{
		o19, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o19, path, "branch", "files"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o19, path, "branch", "files"); err != nil {
			return err
		}
		if x20, ok := o19["branch"]; ok {
			if x20 != nil {
				if err := pane.CheckString(x20, pane.Field(path, "branch")); err != nil {
					return err
				}
			}
		}
		if x21, ok := o19["files"]; ok {
			{
				a22, err := pane.AsArray(x21, pane.Field(path, "files"))
				if err != nil {
					return err
				}
				for i23, x24 := range a22 {
					if err := validateGitFileStatus(x24, pane.Index(pane.Field(path, "files"), i23)); err != nil {
						return err
					}
				}
			}
		}
	}
	return nil
}

// ValidateGitStatusParams checks a decoded JSON value (pane.DecodeValue)
// against types.GitStatusParams.
func ValidateGitStatusParams(v any) error { return validateGitStatusParams(v, "") }

func validateGitStatusParams(v any, path string) error {
	{
		o25, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o25, path, "cwd"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o25, path, "cwd"); err != nil {
			return err
		}
		if x26, ok := o25["cwd"]; ok {
			if err := pane.CheckString(x26, pane.Field(path, "cwd")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateHelloParams checks a decoded JSON value (pane.DecodeValue)
// against types.HelloParams.
func ValidateHelloParams(v any) error { return validateHelloParams(v, "") }

func validateHelloParams(v any, path string) error {
	{
		o27, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o27, path, "name"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o27, path, "name"); err != nil {
			return err
		}
		if x28, ok := o27["name"]; ok {
			if err := pane.CheckString(x28, pane.Field(path, "name")); err != nil {
				return err
			}
		}
	}
	return nil
}

// ValidateHelloResult checks a decoded JSON value (pane.DecodeValue)
// against types.HelloResult.
func ValidateHelloResult(v any) error { return validateHelloResult(v, "") }

func validateHelloResult(v any, path string) error {
	{
		o29, err := pane.AsObject(v, path)
		if err != nil {
			return err
		}
		if err := pane.RequireFields(o29, path, "message"); err != nil {
			return err
		}
		if err := pane.OnlyFields(o29, path, "message"); err != nil {
			return err
		}
		if x30, ok := o29["message"]; ok {
			if err := pane.CheckString(x30, pane.Field(path, "message")); err != nil {
				return err
			}
		}
	}
	return nil
}

// Validators maps each IR type name to its validator (for conformance vectors
// and dynamic checks).
var Validators = map[string]func(any) error{
	"GitDiff":         ValidateGitDiff,
	"GitDiffFile":     ValidateGitDiffFile,
	"GitDiffParams":   ValidateGitDiffParams,
	"GitFileStatus":   ValidateGitFileStatus,
	"GitStatus":       ValidateGitStatus,
	"GitStatusParams": ValidateGitStatusParams,
	"HelloParams":     ValidateHelloParams,
	"HelloResult":     ValidateHelloResult,
}
