public import CoreGraphics
public import Foundation

/// The cmux icon pack (Resources/cmux-icons.json, generated by
/// scripts/icons/build_pack.py): every icon's drawings on a square grid.
public nonisolated struct IconPack: Sendable, Decodable {
    public var id: String
    public var version: Int
    /// Side of the drawing grid in units (24).
    public var grid: CGFloat
    public var icons: [String: IconDrawing]

    public init(id: String = "cmux", version: Int = 1, grid: CGFloat = 24, icons: [String: IconDrawing]) {
        self.id = id
        self.version = version
        self.grid = grid
        self.icons = icons
    }

    public init(data: Data) throws {
        self = try JSONDecoder().decode(IconPack.self, from: data)
    }

    /// The pack shipped in this module's bundle, loaded once; empty when the
    /// bundle is missing or unreadable, so every icon falls back to SF Symbols.
    public static let bundled: IconPack = {
        guard let data = IconResources.json(named: "cmux-icons") else {
            return IconPack(icons: [:])
        }
        do {
            return try IconPack(data: data)
        } catch {
            IconResources.logger.error("cmux-icons.json did not decode: \(String(describing: error), privacy: .public)")
            return IconPack(icons: [:])
        }
    }()

    public func drawing(for name: IconName) -> IconDrawing? {
        icons[name.rawValue]
    }
}
