// Right-click placements of the catalog actions (plans/cmux-next/actions.md).
// Each row is (menu, group, rank[, style][, in: submenu anchor]). Menus list
// groups in `MenuGroup` order; a rank's hundreds are sections inside the
// group (rank / 100, truncated). An action declared with a `surfacePlan`
// in its descriptor keeps its own placements.

nonisolated extension ActionSurfaceCatalog {
    /// Every placement: windows to tabs here, screens to bookmarks in
    /// `ActionSurfaceCatalog+MenusContent.swift`.
    static let placements: [ActionID: [ContextMenuPlacement]] = layoutPlacements.merging(contentPlacements) { $0 + $1 }

    static let layoutPlacements: [ActionID: [ContextMenuPlacement]] = [
        "newTab": [p(.sidebarBackground, .create, 0)],
        "newBrowserWorkspace": [p(.sidebarBackground, .create, 3)],
        "openFolder": [p(.sidebarBackground, .create, 4)],
        "palette.openFolderInVSCodeInline": [p(.workspaceRow, .create, 100)],
        "reopenPreviousSession": [p(.sidebarBackground, .create, 8)],
        "reopenClosedWorkspace": [p(.sidebarBackground, .create, 7)],
        "moveWorkspaceUp": [p(.workspaceRow, .move, 200)],
        "moveWorkspaceDown": [p(.workspaceRow, .move, 201)],
        "palette.moveWorkspaceToTop": [p(.workspaceRow, .move, 202)],
        "moveWorkspaceToWindow": [p(.workspaceRow, .move, 204)],
        "moveWorkspaceToNewWindow": [p(.workspaceRow, .move, 205)],
        "renameWorkspace": [p(.workspaceRow, .identity, 100)],
        "palette.clearWorkspaceName": [p(.workspaceRow, .identity, 100)],
        "editWorkspaceDescription": [p(.workspaceRow, .identity, 101)],
        "palette.clearWorkspaceDescription": [p(.workspaceRow, .identity, 101)],
        "markWorkspaceDone": [p(.workspaceRow, .identity, 103)],
        "palette.workspaceStatus": [p(.workspaceRow, .identity, 102)],
        "palette.addWorkspaceChecklistItem": [p(.workspaceRow, .identity, 120)],
        "palette.openWorkspaceTodoPane": [p(.workspaceRow, .create, 101)],
        "closeWorkspace": [p(.workspaceRow, .close, 504)],
        "palette.closeOtherWorkspaces": [p(.workspaceRow, .close, 500)],
        "palette.closeWorkspacesBelow": [p(.workspaceRow, .close, 502)],
        "palette.closeWorkspacesAbove": [p(.workspaceRow, .close, 503)],
        "palette.toggleWorkspacePin": [p(.workspaceRow, .identity, 110)],
        "palette.markWorkspaceRead": [p(.workspaceRow, .identity, 111)],
        "palette.markWorkspaceUnread": [p(.workspaceRow, .identity, 112)],
        "palette.workspaceColor": [p(.workspaceRow, .identity, 104)],
        "palette.workspaceCustomColor": [p(.workspaceRow, .identity, 105)],
        "palette.resetWorkspaceColor": [p(.workspaceRow, .identity, 105)],
        "reconnectWorkspace": [p(.workspaceRow, .connection, 401)],
        "disconnectWorkspace": [p(.workspaceRow, .connection, 402)],
        "copyWorkspaceSSHError": [p(.workspaceRow, .inspect, 408)],
        "clearWorkspaceNotifications": [p(.workspaceRow, .identity, 114)],
        "revealWorkspaceInFinder": [p(.workspaceRow, .inspect, 403)],
        "palette.copyWorkspaceID": [p(.workspaceRow, .inspect, 405)],
        "palette.copyWorkspaceIDAndRef": [p(.workspaceRow, .inspect, 407)],
        "palette.copyWorkspaceLink": [p(.workspaceRow, .inspect, 406)],
        "workspaceGroup.newWorkspace": [p(.workspaceGroup, .create, 0)],
        "workspaceGroup.rename": [p(.workspaceGroup, .identity, 1)],
        "workspaceGroup.togglePin": [p(.workspaceGroup, .identity, 3)],
        "workspaceGroup.markRead": [p(.workspaceGroup, .identity, 100)],
        "workspaceGroup.markUnread": [p(.workspaceGroup, .identity, 101)],
        "workspaceGroup.clearNotifications": [p(.workspaceGroup, .identity, 102)],
        "workspaceGroup.ungroup": [p(.workspaceGroup, .close, 500)],
        "workspaceGroup.delete": [p(.workspaceGroup, .close, 502)],
        "workspaceGroup.editConfig": [p(.workspaceGroup, .inspect, 400)],
        "saveLayoutTemplate": [p(.workspaceRow, .organize, 210)],
        "palette.layout.open": [p(.workspaceRow, .create, 102)],
        "palette.openWorkspacePullRequests": [p(.workspaceRow, .inspect, 409)],
        "workspace.newAbove": [p(.workspaceRow, .create, 0)],
        "workspace.newBelow": [p(.workspaceRow, .create, 1)],
        "workspace.newAtTop": [p(.sidebarBackground, .create, 1)],
        "workspace.newAtBottom": [p(.sidebarBackground, .create, 1)],
        "workspace.newInGroup": [p(.workspaceRow, .create, 2)],
        "workspace.newInNewGroup": [p(.workspaceRow, .create, 3)],
        "workspace.newOnMachine": [p(.sidebarBackground, .create, 2)],
        "workspace.newInSameDirectory": [p(.workspaceRow, .create, 3)],
        "workspace.duplicate": [p(.workspaceRow, .create, 4)],
        "workspace.duplicateTerminalsOnly": [p(.workspaceRow, .create, 5)],
        "workspace.setIcon": [p(.workspaceRow, .identity, 106)],
        "workspace.clearIcon": [p(.workspaceRow, .identity, 107)],
        "workspace.moveToBottom": [p(.workspaceRow, .move, 203)],
        "workspace.moveToNewGroup": [p(.workspaceRow, .organize, 207)],
        "workspace.closeOthersInGroup": [p(.workspaceRow, .close, 501)],
        "workspace.sortByName": [p(.sidebarBackground, .move, 100)],
        "workspace.sortByLastUsed": [p(.sidebarBackground, .move, 101)],
        "workspace.sortByDirectory": [p(.sidebarBackground, .move, 102)],
        "workspaceGroup.collapseAll": [p(.workspaceGroup, .organize, 5), p(.sidebarBackground, .organize, 103)],
        "workspaceGroup.expandAll": [p(.workspaceGroup, .organize, 6), p(.sidebarBackground, .organize, 104)],
        "workspace.copyPath": [p(.workspaceRow, .inspect, 404)],
        "workspace.mergeInto": [p(.workspaceRow, .move, 211)],
        "pane.moveToNewWorkspace": [p(.pane, .move, 300)],
        "newWorkspaceGroup": [p(.sidebarBackground, .create, 5)],
        "groupSelectedWorkspaces": [p(.workspaceRow, .organize, 205)],
        "toggleFocusedWorkspaceGroupCollapsed": [p(.workspaceGroup, .organize, 4)],
        "moveWorkspaceToGroup": [p(.workspaceRow, .organize, 206)],
        "removeWorkspaceFromGroup": [p(.workspaceRow, .organize, 208)],
        "workspaceGroup.setColor": [p(.workspaceGroup, .identity, 2, .submenu)],
        "workspaceGroup.moveUp": [p(.workspaceGroup, .move, 300)],
        "workspaceGroup.moveDown": [p(.workspaceGroup, .move, 301)],
        "workspaceGroup.moveToWindow": [p(.workspaceGroup, .move, 303)],
        "workspaceGroup.closeWorkspaces": [p(.workspaceGroup, .close, 501)],
        "workspaceGroup.moveToNewWindow": [p(.workspaceGroup, .move, 302)],
        "workspaceGroup.color.grey": [p(.workspaceGroup, .identity, 0, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.blue": [p(.workspaceGroup, .identity, 1, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.red": [p(.workspaceGroup, .identity, 2, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.yellow": [p(.workspaceGroup, .identity, 3, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.green": [p(.workspaceGroup, .identity, 4, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.pink": [p(.workspaceGroup, .identity, 5, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.purple": [p(.workspaceGroup, .identity, 6, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.cyan": [p(.workspaceGroup, .identity, 7, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.orange": [p(.workspaceGroup, .identity, 8, in: "workspaceGroup.setColor")],
        "room.new": [p(.sidebarBackground, .create, 6), p(.profile, .create, 300)],
        "room.newWindow": [p(.profile, .create, 0)],
        "room.newWorkspace": [p(.profile, .create, 1)],
        "room.rename": [p(.profile, .identity, 100)],
        "room.setColor": [p(.profile, .identity, 101, .submenu)],
        "room.color.grey": [p(.profile, .identity, 0, in: "room.setColor")],
        "room.color.blue": [p(.profile, .identity, 1, in: "room.setColor")],
        "room.color.red": [p(.profile, .identity, 2, in: "room.setColor")],
        "room.color.yellow": [p(.profile, .identity, 3, in: "room.setColor")],
        "room.color.green": [p(.profile, .identity, 4, in: "room.setColor")],
        "room.color.pink": [p(.profile, .identity, 5, in: "room.setColor")],
        "room.color.purple": [p(.profile, .identity, 6, in: "room.setColor")],
        "room.color.cyan": [p(.profile, .identity, 7, in: "room.setColor")],
        "room.color.orange": [p(.profile, .identity, 8, in: "room.setColor")],
        "room.clearColor": [p(.profile, .identity, 100, in: "room.setColor")],
        "room.setIcon": [p(.profile, .identity, 102)],
        "room.clearIcon": [p(.profile, .identity, 103)],
        "room.setDefaults": [p(.profile, .identity, 106)],
        "room.delete": [p(.profile, .close, 400)],
        "room.moveLeft": [p(.profile, .move, 200)],
        "room.moveRight": [p(.profile, .move, 201)],
        "workspace.moveToRoom": [p(.workspaceRow, .move, 209)],
        "workspace.duplicateToRoom": [p(.workspaceRow, .move, 210)],
        "workspaceGroup.moveToRoom": [p(.workspaceGroup, .move, 304)],
        "room.setTheme": [p(.profile, .identity, 104, .choices)],
        "room.clearTheme": [p(.profile, .identity, 105)],
        "workspace.setTheme": [p(.workspaceRow, .identity, 108, .choices)],
        "workspace.clearTheme": [p(.workspaceRow, .identity, 109)],
        "terminal.setTheme": [p(.tab, .identity, 205, .choices)],
        "terminal.clearTheme": [p(.tab, .identity, 206)],
        "splitRight": [p(.pane, .create, 0), p(.terminalSelection, .create, 100)],
        "newColumn": [p(.pane, .create, 4)],
        "splitDown": [p(.pane, .create, 1), p(.terminalSelection, .create, 101)],
        "newPaneAutoLayout": [p(.pane, .create, 8)],
        "toggleSplitZoom": [p(.pane, .layout, 100), p(.terminalSelection, .layout, 104)],
        "equalizeSplits": [p(.pane, .layout, 101)],
        "triggerFlash": [p(.pane, .inspect, 500)],
        "palette.swapWithSession": [p(.pane, .connection, 200)],
        "toggleCanvasLayout": [p(.pane, .layout, 102)],
        "palette.newSimulatorPane": [p(.newTab, .create, 100)],
        "newTab.sameKind": [p(.tab, .create, -1)],
        "newSurface": [p(.tab, .create, 0), p(.newTab, .create, 0)],
        "openBrowser.webkit": [p(.tab, .create, 1), p(.newTab, .create, 1)],
        "openBrowser.chromium": [p(.tab, .create, 2), p(.newTab, .create, 2)],
        "closeTab": [p(.tab, .close, 604)],
        "closeOtherTabsInPane": [p(.tab, .close, 603)],
        "closeTabsToLeft": [p(.tab, .close, 601)],
        "closeTabsToRight": [p(.tab, .close, 602)],
        "renameTab": [p(.tab, .identity, 200)],
        "palette.clearTabName": [p(.tab, .identity, 201)],
        "moveSurfaceLeft": [p(.tab, .move, 409)],
        "moveSurfaceRight": [p(.tab, .move, 410)],
        "moveSurfaceToPreviousPane": [p(.tab, .move, 411)],
        "moveSurfaceToNextPane": [p(.tab, .move, 412)],
        "moveSurfaceToPaneLeft": [p(.tab, .move, 400)],
        "moveSurfaceToPaneRight": [p(.tab, .move, 401)],
        "moveSurfaceToPaneUp": [p(.tab, .move, 402)],
        "moveSurfaceToPaneDown": [p(.tab, .move, 403)],
        "palette.moveTabToNewWorkspace": [p(.tab, .move, 406)],
        "palette.toggleTabPin": [p(.tab, .identity, 202)],
        "palette.toggleTabUnread": [p(.tab, .identity, 203)],
        "palette.toggleFullWidthTab": [p(.tab, .layout, 408)],
        "duplicateTab": [p(.tab, .create, 3)],
        "reloadTab": [p(.tab, .create, 4)],
        "toggleTabAudioMute": [p(.tab, .identity, 204)],
        "disconnectRemoteTab": [p(.tab, .connection, 2)],
        "palette.copyIdentifiers": [p(.tab, .inspect, 503)],
        "palette.copyPaneID": [p(.pane, .inspect, 500), p(.tab, .inspect, 504)],
        "palette.copyPaneLink": [p(.pane, .inspect, 501), p(.tab, .inspect, 505)],
        "palette.copySurfaceID": [p(.tab, .inspect, 501)],
        "palette.copySurfaceLink": [p(.tab, .inspect, 502)],
        "tab.showResources": [p(.tab, .inspect, 500)],
        "workspace.showResources": [p(.workspaceRow, .inspect, 400)],
        "tabGroup.create": [p(.tab, .organize, 300)],
        "tabGroup.addTab": [p(.tab, .organize, 301)],
        "tabGroup.removeTab": [p(.tab, .organize, 302)],
        "tabGroup.rename": [p(.tabGroup, .identity, 1)],
        "tabGroup.setColor": [p(.tabGroup, .identity, 2, .submenu)],
        "tabGroup.toggleCollapsed": [p(.tabGroup, .organize, 3)],
        "tabGroup.ungroup": [p(.tabGroup, .close, 300)],
        "tabGroup.close": [p(.tabGroup, .close, 301)],
        "tabGroup.moveToNewSplit": [p(.tabGroup, .move, 202)],
        "tabGroup.moveToNewColumn": [p(.tabGroup, .move, 203)],
        "tabGroup.moveToNewWorkspace": [p(.tabGroup, .move, 204)],
        "tabGroup.moveToWorkspace": [p(.tabGroup, .move, 205)],
        "tabGroup.moveToNewWindow": [p(.tabGroup, .move, 206)],
        "tabGroup.newTab": [p(.tabGroup, .create, 0)],
        "tabGroup.save": [p(.tabGroup, .organize, 100)],
        "tabGroup.unsave": [p(.tabGroup, .organize, 101)],
        "tabGroup.color.grey": [p(.tabGroup, .identity, 0, in: "tabGroup.setColor")],
        "tabGroup.color.blue": [p(.tabGroup, .identity, 1, in: "tabGroup.setColor")],
        "tabGroup.color.red": [p(.tabGroup, .identity, 2, in: "tabGroup.setColor")],
        "tabGroup.color.yellow": [p(.tabGroup, .identity, 3, in: "tabGroup.setColor")],
        "tabGroup.color.green": [p(.tabGroup, .identity, 4, in: "tabGroup.setColor")],
        "tabGroup.color.pink": [p(.tabGroup, .identity, 5, in: "tabGroup.setColor")],
        "tabGroup.color.purple": [p(.tabGroup, .identity, 6, in: "tabGroup.setColor")],
        "tabGroup.color.cyan": [p(.tabGroup, .identity, 7, in: "tabGroup.setColor")],
        "tabGroup.color.orange": [p(.tabGroup, .identity, 8, in: "tabGroup.setColor")],
    ]
}
