// Right-click placements, screens to bookmarks (see ActionSurfaceCatalog+Menus.swift).

nonisolated extension ActionSurfaceCatalog {
    static let contentPlacements: [ActionID: [ContextMenuPlacement]] = [
        "screen.new": [p(.screen, .create, 0), p(.screenBar, .create, 0)],
        "screen.newWith": [p(.screenBar, .create, 1), p(.screen, .create, 2)],
        "screen.duplicate": [p(.screen, .create, 1)],
        "screen.close": [p(.screen, .close, 400)],
        "screen.closeOthers": [p(.screen, .close, 401)],
        "screen.closeToRight": [p(.screen, .close, 402)],
        "screen.closeToLeft": [p(.screen, .close, 403)],
        "screen.reopenClosed": [p(.screenBar, .create, 2)],
        "screen.rename": [p(.screen, .identity, 100)],
        "screen.clearName": [p(.screen, .identity, 100)],
        "screen.setColor": [p(.screen, .identity, 101, .submenu)],
        "screen.clearColor": [p(.screen, .identity, 9, in: "screen.setColor")],
        "screen.setIcon": [p(.screen, .identity, 102)],
        "screen.clearIcon": [p(.screen, .identity, 103)],
        "screen.togglePin": [p(.screen, .identity, 104)],
        "screen.color.grey": [p(.screen, .identity, 0, in: "screen.setColor")],
        "screen.color.blue": [p(.screen, .identity, 1, in: "screen.setColor")],
        "screen.color.red": [p(.screen, .identity, 2, in: "screen.setColor")],
        "screen.color.yellow": [p(.screen, .identity, 3, in: "screen.setColor")],
        "screen.color.green": [p(.screen, .identity, 4, in: "screen.setColor")],
        "screen.color.pink": [p(.screen, .identity, 5, in: "screen.setColor")],
        "screen.color.purple": [p(.screen, .identity, 6, in: "screen.setColor")],
        "screen.color.cyan": [p(.screen, .identity, 7, in: "screen.setColor")],
        "screen.color.orange": [p(.screen, .identity, 8, in: "screen.setColor")],
        "screen.moveLeft": [p(.screen, .move, 300)],
        "screen.moveRight": [p(.screen, .move, 301)],
        "screen.moveToWorkspace": [p(.screen, .move, 302)],
        "screen.moveToNewWorkspace": [p(.screen, .move, 303)],
        "screen.moveToNewWindow": [p(.screen, .move, 304)],
        "screenGroup.create": [p(.screen, .organize, 200)],
        "screenGroup.addScreen": [p(.screen, .organize, 201)],
        "screenGroup.removeScreen": [p(.screen, .organize, 202)],
        "screenGroup.newScreen": [p(.screenGroup, .create, 0)],
        "screenGroup.rename": [p(.screenGroup, .identity, 1)],
        "screenGroup.setColor": [p(.screenGroup, .identity, 2, .submenu)],
        "screenGroup.toggleCollapsed": [p(.screenGroup, .organize, 3)],
        "screenGroup.ungroup": [p(.screenGroup, .close, 300)],
        "screenGroup.close": [p(.screenGroup, .close, 301)],
        "screenGroup.moveLeft": [p(.screenGroup, .move, 200)],
        "screenGroup.moveRight": [p(.screenGroup, .move, 201)],
        "screenGroup.moveToWorkspace": [p(.screenGroup, .move, 202)],
        "screenGroup.moveToNewWorkspace": [p(.screenGroup, .move, 203)],
        "screenGroup.moveToNewWindow": [p(.screenGroup, .move, 204)],
        "screenGroup.save": [p(.screenGroup, .organize, 100)],
        "screenGroup.unsave": [p(.screenGroup, .organize, 101)],
        "screenGroup.color.grey": [p(.screenGroup, .identity, 0, in: "screenGroup.setColor")],
        "screenGroup.color.blue": [p(.screenGroup, .identity, 1, in: "screenGroup.setColor")],
        "screenGroup.color.red": [p(.screenGroup, .identity, 2, in: "screenGroup.setColor")],
        "screenGroup.color.yellow": [p(.screenGroup, .identity, 3, in: "screenGroup.setColor")],
        "screenGroup.color.green": [p(.screenGroup, .identity, 4, in: "screenGroup.setColor")],
        "screenGroup.color.pink": [p(.screenGroup, .identity, 5, in: "screenGroup.setColor")],
        "screenGroup.color.purple": [p(.screenGroup, .identity, 6, in: "screenGroup.setColor")],
        "screenGroup.color.cyan": [p(.screenGroup, .identity, 7, in: "screenGroup.setColor")],
        "screenGroup.color.orange": [p(.screenGroup, .identity, 8, in: "screenGroup.setColor")],
        "terminal.keep": [p(.tab, .identity, 210)],
        "clearScreenKeepScrollback": [p(.terminalSelection, .reset, 300)],
        "useSelectionForFind": [p(.terminalSelection, .edit, 3)],
        "terminalCopy": [p(.terminalSelection, .edit, 0)],
        "terminalPaste": [p(.terminalSelection, .edit, 1)],
        "resetTerminal": [p(.terminalSelection, .reset, 301)],
        "reconnectPane": [p(.pane, .connection, 201)],
        "palette.terminalOpenDirectory": [p(.terminalSelection, .inspect, 0)],
        "browserBack": [p(.browserPage, .navigate, 0)],
        "browserForward": [p(.browserPage, .navigate, 1)],
        "browserReload": [p(.browserPage, .navigate, 2)],
        "browserHardReload": [p(.browserPage, .navigate, 3)],
        "browser.openInChromium": [p(.tab, .reopen, 100)],
        "browser.openInWebKit": [p(.tab, .reopen, 101)],
        "toggleBrowserDeveloperTools": [p(.browserPage, .inspect, 201)],
        "showBrowserJavaScriptConsole": [p(.browserPage, .inspect, 202)],
        "inspectBrowserElement": [p(.browserPage, .inspect, 203)],
        "toggleBrowserFocusMode": [p(.browserPage, .view, 0)],
        "toggleBrowserDesignMode": [p(.browserPage, .view, 1)],
        "splitBrowserRight": [p(.pane, .create, 5)],
        "splitBrowserDown": [p(.pane, .create, 6)],
        "palette.browserOpenDefault": [p(.browserPage, .inspect, 101)],
        "browserScreenshotPage": [p(.browserPage, .inspect, 102)],
        "browserScreenshotSection": [p(.browserPage, .inspect, 103)],
        "browserTheme": [p(.browserPage, .identity, 0, .choices)],
        "browser.pageInfo": [p(.browserPage, .inspect, 200, .submenu), p(.browserPage, .inspect, 0, in: "browser.pageInfo")],
        "browser.pageInfo.connection": [p(.browserPage, .inspect, 1, in: "browser.pageInfo")],
        "browser.pageInfo.certificate": [p(.browserPage, .inspect, 2, in: "browser.pageInfo")],
        "browser.pageInfo.cookies": [p(.browserPage, .inspect, 200, in: "browser.pageInfo")],
        "browser.pageInfo.manageSiteData": [p(.browserPage, .inspect, 201, in: "browser.pageInfo")],
        "browser.pageInfo.deleteSiteData": [p(.browserPage, .inspect, 202, in: "browser.pageInfo")],
        "browser.pageInfo.setPermission": [p(.browserPage, .inspect, 100, in: "browser.pageInfo")],
        "browser.pageInfo.resetPermissions": [p(.browserPage, .inspect, 101, in: "browser.pageInfo")],
        "browser.pageInfo.siteSettings": [p(.browserPage, .inspect, 300, in: "browser.pageInfo")],
        "browser.pageInfo.aboutThisPage": [p(.browserPage, .inspect, 301, in: "browser.pageInfo")],
        "browser.extensions.menu": [p(.browserPage, .inspect, 300)],
        "browser.extensions.manage": [p(.browserPage, .inspect, 301)],
        "browser.extensions.webStore": [p(.browserPage, .inspect, 302)],
        "browser.extensions.loadUnpacked": [p(.browserPage, .inspect, 303)],
        "browserProfile.new": [p(.browserProfile, .create, 300)],
        "browserProfile.rename": [p(.browserProfile, .identity, 100)],
        "browserProfile.setColor": [p(.browserProfile, .identity, 101)],
        "browserProfile.clearColor": [p(.browserProfile, .identity, 102)],
        "browserProfile.setIcon": [p(.browserProfile, .identity, 103)],
        "browserProfile.clearIcon": [p(.browserProfile, .identity, 104)],
        "browserProfile.delete": [p(.browserProfile, .close, 400)],
        "browserProfile.newTab": [p(.newTab, .create, 3), p(.browserProfile, .create, 0)],
        "browserProfile.newWindow": [p(.browserProfile, .create, 1)],
        "browserProfile.newWorkspace": [p(.browserProfile, .create, 2)],
        "browserProfile.setWorkspaceDefault": [p(.workspaceRow, .identity, 300)],
        "browserProfile.clearWorkspaceDefault": [p(.workspaceRow, .identity, 301)],
        "browserProfile.setRoomDefault": [p(.profile, .identity, 107)],
        "browserProfile.clearRoomDefault": [p(.profile, .identity, 108)],
        "browserProfile.moveTab": [p(.tab, .reopen, 102)],
        "browserProfile.duplicateTab": [p(.tab, .reopen, 103)],
        "browserProfile.manageExtensions": [p(.browserProfile, .inspect, 200)],
        "toggleSidebar": [p(.sidebarBackground, .view, 300)],
        "notificationOpen": [p(.notification, .navigate, 0)],
        "notificationCopy": [p(.notification, .inspect, 0)],
        "notificationToggleRead": [p(.notification, .identity, 0)],
        "notificationDismiss": [p(.notification, .close, 0)],
        "notifications.toggleWorkspaceMute": [p(.workspaceRow, .identity, 113)],
        "palette.newAgentChat": [p(.newTab, .create, 4)],
        "newTab.page": [p(.newTab, .create, 5)],
        "palette.forkAgentConversationRight": [p(.terminalSelection, .create, 200)],
        "palette.forkAgentConversationLeft": [p(.terminalSelection, .create, 202)],
        "palette.forkAgentConversationTop": [p(.terminalSelection, .create, 203)],
        "palette.forkAgentConversationBottom": [p(.terminalSelection, .create, 204)],
        "palette.forkAgentConversationNewTab": [p(.terminalSelection, .create, 201)],
        "palette.forkAgentConversationNewWorkspace": [p(.terminalSelection, .create, 205)],
        "newCloudWorkspace": [p(.sidebarBackground, .create, 200)],
        "palette.cloud.fork": [p(.cloudMachine, .connection, 203)],
        "palette.cloud.snapshot": [p(.cloudMachine, .connection, 202)],
        "palette.cloud.restore": [p(.cloudMachine, .connection, 207)],
        "palette.cloud.promoteTemplate": [p(.cloudMachine, .connection, 206)],
        "palette.cloud.status": [p(.cloudMachine, .connection, 201)],
        "palette.cloud.ports": [p(.cloudMachine, .connection, 205)],
        "palette.cloud.tools": [p(.cloudMachine, .inspect, 103)],
        "palette.cloud.handoff": [p(.cloudMachine, .connection, 204)],
        "cloudNewTerminal": [p(.cloudMachine, .create, 0)],
        "cloudOpenMachine": [p(.cloudMachine, .create, 1)],
        "cloudRenameMachine": [p(.cloudMachine, .identity, 2)],
        "cloudKillMachine": [p(.cloudMachine, .close, 300)],
        "cloudCopyLink": [p(.cloudMachine, .inspect, 101)],
        "cloudCopyPort": [p(.cloudMachine, .inspect, 102)],
        "cloudCopyMachineID": [p(.cloudMachine, .inspect, 100)],
        "cloudResizeMachine": [p(.cloudMachine, .connection, 200)],
        "remote.connect": [p(.sidebarBackground, .create, 201)],
        "remote.newWorkspace": [p(.sshMachine, .create, 0)],
        "remote.openTerminalHere": [p(.pane, .create, 7)],
        "remote.reconnect": [p(.sshMachine, .connection, 100)],
        "remote.disconnect": [p(.sshMachine, .connection, 101)],
        "remote.install": [p(.sshMachine, .connection, 102)],
        "remote.forget": [p(.sshMachine, .close, 200)],
        "hibernateTab": [p(.tab, .connection, 0)],
        "wakeTab": [p(.tab, .connection, 1)],
        "tab.moveToNewSplit": [p(.tab, .move, 404)],
        "tab.moveToNewColumn": [p(.tab, .move, 405)],
        "tab.moveToWorkspace": [p(.tab, .move, 413)],
        "tab.moveToNewWindow": [p(.tab, .move, 407)],
        "tabGroup.moveLeft": [p(.tabGroup, .move, 200)],
        "tabGroup.moveRight": [p(.tabGroup, .move, 201)],
        "splitLeft": [p(.pane, .create, 2), p(.terminalSelection, .create, 102)],
        "splitUp": [p(.pane, .create, 3), p(.terminalSelection, .create, 103)],
        "swapPaneLeft": [p(.pane, .move, 301)],
        "swapPaneRight": [p(.pane, .move, 302)],
        "swapPaneUp": [p(.pane, .move, 303)],
        "swapPaneDown": [p(.pane, .move, 304)],
        "closePane": [p(.pane, .close, 600)],
        "renamePane": [p(.pane, .identity, 103)],
        "column.moveLeft": [p(.pane, .move, 310)],
        "column.moveRight": [p(.pane, .move, 311)],
        "column.center": [p(.pane, .layout, 504)],
        "column.widthOneThird": [p(.pane, .layout, 500)],
        "column.widthHalf": [p(.pane, .layout, 501)],
        "column.widthTwoThirds": [p(.pane, .layout, 502)],
        "column.widthFull": [p(.pane, .layout, 503)],
        "column.makeSticky": [p(.pane, .layout, 400)],
        "column.makeStickyLeft": [p(.pane, .layout, 403)],
        "column.unstick": [p(.pane, .layout, 401)],
        "column.toggleStickyOverlay": [p(.pane, .layout, 402)],
        "terminal.selectAll": [p(.terminalSelection, .edit, 2)],
        "terminal.clear": [p(.terminalSelection, .reset, 302)],
        "terminal.sendText": [p(.terminalSelection, .edit, 4)],
        "bookmark.addPage": [p(.browserPage, .inspect, 100), p(.bookmark, .create, 200), p(.bookmarksBar, .create, 0)],
        "bookmark.addAllTabs": [p(.bookmarksBar, .create, 2), p(.bookmark, .create, 202)],
        "bookmark.newFolder": [p(.bookmark, .create, 201), p(.bookmarksBar, .create, 1)],
        "bookmark.open": [p(.bookmark, .create, 0)],
        "bookmark.openInNewTab": [p(.bookmark, .create, 1)],
        "bookmark.openInBackgroundTab": [p(.bookmark, .create, 2)],
        "bookmark.openAll": [p(.bookmark, .create, 3)],
        "bookmark.edit": [p(.bookmark, .identity, 100)],
        "bookmark.remove": [p(.bookmark, .close, 101)],
        "bookmark.toggleBar": [p(.bookmark, .view, 300), p(.bookmarksBar, .view, 100)],
        "bookmark.manager": [p(.bookmark, .view, 301), p(.bookmarksBar, .view, 101)],
    ]
}
