// Right-click placements of the catalog actions (plans/cmux-next/actions.md).
// Each row is (menu, group, rank[, style][, in: submenu anchor]). Menus list
// groups in `MenuGroup` order; a rank's hundreds are sections inside the
// group (rank / 100, truncated). An action declared with a `surfacePlan`
// in its descriptor keeps its own placements.

nonisolated extension ActionSurfaceCatalog {
    static let placements: [ActionID: [ContextMenuPlacement]] = [
        "newTab": [p(.sidebarBackground, .create, 0)],
        "newBrowserWorkspace": [p(.sidebarBackground, .create, 3)],
        "openFolder": [p(.sidebarBackground, .create, 4)],
        "palette.openFolderInVSCodeInline": [p(.workspaceRow, .create, 100)],
        "reopenPreviousSession": [p(.sidebarBackground, .create, 8)],
        "reopenClosedWorkspace": [p(.sidebarBackground, .create, 7)],
        "moveWorkspaceUp": [p(.workspaceRow, .move, 200)],
        "moveWorkspaceDown": [p(.workspaceRow, .move, 201)],
        "palette.moveWorkspaceToTop": [p(.workspaceRow, .move, 202)],
        "moveWorkspaceToWindow": [p(.workspaceRow, .move, 204)],
        "moveWorkspaceToNewWindow": [p(.workspaceRow, .move, 205)],
        "renameWorkspace": [p(.workspaceRow, .identity, 100)],
        "palette.clearWorkspaceName": [p(.workspaceRow, .identity, 100)],
        "editWorkspaceDescription": [p(.workspaceRow, .identity, 101)],
        "palette.clearWorkspaceDescription": [p(.workspaceRow, .identity, 101)],
        "markWorkspaceDone": [p(.workspaceRow, .identity, 103)],
        "palette.workspaceStatus": [p(.workspaceRow, .identity, 102)],
        "palette.addWorkspaceChecklistItem": [p(.workspaceRow, .identity, 120)],
        "palette.openWorkspaceTodoPane": [p(.workspaceRow, .create, 101)],
        "closeWorkspace": [p(.workspaceRow, .close, 504)],
        "palette.closeOtherWorkspaces": [p(.workspaceRow, .close, 500)],
        "palette.closeWorkspacesBelow": [p(.workspaceRow, .close, 502)],
        "palette.closeWorkspacesAbove": [p(.workspaceRow, .close, 503)],
        "palette.toggleWorkspacePin": [p(.workspaceRow, .identity, 110)],
        "palette.markWorkspaceRead": [p(.workspaceRow, .identity, 111)],
        "palette.markWorkspaceUnread": [p(.workspaceRow, .identity, 112)],
        "palette.workspaceColor": [p(.workspaceRow, .identity, 104)],
        "palette.workspaceCustomColor": [p(.workspaceRow, .identity, 105)],
        "palette.resetWorkspaceColor": [p(.workspaceRow, .identity, 105)],
        "reconnectWorkspace": [p(.workspaceRow, .connection, 401)],
        "disconnectWorkspace": [p(.workspaceRow, .connection, 402)],
        "copyWorkspaceSSHError": [p(.workspaceRow, .inspect, 408)],
        "clearWorkspaceNotifications": [p(.workspaceRow, .identity, 114)],
        "revealWorkspaceInFinder": [p(.workspaceRow, .inspect, 403)],
        "palette.copyWorkspaceID": [p(.workspaceRow, .inspect, 405)],
        "palette.copyWorkspaceIDAndRef": [p(.workspaceRow, .inspect, 407)],
        "palette.copyWorkspaceLink": [p(.workspaceRow, .inspect, 406)],
        "workspaceGroup.newWorkspace": [p(.workspaceGroup, .create, 0)],
        "workspaceGroup.rename": [p(.workspaceGroup, .identity, 1)],
        "workspaceGroup.togglePin": [p(.workspaceGroup, .identity, 3)],
        "workspaceGroup.markRead": [p(.workspaceGroup, .identity, 100)],
        "workspaceGroup.markUnread": [p(.workspaceGroup, .identity, 101)],
        "workspaceGroup.clearNotifications": [p(.workspaceGroup, .identity, 102)],
        "workspaceGroup.ungroup": [p(.workspaceGroup, .close, 500)],
        "workspaceGroup.delete": [p(.workspaceGroup, .close, 502)],
        "workspaceGroup.editConfig": [p(.workspaceGroup, .inspect, 400)],
        "saveLayoutTemplate": [p(.workspaceRow, .organize, 210)],
        "palette.layout.open": [p(.workspaceRow, .create, 102)],
        "palette.openWorkspacePullRequests": [p(.workspaceRow, .inspect, 409)],
        "workspace.newAbove": [p(.workspaceRow, .create, 0)],
        "workspace.newBelow": [p(.workspaceRow, .create, 1)],
        "workspace.newAtTop": [p(.sidebarBackground, .create, 1)],
        "workspace.newAtBottom": [p(.sidebarBackground, .create, 1)],
        "workspace.newInGroup": [p(.workspaceRow, .create, 2)],
        "workspace.newInNewGroup": [p(.workspaceRow, .create, 3)],
        "workspace.newOnMachine": [p(.sidebarBackground, .create, 2)],
        "workspace.newInSameDirectory": [p(.workspaceRow, .create, 3)],
        "workspace.duplicate": [p(.workspaceRow, .create, 4)],
        "workspace.duplicateTerminalsOnly": [p(.workspaceRow, .create, 5)],
        "workspace.setIcon": [p(.workspaceRow, .identity, 106)],
        "workspace.clearIcon": [p(.workspaceRow, .identity, 107)],
        "workspace.moveToBottom": [p(.workspaceRow, .move, 203)],
        "workspace.moveToNewGroup": [p(.workspaceRow, .organize, 207)],
        "workspace.closeOthersInGroup": [p(.workspaceRow, .close, 501)],
        "workspace.sortByName": [p(.sidebarBackground, .move, 100)],
        "workspace.sortByLastUsed": [p(.sidebarBackground, .move, 101)],
        "workspace.sortByDirectory": [p(.sidebarBackground, .move, 102)],
        "workspaceGroup.collapseAll": [p(.workspaceGroup, .organize, 5), p(.sidebarBackground, .organize, 103)],
        "workspaceGroup.expandAll": [p(.workspaceGroup, .organize, 6), p(.sidebarBackground, .organize, 104)],
        "workspace.copyPath": [p(.workspaceRow, .inspect, 404)],
        "workspace.mergeInto": [p(.workspaceRow, .move, 211)],
        "pane.moveToNewWorkspace": [p(.pane, .move, 300)],
        "newWorkspaceGroup": [p(.sidebarBackground, .create, 5)],
        "groupSelectedWorkspaces": [p(.workspaceRow, .organize, 205)],
        "toggleFocusedWorkspaceGroupCollapsed": [p(.workspaceGroup, .organize, 4)],
        "moveWorkspaceToGroup": [p(.workspaceRow, .organize, 206)],
        "removeWorkspaceFromGroup": [p(.workspaceRow, .organize, 208)],
        "workspaceGroup.setColor": [p(.workspaceGroup, .identity, 2, .submenu)],
        "workspaceGroup.moveUp": [p(.workspaceGroup, .move, 300)],
        "workspaceGroup.moveDown": [p(.workspaceGroup, .move, 301)],
        "workspaceGroup.moveToWindow": [p(.workspaceGroup, .move, 303)],
        "workspaceGroup.closeWorkspaces": [p(.workspaceGroup, .close, 501)],
        "workspaceGroup.moveToNewWindow": [p(.workspaceGroup, .move, 302)],
        "workspaceGroup.color.grey": [p(.workspaceGroup, .identity, 0, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.blue": [p(.workspaceGroup, .identity, 1, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.red": [p(.workspaceGroup, .identity, 2, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.yellow": [p(.workspaceGroup, .identity, 3, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.green": [p(.workspaceGroup, .identity, 4, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.pink": [p(.workspaceGroup, .identity, 5, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.purple": [p(.workspaceGroup, .identity, 6, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.cyan": [p(.workspaceGroup, .identity, 7, in: "workspaceGroup.setColor")],
        "workspaceGroup.color.orange": [p(.workspaceGroup, .identity, 8, in: "workspaceGroup.setColor")],
        "room.new": [p(.sidebarBackground, .create, 6), p(.profile, .create, 300)],
        "room.newWindow": [p(.profile, .create, 0)],
        "room.newWorkspace": [p(.profile, .create, 1)],
        "room.rename": [p(.profile, .identity, 100)],
        "room.setColor": [p(.profile, .identity, 101, .submenu)],
        "room.color.grey": [p(.profile, .identity, 0, in: "room.setColor")],
        "room.color.blue": [p(.profile, .identity, 1, in: "room.setColor")],
        "room.color.red": [p(.profile, .identity, 2, in: "room.setColor")],
        "room.color.yellow": [p(.profile, .identity, 3, in: "room.setColor")],
        "room.color.green": [p(.profile, .identity, 4, in: "room.setColor")],
        "room.color.pink": [p(.profile, .identity, 5, in: "room.setColor")],
        "room.color.purple": [p(.profile, .identity, 6, in: "room.setColor")],
        "room.color.cyan": [p(.profile, .identity, 7, in: "room.setColor")],
        "room.color.orange": [p(.profile, .identity, 8, in: "room.setColor")],
        "room.clearColor": [p(.profile, .identity, 100, in: "room.setColor")],
        "room.setIcon": [p(.profile, .identity, 102)],
        "room.clearIcon": [p(.profile, .identity, 103)],
        "room.setDefaults": [p(.profile, .identity, 106)],
        "room.delete": [p(.profile, .close, 400)],
        "room.moveLeft": [p(.profile, .move, 200)],
        "room.moveRight": [p(.profile, .move, 201)],
        "workspace.moveToRoom": [p(.workspaceRow, .move, 209)],
        "workspace.duplicateToRoom": [p(.workspaceRow, .move, 210)],
        "workspaceGroup.moveToRoom": [p(.workspaceGroup, .move, 304)],
        "room.setTheme": [p(.profile, .identity, 104, .choices)],
        "room.clearTheme": [p(.profile, .identity, 105)],
        "workspace.setTheme": [p(.workspaceRow, .identity, 108, .choices)],
        "workspace.clearTheme": [p(.workspaceRow, .identity, 109)],
        "terminal.setTheme": [p(.tab, .identity, 205, .choices)],
        "terminal.clearTheme": [p(.tab, .identity, 206)],
        "splitRight": [p(.pane, .create, 0), p(.terminalSelection, .create, 100)],
        "newColumn": [p(.pane, .create, 4), p(.column, .create, 0)],
        "splitDown": [p(.pane, .create, 1), p(.column, .create, 2), p(.terminalSelection, .create, 101)],
        "newPaneAutoLayout": [p(.column, .create, 1), p(.pane, .create, 8)],
        "toggleSplitZoom": [p(.pane, .layout, 100), p(.column, .layout, 203), p(.terminalSelection, .layout, 104)],
        "equalizeSplits": [p(.pane, .layout, 101), p(.column, .layout, 202)],
        "triggerFlash": [p(.pane, .inspect, 500)],
        "palette.swapWithSession": [p(.pane, .connection, 200)],
        "toggleCanvasLayout": [p(.pane, .layout, 102)],
        "palette.newSimulatorPane": [p(.newTab, .create, 100)],
        "palette.openFilesPane": [p(.newTab, .create, 101)],
        "palette.openFindPane": [p(.newTab, .create, 102)],
        "palette.openVaultPane": [p(.newTab, .create, 103)],
        "palette.openCloudPane": [p(.newTab, .create, 104)],
        "newTab.sameKind": [p(.tab, .create, -1)],
        "newSurface": [p(.tab, .create, 0), p(.newTab, .create, 0)],
        "openBrowser.webkit": [p(.tab, .create, 1), p(.newTab, .create, 1)],
        "openBrowser.chromium": [p(.tab, .create, 2), p(.newTab, .create, 2)],
        "closeTab": [p(.tab, .close, 604)],
        "closeOtherTabsInPane": [p(.tab, .close, 603)],
        "closeTabsToLeft": [p(.tab, .close, 601)],
        "closeTabsToRight": [p(.tab, .close, 602)],
        "renameTab": [p(.tab, .identity, 200)],
        "palette.clearTabName": [p(.tab, .identity, 201)],
        "moveSurfaceLeft": [p(.tab, .move, 409)],
        "moveSurfaceRight": [p(.tab, .move, 410)],
        "moveSurfaceToPreviousPane": [p(.tab, .move, 411)],
        "moveSurfaceToNextPane": [p(.tab, .move, 412)],
        "moveSurfaceToPaneLeft": [p(.tab, .move, 400)],
        "moveSurfaceToPaneRight": [p(.tab, .move, 401)],
        "moveSurfaceToPaneUp": [p(.tab, .move, 402)],
        "moveSurfaceToPaneDown": [p(.tab, .move, 403)],
        "palette.moveTabToNewWorkspace": [p(.tab, .move, 406)],
        "palette.toggleTabPin": [p(.tab, .identity, 202)],
        "palette.toggleTabUnread": [p(.tab, .identity, 203)],
        "palette.toggleFullWidthTab": [p(.tab, .layout, 408)],
        "duplicateTab": [p(.tab, .create, 3)],
        "reloadTab": [p(.tab, .create, 4)],
        "toggleTabAudioMute": [p(.tab, .identity, 204)],
        "disconnectRemoteTab": [p(.tab, .connection, 2)],
        "palette.copyIdentifiers": [p(.tab, .inspect, 503)],
        "palette.copyPaneID": [p(.pane, .inspect, 500), p(.tab, .inspect, 504)],
        "palette.copyPaneLink": [p(.pane, .inspect, 501), p(.tab, .inspect, 505)],
        "palette.copySurfaceID": [p(.tab, .inspect, 501)],
        "palette.copySurfaceLink": [p(.tab, .inspect, 502)],
        "tab.showResources": [p(.tab, .inspect, 500)],
        "workspace.showResources": [p(.workspaceRow, .inspect, 400)],
        "tabGroup.create": [p(.tab, .organize, 300)],
        "tabGroup.addTab": [p(.tab, .organize, 301)],
        "tabGroup.removeTab": [p(.tab, .organize, 302)],
        "tabGroup.rename": [p(.tabGroup, .identity, 1)],
        "tabGroup.setColor": [p(.tabGroup, .identity, 2, .submenu)],
        "tabGroup.toggleCollapsed": [p(.tabGroup, .organize, 3)],
        "tabGroup.ungroup": [p(.tabGroup, .close, 300)],
        "tabGroup.close": [p(.tabGroup, .close, 301)],
        "tabGroup.moveToNewSplit": [p(.tabGroup, .move, 202)],
        "tabGroup.moveToNewColumn": [p(.tabGroup, .move, 203)],
        "tabGroup.moveToNewWorkspace": [p(.tabGroup, .move, 204)],
        "tabGroup.moveToWorkspace": [p(.tabGroup, .move, 205)],
        "tabGroup.moveToNewWindow": [p(.tabGroup, .move, 206)],
        "tabGroup.newTab": [p(.tabGroup, .create, 0)],
        "tabGroup.save": [p(.tabGroup, .organize, 100)],
        "tabGroup.unsave": [p(.tabGroup, .organize, 101)],
        "tabGroup.deleteSaved": [p(.tabGroup, .organize, 103)],
        "tabGroup.reopenSaved": [p(.tabGroup, .organize, 102)],
        "tabGroup.color.grey": [p(.tabGroup, .identity, 0, in: "tabGroup.setColor")],
        "tabGroup.color.blue": [p(.tabGroup, .identity, 1, in: "tabGroup.setColor")],
        "tabGroup.color.red": [p(.tabGroup, .identity, 2, in: "tabGroup.setColor")],
        "tabGroup.color.yellow": [p(.tabGroup, .identity, 3, in: "tabGroup.setColor")],
        "tabGroup.color.green": [p(.tabGroup, .identity, 4, in: "tabGroup.setColor")],
        "tabGroup.color.pink": [p(.tabGroup, .identity, 5, in: "tabGroup.setColor")],
        "tabGroup.color.purple": [p(.tabGroup, .identity, 6, in: "tabGroup.setColor")],
        "tabGroup.color.cyan": [p(.tabGroup, .identity, 7, in: "tabGroup.setColor")],
        "tabGroup.color.orange": [p(.tabGroup, .identity, 8, in: "tabGroup.setColor")],
        "screen.new": [p(.screen, .create, 0), p(.screenBar, .create, 0)],
        "screen.newWith": [p(.screenBar, .create, 1), p(.screen, .create, 2)],
        "screen.duplicate": [p(.screen, .create, 1)],
        "screen.close": [p(.screen, .close, 400)],
        "screen.closeOthers": [p(.screen, .close, 401)],
        "screen.closeToRight": [p(.screen, .close, 402)],
        "screen.closeToLeft": [p(.screen, .close, 403)],
        "screen.reopenClosed": [p(.screenBar, .create, 2)],
        "screen.rename": [p(.screen, .identity, 100)],
        "screen.clearName": [p(.screen, .identity, 100)],
        "screen.setColor": [p(.screen, .identity, 101, .submenu)],
        "screen.clearColor": [p(.screen, .identity, 9, in: "screen.setColor")],
        "screen.setIcon": [p(.screen, .identity, 102)],
        "screen.clearIcon": [p(.screen, .identity, 103)],
        "screen.togglePin": [p(.screen, .identity, 104)],
        "screen.color.grey": [p(.screen, .identity, 0, in: "screen.setColor")],
        "screen.color.blue": [p(.screen, .identity, 1, in: "screen.setColor")],
        "screen.color.red": [p(.screen, .identity, 2, in: "screen.setColor")],
        "screen.color.yellow": [p(.screen, .identity, 3, in: "screen.setColor")],
        "screen.color.green": [p(.screen, .identity, 4, in: "screen.setColor")],
        "screen.color.pink": [p(.screen, .identity, 5, in: "screen.setColor")],
        "screen.color.purple": [p(.screen, .identity, 6, in: "screen.setColor")],
        "screen.color.cyan": [p(.screen, .identity, 7, in: "screen.setColor")],
        "screen.color.orange": [p(.screen, .identity, 8, in: "screen.setColor")],
        "screen.moveLeft": [p(.screen, .move, 300)],
        "screen.moveRight": [p(.screen, .move, 301)],
        "screen.moveToWorkspace": [p(.screen, .move, 302)],
        "screen.moveToNewWorkspace": [p(.screen, .move, 303)],
        "screen.moveToNewWindow": [p(.screen, .move, 304)],
        "screenGroup.create": [p(.screen, .organize, 200)],
        "screenGroup.addScreen": [p(.screen, .organize, 201)],
        "screenGroup.removeScreen": [p(.screen, .organize, 202)],
        "screenGroup.newScreen": [p(.screenGroup, .create, 0)],
        "screenGroup.rename": [p(.screenGroup, .identity, 1)],
        "screenGroup.setColor": [p(.screenGroup, .identity, 2, .submenu)],
        "screenGroup.toggleCollapsed": [p(.screenGroup, .organize, 3)],
        "screenGroup.ungroup": [p(.screenGroup, .close, 300)],
        "screenGroup.close": [p(.screenGroup, .close, 301)],
        "screenGroup.moveLeft": [p(.screenGroup, .move, 200)],
        "screenGroup.moveRight": [p(.screenGroup, .move, 201)],
        "screenGroup.moveToWorkspace": [p(.screenGroup, .move, 202)],
        "screenGroup.moveToNewWorkspace": [p(.screenGroup, .move, 203)],
        "screenGroup.moveToNewWindow": [p(.screenGroup, .move, 204)],
        "screenGroup.save": [p(.screenGroup, .organize, 100)],
        "screenGroup.unsave": [p(.screenGroup, .organize, 101)],
        "screenGroup.color.grey": [p(.screenGroup, .identity, 0, in: "screenGroup.setColor")],
        "screenGroup.color.blue": [p(.screenGroup, .identity, 1, in: "screenGroup.setColor")],
        "screenGroup.color.red": [p(.screenGroup, .identity, 2, in: "screenGroup.setColor")],
        "screenGroup.color.yellow": [p(.screenGroup, .identity, 3, in: "screenGroup.setColor")],
        "screenGroup.color.green": [p(.screenGroup, .identity, 4, in: "screenGroup.setColor")],
        "screenGroup.color.pink": [p(.screenGroup, .identity, 5, in: "screenGroup.setColor")],
        "screenGroup.color.purple": [p(.screenGroup, .identity, 6, in: "screenGroup.setColor")],
        "screenGroup.color.cyan": [p(.screenGroup, .identity, 7, in: "screenGroup.setColor")],
        "screenGroup.color.orange": [p(.screenGroup, .identity, 8, in: "screenGroup.setColor")],
        "terminal.keep": [p(.tab, .identity, 210)],
        "clearScreenKeepScrollback": [p(.terminalSelection, .reset, 300)],
        "useSelectionForFind": [p(.terminalSelection, .edit, 3)],
        "terminalCopy": [p(.terminalSelection, .edit, 0), p(.link, .edit, 100)],
        "terminalPaste": [p(.terminalSelection, .edit, 1)],
        "resetTerminal": [p(.terminalSelection, .reset, 301)],
        "reconnectPane": [p(.pane, .connection, 201)],
        "palette.terminalOpenDirectory": [p(.terminalSelection, .inspect, 0)],
        "browserBack": [p(.browserPage, .navigate, 0)],
        "browserForward": [p(.browserPage, .navigate, 1)],
        "browserReload": [p(.browserPage, .navigate, 2)],
        "browserHardReload": [p(.browserPage, .navigate, 3)],
        "browser.openInChromium": [p(.tab, .reopen, 100)],
        "browser.openInWebKit": [p(.tab, .reopen, 101)],
        "toggleBrowserDeveloperTools": [p(.browserPage, .inspect, 201)],
        "showBrowserJavaScriptConsole": [p(.browserPage, .inspect, 202)],
        "inspectBrowserElement": [p(.browserPage, .inspect, 203)],
        "toggleBrowserFocusMode": [p(.browserPage, .view, 0)],
        "toggleBrowserDesignMode": [p(.browserPage, .view, 1)],
        "toggleReactGrab": [p(.browserPage, .view, 2)],
        "splitBrowserRight": [p(.pane, .create, 5)],
        "splitBrowserDown": [p(.pane, .create, 6)],
        "palette.browserOpenDefault": [p(.browserPage, .inspect, 101)],
        "palette.browserToggleOmnibar": [p(.browserPage, .view, 3)],
        "openLinkInNewTab": [p(.link, .navigate, 0)],
        "openLinkInDefaultBrowser": [p(.link, .navigate, 1)],
        "browserScreenshotPage": [p(.browserPage, .inspect, 102)],
        "browserScreenshotSection": [p(.browserPage, .inspect, 103)],
        "browserTheme": [p(.browserPage, .identity, 0, .choices)],
        "openDiffViewer": [p(.pane, .create, 100)],
        "palette.openDirectoryDiffViewer": [p(.pane, .create, 101)],
        "browser.pageInfo": [p(.browserPage, .inspect, 200, .submenu), p(.browserPage, .inspect, 0, in: "browser.pageInfo")],
        "browser.pageInfo.connection": [p(.browserPage, .inspect, 1, in: "browser.pageInfo")],
        "browser.pageInfo.certificate": [p(.browserPage, .inspect, 2, in: "browser.pageInfo")],
        "browser.pageInfo.cookies": [p(.browserPage, .inspect, 200, in: "browser.pageInfo")],
        "browser.pageInfo.manageSiteData": [p(.browserPage, .inspect, 201, in: "browser.pageInfo")],
        "browser.pageInfo.deleteSiteData": [p(.browserPage, .inspect, 202, in: "browser.pageInfo")],
        "browser.pageInfo.setPermission": [p(.browserPage, .inspect, 100, in: "browser.pageInfo")],
        "browser.pageInfo.resetPermissions": [p(.browserPage, .inspect, 101, in: "browser.pageInfo")],
        "browser.pageInfo.siteSettings": [p(.browserPage, .inspect, 300, in: "browser.pageInfo")],
        "browser.pageInfo.aboutThisPage": [p(.browserPage, .inspect, 301, in: "browser.pageInfo")],
        "browser.extensions.menu": [p(.browserPage, .inspect, 300)],
        "browser.extensions.manage": [p(.browserPage, .inspect, 301)],
        "browser.extensions.webStore": [p(.browserPage, .inspect, 302)],
        "browser.extensions.loadUnpacked": [p(.browserPage, .inspect, 303)],
        "browserProfile.new": [p(.browserProfile, .create, 300)],
        "browserProfile.rename": [p(.browserProfile, .identity, 100)],
        "browserProfile.setColor": [p(.browserProfile, .identity, 101)],
        "browserProfile.clearColor": [p(.browserProfile, .identity, 102)],
        "browserProfile.setIcon": [p(.browserProfile, .identity, 103)],
        "browserProfile.clearIcon": [p(.browserProfile, .identity, 104)],
        "browserProfile.delete": [p(.browserProfile, .close, 400)],
        "browserProfile.newTab": [p(.newTab, .create, 3), p(.browserProfile, .create, 0)],
        "browserProfile.newWindow": [p(.browserProfile, .create, 1)],
        "browserProfile.newWorkspace": [p(.browserProfile, .create, 2)],
        "browserProfile.openLink": [p(.link, .navigate, 2)],
        "browserProfile.setWorkspaceDefault": [p(.workspaceRow, .identity, 300)],
        "browserProfile.clearWorkspaceDefault": [p(.workspaceRow, .identity, 301)],
        "browserProfile.setRoomDefault": [p(.profile, .identity, 107)],
        "browserProfile.clearRoomDefault": [p(.profile, .identity, 108)],
        "browserProfile.moveTab": [p(.tab, .reopen, 102)],
        "browserProfile.duplicateTab": [p(.tab, .reopen, 103)],
        "browserProfile.manageExtensions": [p(.browserProfile, .inspect, 200)],
        "toggleSidebar": [p(.sidebarBackground, .view, 300)],
        "notificationOpen": [p(.notification, .navigate, 0)],
        "notificationCopy": [p(.notification, .edit, 0)],
        "notificationToggleRead": [p(.notification, .identity, 0)],
        "notificationDismiss": [p(.notification, .close, 0)],
        "notifications.toggleWorkspaceMute": [p(.workspaceRow, .identity, 113)],
        "palette.newAgentChat": [p(.newTab, .create, 4)],
        "palette.forkAgentConversationRight": [p(.terminalSelection, .create, 200)],
        "palette.forkAgentConversationLeft": [p(.terminalSelection, .create, 202)],
        "palette.forkAgentConversationTop": [p(.terminalSelection, .create, 203)],
        "palette.forkAgentConversationBottom": [p(.terminalSelection, .create, 204)],
        "palette.forkAgentConversationNewTab": [p(.terminalSelection, .create, 201)],
        "palette.forkAgentConversationNewWorkspace": [p(.terminalSelection, .create, 205)],
        "newCloudWorkspace": [p(.sidebarBackground, .create, 200)],
        "palette.cloud.fork": [p(.cloudMachine, .connection, 203)],
        "palette.cloud.snapshot": [p(.cloudMachine, .connection, 202)],
        "palette.cloud.restore": [p(.cloudMachine, .connection, 207)],
        "palette.cloud.promoteTemplate": [p(.cloudMachine, .connection, 206)],
        "palette.cloud.status": [p(.cloudMachine, .connection, 201)],
        "palette.cloud.ports": [p(.cloudMachine, .connection, 205)],
        "palette.cloud.tools": [p(.cloudMachine, .inspect, 103)],
        "palette.cloud.handoff": [p(.cloudMachine, .connection, 204)],
        "cloudNewTerminal": [p(.cloudMachine, .create, 0)],
        "cloudOpenMachine": [p(.cloudMachine, .create, 1)],
        "cloudRenameMachine": [p(.cloudMachine, .identity, 2)],
        "cloudKillMachine": [p(.cloudMachine, .close, 300)],
        "cloudCopyLink": [p(.cloudMachine, .inspect, 101)],
        "cloudCopyPort": [p(.cloudMachine, .inspect, 102)],
        "cloudCopyMachineID": [p(.cloudMachine, .inspect, 100)],
        "cloudResizeMachine": [p(.cloudMachine, .connection, 200)],
        "remote.connect": [p(.sidebarBackground, .create, 201)],
        "remote.newWorkspace": [p(.sshMachine, .create, 0)],
        "remote.openTerminalHere": [p(.pane, .create, 7)],
        "remote.reconnect": [p(.sshMachine, .connection, 100)],
        "remote.disconnect": [p(.sshMachine, .connection, 101)],
        "remote.install": [p(.sshMachine, .connection, 102)],
        "remote.forget": [p(.sshMachine, .close, 200)],
        "hibernateTab": [p(.tab, .connection, 0)],
        "wakeTab": [p(.tab, .connection, 1)],
        "tab.moveToNewSplit": [p(.tab, .move, 404)],
        "tab.moveToNewColumn": [p(.tab, .move, 405)],
        "tab.moveToWorkspace": [p(.tab, .move, 413)],
        "tab.moveToNewWindow": [p(.tab, .move, 407)],
        "tabGroup.moveLeft": [p(.tabGroup, .move, 200)],
        "tabGroup.moveRight": [p(.tabGroup, .move, 201)],
        "splitLeft": [p(.pane, .create, 2), p(.terminalSelection, .create, 102)],
        "splitUp": [p(.pane, .create, 3), p(.terminalSelection, .create, 103)],
        "swapPaneLeft": [p(.pane, .move, 301)],
        "swapPaneRight": [p(.pane, .move, 302)],
        "swapPaneUp": [p(.pane, .move, 303)],
        "swapPaneDown": [p(.pane, .move, 304)],
        "closePane": [p(.pane, .close, 600)],
        "renamePane": [p(.pane, .identity, 103)],
        "column.moveLeft": [p(.column, .move, 200), p(.pane, .move, 310)],
        "column.moveRight": [p(.column, .move, 201), p(.pane, .move, 311)],
        "column.center": [p(.column, .layout, 104), p(.pane, .layout, 504)],
        "column.widthOneThird": [p(.column, .layout, 100), p(.pane, .layout, 500)],
        "column.widthHalf": [p(.column, .layout, 101), p(.pane, .layout, 501)],
        "column.widthTwoThirds": [p(.column, .layout, 102), p(.pane, .layout, 502)],
        "column.widthFull": [p(.column, .layout, 103), p(.pane, .layout, 503)],
        "column.makeSticky": [p(.pane, .layout, 400), p(.column, .layout, 300)],
        "column.makeStickyLeft": [p(.column, .layout, 301), p(.pane, .layout, 403)],
        "column.unstick": [p(.pane, .layout, 401), p(.column, .layout, 302)],
        "column.toggleStickyOverlay": [p(.pane, .layout, 402), p(.column, .layout, 303)],
        "terminal.selectAll": [p(.terminalSelection, .edit, 2)],
        "terminal.clear": [p(.terminalSelection, .reset, 302)],
        "terminal.sendText": [p(.terminalSelection, .edit, 4)],
        "bookmark.addPage": [p(.browserPage, .inspect, 100), p(.bookmark, .create, 200), p(.bookmarksBar, .create, 0)],
        "bookmark.addAllTabs": [p(.bookmarksBar, .create, 2), p(.bookmark, .create, 202)],
        "bookmark.newFolder": [p(.bookmark, .create, 201), p(.bookmarksBar, .create, 1)],
        "bookmark.open": [p(.bookmark, .create, 0)],
        "bookmark.openInNewTab": [p(.bookmark, .create, 1)],
        "bookmark.openInBackgroundTab": [p(.bookmark, .create, 2)],
        "bookmark.openAll": [p(.bookmark, .create, 3)],
        "bookmark.edit": [p(.bookmark, .identity, 100)],
        "bookmark.remove": [p(.bookmark, .close, 101)],
        "bookmark.toggleBar": [p(.bookmark, .view, 300), p(.bookmarksBar, .view, 100)],
        "bookmark.manager": [p(.bookmark, .view, 301), p(.bookmarksBar, .view, 101)],
    ]
}
