import Foundation

/// Recognizes only the attach command generated by cmux's local-tmux profile.
///
/// `tmuxStartCommand` is also used by older agent integrations, so accepting
/// every command that happens to contain `tmux` would turn session restore into
/// an arbitrary shell-command launcher. The profile emits a fixed environment
/// marker and an `exec ... attach-session` shape; both are required here.
struct LocalTmuxRestoreCommandPolicy: Sendable {
    func restorableCommand(_ rawCommand: String?) -> String? {
        guard let command = rawCommand?.trimmingCharacters(in: .whitespacesAndNewlines),
              !command.isEmpty,
              !containsControlScalar(command) else {
            return nil
        }
        let words = shellWords(command)
        guard words.count == 9,
              words[0] == "TMUX=",
              words[1] == "CMUX_LOCAL_TMUX=1",
              words[2] == "exec",
              (words[3] as NSString).lastPathComponent == "tmux",
              words[4] == "-S",
              words[5].hasPrefix("/"),
              words[5].hasSuffix("/server.sock"),
              words[6] == "attach-session",
              words[7] == "-t",
              words[8].range(of: "^[A-Za-z0-9._:-]{1,128}$", options: .regularExpression) != nil else {
            return nil
        }
        return command
    }

    private func containsControlScalar(_ command: String) -> Bool {
        command.unicodeScalars.contains { scalar in
            switch scalar.properties.generalCategory {
            case .control, .format, .lineSeparator, .paragraphSeparator:
                return true
            default:
                return false
            }
        }
    }

    /// Small shell-word reader used only to validate cmux-generated commands.
    /// It deliberately does not expand variables or execute substitutions.
    private func shellWords(_ command: String) -> [String] {
        var words: [String] = []
        var index = command.startIndex
        while index < command.endIndex {
            while index < command.endIndex, command[index].isWhitespace {
                index = command.index(after: index)
            }
            guard index < command.endIndex else { break }
            var value = ""
            while index < command.endIndex, !command[index].isWhitespace {
                let character = command[index]
                if character == "'" {
                    index = command.index(after: index)
                    while index < command.endIndex, command[index] != "'" {
                        value.append(command[index])
                        index = command.index(after: index)
                    }
                    guard index < command.endIndex else { return [] }
                    index = command.index(after: index)
                } else if character == "\\" {
                    let next = command.index(after: index)
                    guard next < command.endIndex else { return [] }
                    value.append(command[next])
                    index = command.index(after: next)
                } else {
                    value.append(character)
                    index = command.index(after: index)
                }
            }
            guard !value.isEmpty else { return [] }
            words.append(value)
        }
        return words
    }
}
