name: Daily Automated Release

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: daily-release
  cancel-in-progress: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create daily release
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const today = new Date().toISOString().split("T")[0];
            const tagName = `daily-${today}`;
            const releaseName = `Daily Release ${today}`;

            try {
              await github.rest.repos.getReleaseByTag({ owner, repo, tag: tagName });
              core.notice(`Release for ${today} already exists (tag: ${tagName}).`);
              return;
            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
            }

            await github.rest.repos.createRelease({
              owner,
              repo,
              tag_name: tagName,
              name: releaseName,
              body: `Automated daily release for ${today}.`,
              generate_release_notes: false,
              draft: false,
              prerelease: false,
            });
