name: Build & Publish Electron Updates (GitHub Releases)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - package.json
      - apps/client/package.json

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

env:
  NODE_VERSION: "24"

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.resolve.outputs.tag }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Resolve release tag
        id: resolve
        env:
          EVENT_RELEASE_TAG: ${{ github.event.release.tag_name }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail

          release_tag="${EVENT_RELEASE_TAG:-}"
          repo="${GITHUB_REPOSITORY}"

          version="$(node -p "require('./apps/client/package.json').version")"
          if [[ -z "$version" ]]; then
            echo "Unable to determine app version from apps/client/package.json" >&2
            exit 1
          fi

          declare -a candidates
          candidates=()

          if [[ -n "$release_tag" ]]; then
            candidates+=("$release_tag")
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            candidates+=("$GITHUB_REF_NAME")
          fi

          candidates+=("v$version" "$version")

          resolved_tag=""
          for tag in "${candidates[@]}"; do
            if [[ -z "$tag" ]]; then
              continue
            fi
            if gh release view "$tag" --repo "$repo" >/dev/null 2>&1; then
              resolved_tag="$tag"
              break
            fi
          done

          if [[ -z "$resolved_tag" ]]; then
            resolved_tag="${candidates[0]}"
            if [[ -z "$resolved_tag" ]]; then
              echo "Unable to resolve a release tag candidate" >&2
              exit 1
            fi
            echo "Creating draft release $resolved_tag"
            gh release create "$resolved_tag" \
              --repo "$repo" \
              --draft \
              --title "$resolved_tag" \
              --notes ""
          fi

          echo "Resolved release tag: $resolved_tag"
          printf 'tag=%s\n' "$resolved_tag" >> "$GITHUB_OUTPUT"

  mac-x64:
    name: macOS x64
    needs: prepare-release
    environment: electron
    runs-on: ${{ (vars.USE_LARGE_RUNNERS == 'true' && 'macos-13-large') || 'macos-13' }}
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          profile: minimal
          targets: x86_64-apple-darwin
      - name: Install dependencies (bun)
        run: bun install --frozen-lockfile
      - name: Install app deps in apps/client (bun)
        working-directory: apps/client
        run: bun install --frozen-lockfile
      - name: Ensure local production node_modules (apps/client)
        working-directory: apps/client
        run: |
          set -euo pipefail
          echo "Ensuring local node_modules in $(pwd)..."
          # First try a local bun install to materialize node_modules
          bun install --frozen-lockfile || true
          if [ ! -d node_modules ]; then
            echo "Local node_modules missing; copying from workspace root..."
            # Copy the hoisted workspace root node_modules into the app package
            # -L to dereference any symlinks so the packaged app has real files
            rsync -aL --delete ../../node_modules/ node_modules/ || true
          fi
          if [ ! -d node_modules ]; then
            echo "ERROR: apps/client/node_modules still missing after attempts." >&2
            exit 1
          fi
      - name: Write .env for build
        shell: bash
        run: |
          cat > .env <<EOF
          NEXT_PUBLIC_CONVEX_URL=${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
          NEXT_PUBLIC_STACK_PROJECT_ID=${{ secrets.NEXT_PUBLIC_STACK_PROJECT_ID }}
          NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY=${{ secrets.NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY }}
          NEXT_PUBLIC_WWW_ORIGIN=${{ secrets.NEXT_PUBLIC_WWW_ORIGIN }}
          NEXT_PUBLIC_GITHUB_APP_SLUG=${{ secrets.NEXT_PUBLIC_GITHUB_APP_SLUG }}
          EOF
      - name: Build native Rust addon
        working-directory: apps/server/native/core
        shell: bash
        run: bunx --bun @napi-rs/cli build --platform --release
      - name: Build, sign, and notarize (x64) via publish script
        env:
          MAC_CERT_BASE64: ${{ secrets.MAC_CERT_BASE64 }}
          MAC_CERT_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
        run: bash scripts/publish-build-mac-x64.sh --skip-install
      - name: Publish notarized macOS x64 artifacts to GitHub Releases
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ needs.prepare-release.outputs.release_tag }}
          REPO: ${{ github.repository }}
        working-directory: apps/client
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          artifacts=(
            dist-electron/*.dmg
            dist-electron/*.zip
            dist-electron/latest-*.yml
            dist-electron/*.blockmap
          )
          if [[ ${#artifacts[@]} -eq 0 ]]; then
            echo "No notarized macOS x64 artifacts found in dist-electron" >&2
            exit 1
          fi
          release_tag="${RELEASE_TAG:-}"
          if [[ -z "$release_tag" ]]; then
            echo "Release tag not provided" >&2
            exit 1
          fi
          repo="${REPO}"
          for artifact in "${artifacts[@]}"; do
            echo "Uploading $artifact to $repo@$release_tag"
            gh release upload "$release_tag" "$artifact" --repo "$repo" --clobber
          done

  mac-arm64:
    name: macOS arm64
    needs: prepare-release
    environment: electron
    runs-on: ${{ (vars.USE_LARGE_RUNNERS == 'true' && 'macos-14-xlarge') || 'macos-14' }}
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          profile: minimal
          targets: aarch64-apple-darwin
      - name: Install dependencies (bun)
        run: bun install --frozen-lockfile
      - name: Install app deps in apps/client (bun)
        working-directory: apps/client
        run: bun install --frozen-lockfile
      - name: Ensure local production node_modules (apps/client)
        working-directory: apps/client
        run: |
          set -euo pipefail
          echo "Ensuring local node_modules in $(pwd)..."
          # First try a local bun install to materialize node_modules
          bun install --frozen-lockfile || true
          if [ ! -d node_modules ]; then
            echo "Local node_modules missing; copying from workspace root..."
            # Copy the hoisted workspace root node_modules into the app package
            # -L to dereference any symlinks so the packaged app has real files
            rsync -aL --delete ../../node_modules/ node_modules/ || true
          fi
          if [ ! -d node_modules ]; then
            echo "ERROR: apps/client/node_modules still missing after attempts." >&2
            exit 1
          fi
      - name: Write .env for build
        shell: bash
        run: |
          cat > .env <<EOF
          NEXT_PUBLIC_CONVEX_URL=${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
          NEXT_PUBLIC_STACK_PROJECT_ID=${{ secrets.NEXT_PUBLIC_STACK_PROJECT_ID }}
          NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY=${{ secrets.NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY }}
          NEXT_PUBLIC_WWW_ORIGIN=${{ secrets.NEXT_PUBLIC_WWW_ORIGIN }}
          NEXT_PUBLIC_GITHUB_APP_SLUG=${{ secrets.NEXT_PUBLIC_GITHUB_APP_SLUG }}
          EOF
      - name: Build native Rust addon
        working-directory: apps/server/native/core
        shell: bash
        run: bunx --bun @napi-rs/cli build --platform --release
      - name: Build, sign, and notarize (arm64) via publish script
        env:
          MAC_CERT_BASE64: ${{ secrets.MAC_CERT_BASE64 }}
          MAC_CERT_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
        run: bash scripts/publish-build-mac-arm64.sh --skip-install
      - name: Publish notarized macOS arm64 artifacts to GitHub Releases
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ needs.prepare-release.outputs.release_tag }}
          REPO: ${{ github.repository }}
        working-directory: apps/client
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          artifacts=(
            dist-electron/*.dmg
            dist-electron/*.zip
            dist-electron/latest-*.yml
            dist-electron/*.blockmap
          )
          if [[ ${#artifacts[@]} -eq 0 ]]; then
            echo "No notarized macOS arm64 artifacts found in dist-electron" >&2
            exit 1
          fi
          release_tag="${RELEASE_TAG:-}"
          if [[ -z "$release_tag" ]]; then
            echo "Release tag not provided" >&2
            exit 1
          fi
          repo="${REPO}"
          for artifact in "${artifacts[@]}"; do
            echo "Uploading $artifact to $repo@$release_tag"
            gh release upload "$release_tag" "$artifact" --repo "$repo" --clobber
          done

  windows-x64:
    name: Windows x64
    needs: prepare-release
    environment: electron
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          profile: minimal
          targets: x86_64-pc-windows-msvc
      - name: Install dependencies (bun)
        run: bun install --frozen-lockfile
      - name: Write .env for build
        shell: bash
        run: |
          cat > .env <<EOF
          NEXT_PUBLIC_CONVEX_URL=${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
          NEXT_PUBLIC_STACK_PROJECT_ID=${{ secrets.NEXT_PUBLIC_STACK_PROJECT_ID }}
          NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY=${{ secrets.NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY }}
          NEXT_PUBLIC_WWW_ORIGIN=${{ secrets.NEXT_PUBLIC_WWW_ORIGIN }}
          NEXT_PUBLIC_GITHUB_APP_SLUG=${{ secrets.NEXT_PUBLIC_GITHUB_APP_SLUG }}
          EOF
      - name: Build native Rust addon
        working-directory: apps/server/native/core
        shell: pwsh
        run: bunx --bun @napi-rs/cli build --platform --release
      - name: Generate icons
        working-directory: apps/client
        run: bun run ./scripts/generate-icons.mjs
      - name: Build & publish Windows x64 to GitHub Releases
        env:
          GH_TOKEN: ${{ github.token }}
          PUBLISH_FLAG: ${{ github.event_name == 'release' && 'always' || 'never' }}
        working-directory: apps/client
        run: bunx electron-vite build -c electron.vite.config.ts && bunx electron-builder --config electron-builder.json --win --x64 --publish always --config.publish.provider=github --config.publish.owner="${{ github.repository_owner }}" --config.publish.repo="${{ github.event.repository.name }}"

  linux-x64:
    name: Linux x64
    needs: prepare-release
    environment: electron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          profile: minimal
          targets: x86_64-unknown-linux-gnu
      - name: Install dependencies (bun)
        run: bun install --frozen-lockfile
      - name: Write .env for build
        shell: bash
        run: |
          cat > .env <<EOF
          NEXT_PUBLIC_CONVEX_URL=${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
          NEXT_PUBLIC_STACK_PROJECT_ID=${{ secrets.NEXT_PUBLIC_STACK_PROJECT_ID }}
          NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY=${{ secrets.NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY }}
          NEXT_PUBLIC_WWW_ORIGIN=${{ secrets.NEXT_PUBLIC_WWW_ORIGIN }}
          NEXT_PUBLIC_GITHUB_APP_SLUG=${{ secrets.NEXT_PUBLIC_GITHUB_APP_SLUG }}
          EOF
      - name: Build native Rust addon
        working-directory: apps/server/native/core
        shell: bash
        run: bunx --bun @napi-rs/cli build --platform --release
      - name: Generate icons
        working-directory: apps/client
        run: bun run ./scripts/generate-icons.mjs
      - name: Build & publish Linux AppImage x64 to GitHub Releases
        env:
          GH_TOKEN: ${{ github.token }}
          PUBLISH_FLAG: ${{ github.event_name == 'release' && 'always' || 'never' }}
        working-directory: apps/client
        run: bunx electron-vite build -c electron.vite.config.ts && bunx electron-builder --config electron-builder.json --linux AppImage --x64 --publish always --config.publish.provider=github --config.publish.owner="${{ github.repository_owner }}" --config.publish.repo="${{ github.event.repository.name }}"
